[MI100][FP16]Fix wrw's very small ho and wo error
ROCmSoftwarePlatform/MIOpen pull request #1000
Opened 2021-06-22 09:45 UTC by shaojiewang

fix #996 
fix asm igemm wrw hoxwo less than b_padding bug.

2021-06-22 15:07 UTC, atamazov requested changes
Please fix merge conflicts and revert W/A for #996

2021-06-24 03:15 UTC, shaojiewang commented
> Please fix merge conflicts and revert W/A for #996

Merged.

2021-06-24 13:19 UTC, atamazov requested changes
Almost almost done

2021-06-24 13:19 UTC, atamazov commented on test/CMakeLists.txt
>  # WORKAROUND_ISSUE_996
Please remove comment as well. Or you think we may need it in the future?

2021-06-24 14:16 UTC, atamazov commented on test/CMakeLists.txt
>  # WORKAROUND_ISSUE_996
@shaojiewang I'll do it myself

2021-06-24 14:23 UTC, atamazov commented
CI run `#2` has passed all the tests.

2021-06-24 14:28 UTC, atamazov commented
@JehandadKhan @junliume This PR adds a new parameter to kernels, thus making 4.3 precompiled kernels package for MI100 incompatible with current develop (and with MIOpen Mainline when this change gets merged there).

2021-06-24 14:29 UTC, atamazov approved these changes
LGTM!

2021-06-24 14:30 UTC, merged

2021-06-24 14:40 UTC, JehandadKhan commented
@atamazov Please let me know when this gets promoted to mainline

2021-06-24 14:45 UTC, atamazov commented
@JehandadKhan I will try to not forget about it. Please also try to keep an eye on the "MIOpen promotion: Mainline" mail thread. "PR #1000" is easy to remember ;)