[HOTFIX] remove unsed kernel arg for wrw fp32 NCHW
ROCmSoftwarePlatform/MIOpen pull request #1013
Opened 2021-06-26 07:24 UTC by carlushuang

This resolve issue https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1012, when under fp32 wrw, it seems feed in more kernel arg than needed. This seems OK under HIP, but in OCL it will report issue. But anyway we need keep consistent kernel arg with metadata declaration.

@shaojiewang please double check this fp32 wrw

2021-06-26 07:39 UTC, shaojiewang submitted a review, later dismissed

2021-06-26 07:39 UTC, atamazov requested changes
Thanks for quick response. Constness of buffers also needs to be fixed, see https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1012#issuecomment-868895217.

What about regression tests?

2021-06-26 07:42 UTC, atamazov commented
> This seems OK under HIP.

I think this is not ok, https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1012#issuecomment-868896151

2021-06-26 08:09 UTC, carlushuang commented
> Constness of buffers also needs to be fixed, see #1012 (comment).
OK, let me add that part into this PR

> What about regression tests?
I guess this fix does not introduce regression? If can't work (e.g. after this PR fail on HIP), the CI will just fail

2021-06-26 11:34 UTC, atamazov commented
@carlushuang 
> > What about regression tests?
> 
> I guess this fix does not introduce regression? If can't work (e.g. after this PR fail on HIP), the CI will just fail

Or course, not. But this PR should add some regression tests that should prevent this bug in the future (see #1012). If you need assistance, please let me know and I'll add them to this branch.

2021-06-26 13:22 UTC, carlushuang commented
@atamazov ok sure, I think need your help on adding some tests in this branch, in case I'm not quite clear of the regression of this PR.
Thanks :)

2021-06-30 00:04 UTC, atamazov commented
@carlushuang 
> @atamazov ok sure, I think need your help on adding some tests in this branch, in case I'm not quite clear of the regression of this PR.  Thanks :)

Done in b6a3ff7. I would like to make this commit absolutely clear for you _before_ merging this. Please review this commit and compare it with the description of #1012. Ask if something is unclear.

2021-06-30 00:29 UTC, carlushuang commented
@atamazov the flag `--disable-validation` is added, because we don't care about the result is correct or not, but this test it self will fail (because of extra kernel arg) right?

2021-06-30 13:53 UTC, atamazov commented
We didn't have a MI100 test for OpenCL backend, so the test weren't run. dca7901 resolves this.

2021-06-30 21:54 UTC, atamazov submitted a review, later dismissed

2021-06-30 21:58 UTC, atamazov approved these changes

2021-06-30 23:04 UTC, merged

2021-07-01 16:04 UTC, atamazov commented on test/CMakeLists.txt
> +    --disable-validation)
:anchor: