Documentation assembling fix
ROCmSoftwarePlatform/MIOpen pull request #1051
Opened 2021-07-23 15:11 UTC by averinevg

It looks like the documentation assembling is broken, I've got the following exception after `make doc`:

`Exception occurred:`
`  File "conf.py", line 101, in <module>`
`    version_line = next(itertools.ifilter(lambda x:'rocm_setup_version' in x, open('../../CMakeLists.txt').readlines()))`
`AttributeError: module 'itertools' has no attribute 'ifilter'`

Modern operation systems use python3 instead of python2. itertools.ifilter() exists only in python2 environment.  So I changed it to built-in filter(). The exception is no longer thrown, I've got another error though. I will work further.

2021-07-23 16:47 UTC, atamazov commented
> It looks like the documentation assembling is broken, I've got the following exception after make doc...

I am afraid that this is not so. `make doc` is tested on our CI (see the `Fp32 OpenCL Debug + Codecov` stage in Jenkinsfile) and there is none exceptions. Perhaps you don't have all the necessary dependencies installed (or their versions are wrong)?

2021-07-26 16:40 UTC, averinevg commented
@atamazov This exception is definitely caused by wrong python version. The code does not work on python 3. But [Python 2 is EOL](https://devguide.python.org/devcycle/#end-of-life-branches). Wouldn't it be better to redo it using python 3?

2021-07-26 16:41 UTC, averinevg commented
@atamazov This exception is definitely caused by wrong python version. The code does not work on python 3. But [Python 2 is EOL](https://devguide.python.org/devcycle/#end-of-life-branches). Wouldn't it be better to redo it using python 3?

2021-07-26 23:54 UTC, atamazov commented
> @atamazov This exception is definitely caused by wrong python version. The code does not work on python 3. But [Python 2 is EOL](https://devguide.python.org/devcycle/#end-of-life-branches). Wouldn't it be better to redo it using python 3?

@pfultz2 Paul, what is your opinion?

2021-07-27 18:38 UTC, pfultz2 commented
Its probably good to switch to python 3, but we need to update the dockerfile to install the doc dependencies with python 3 rather than python 2(i think just changing it from `pip install` to `pip3 install` in the dockerfile should work).

2021-07-27 23:24 UTC, atamazov commented
@pfultz2 Thank you.

2021-07-28 19:15 UTC, atamazov commented
@averinevg @pfultz2 is busy with MIGraphX so please remind him to review (and expect delays anyway). Recommendation: check the history of modified files and assign appropriate reviewers. In case of problems, please ask @junliume or @JehandadKhan to help with this.

2021-07-28 19:19 UTC, pfultz2 requested changes

2021-07-28 19:19 UTC, pfultz2 commented on doc/requirements.txt
> +recommonmark
The versions should be pinned.

2021-07-29 12:32 UTC, averinevg commented
> @averinevg @pfultz2 is busy with MIGraphX so please remind him to review (and expect delays anyway). Recommendation: check the history of modified files and assign appropriate reviewers. In case of problems, please ask @junliume or @JehandadKhan to help with this.

@atamazov Thanks, I will keep that in mind

2021-07-29 16:51 UTC, averinevg commented on doc/requirements.txt
> +recommonmark
Fixed, thanks!

2021-07-30 11:08 UTC, atamazov commented
@averinevg Click `[Ready for review]` if this is so.

2021-07-30 11:13 UTC, averinevg commented
> @averinevg Click `[Ready for review]` if this is so.

@atamazov Not yet. Documentation is generated with wrong formatting and broken links.

2021-07-30 12:34 UTC, averinevg commented
Unmaintained [recommonmark](https://recommonmark.readthedocs.io/en/latest/) was replaced by [myst-parser](https://myst-parser.readthedocs.io/en/latest/index.html) according to https://github.com/readthedocs/recommonmark/issues/221

2021-07-30 12:37 UTC, atamazov commented
Please add https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1051#issuecomment-889863294 to the PR description (the topmost comment)

2021-07-30 12:40 UTC, atamazov commented
Please open your next PR in this repo. PRs from forks:
- Require manual intervention to launch CI jobs
- Cannot be updated by other team members (if necessary, which is not very rare case) unless you grant write access to your repo

2021-08-10 04:11 UTC, junliume commented
Ping @pfultz2 and @JehandadKhan  for review :)

2021-08-10 17:10 UTC, JehandadKhan approved these changes

2021-08-10 17:11 UTC, merged