[MI100][test]fix issue 995:add some fp16 only test cases for asm igemm wrw nchw
ROCmSoftwarePlatform/MIOpen pull request #1068
Opened 2021-07-30 07:11 UTC by shaojiewang

Add regression test for #995 , 4 cases only applicable for fp16.

2021-07-30 13:00 UTC, atamazov requested changes
This should be also resolved:
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/097769a499d3971a6a9bf4f3cc37314f3fd8f149/test/CMakeLists.txt#L1156-L1157

2021-07-30 22:48 UTC, atamazov submitted a review, later dismissed
Let me repeat:

This should be also resolved:
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/097769a499d3971a6a9bf4f3cc37314f3fd8f149/test/CMakeLists.txt#L1156-L1157

I mean that the comment should be removed and the test case should be uncommented.

2021-07-31 03:00 UTC, shaojiewang commented
> Let me repeat:
> 
> This should be also resolved:
> https://github.com/ROCmSoftwarePlatform/MIOpen/blob/097769a499d3971a6a9bf4f3cc37314f3fd8f149/test/CMakeLists.txt#L1156-L1157
> 
> I mean that the comment should be removed and the test case should be uncommented.

ok, understand.

2021-07-31 03:11 UTC, shaojiewang commented
> Let me repeat:
> 
> This should be also resolved:
> https://github.com/ROCmSoftwarePlatform/MIOpen/blob/097769a499d3971a6a9bf4f3cc37314f3fd8f149/test/CMakeLists.txt#L1156-L1157
> 
> I mean that the comment should be removed and the test case should be uncommented.

This case is not applicable for --half mode. Move it to a float only test.

2021-07-31 03:29 UTC, shaojiewang commented
Also remove W/A for 954.

2021-08-03 22:03 UTC, merged

2024-04-05 13:27 UTC, atamazov commented on test/CMakeLists.txt
> +add_custom_test(test_conv_igemm_dynamic_xdlops_bwd_float SKIP_UNLESS_ALL HALF_DISABLED FLOAT_ENABLED GFX908_ENABLED VEGA_DISABLED
The code move moved to gtest in #2409, bug still persists, details at https://github.com/ROCm/MIOpen/pull/2409/files#r1553637436