[NFC] Post review of #1230: Asm igemm nhwc native bf16 kernel on gfx90a
ROCmSoftwarePlatform/MIOpen pull request #1248
Opened 2021-10-29 07:04 UTC by shaojiewang

Fix post review comment of #1230.
Note: Post review of #1227 will be fixed within #1247 by @carlushuang.

----
_Clarification by @atamazov:_ This should resolve bullets (2) and (3) from #1241. No Functional Changes.

2021-10-29 18:42 UTC, junliume commented
> fix post review comment of #1227 and #1230

@shaojiewang Thanks for the quick actions! Please check the tasks in:
https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1241

and if all tasks are completed in this PR, please mark it ready for review :)

2021-11-01 00:01 UTC, shaojiewang commented
> > fix post review comment of #1227 and #1230
> 
> @shaojiewang Thanks for the quick actions! Please check the tasks in: #1241
> 
> and if all tasks are completed in this PR, please mark it ready for review :)

Yes, sure.

2021-11-03 14:49 UTC, atamazov submitted a review, later dismissed

2021-11-03 14:49 UTC, atamazov commented on src/include/miopen/solver.hpp
> +    void SetParamsForKSplit(const ConvolutionContext& ctx, const size_t& occupancy);
```suggestion
    private:
    void SetParamsForKSplit(const ConvolutionContext& ctx, const size_t& occupancy);
```
basically, `ComputeKernelOccupancy()` should be private as well.

2021-11-03 14:49 UTC, atamazov commented on src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
> +            //gemm_k_global_split = occupancy;
Please remove

2021-11-03 14:49 UTC, atamazov commented on src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
> +                        // gemm_k_global_split = occupancy;
ditto

2021-11-04 00:50 UTC, shaojiewang commented on src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
> +            //gemm_k_global_split = occupancy;
removed

2021-11-04 00:50 UTC, shaojiewang commented on src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
> +                        // gemm_k_global_split = occupancy;
removed

2021-11-04 00:58 UTC, junliume approved these changes

2021-11-04 05:18 UTC, carlushuang approved these changes
LGTM

2021-11-05 01:52 UTC, shaojiewang commented
conflicts resolved

2021-11-05 01:59 UTC, carlushuang approved these changes
LGTM

2021-11-07 09:04 UTC, junliume approved these changes

2021-11-07 09:05 UTC, junliume commented
@atamazov  gentle ping for review input on this one :)

2021-11-08 19:35 UTC, atamazov commented on src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
> +    const auto precision  = ctx.IsFp16() ? miopenHalf : (ctx.IsBfp16() ? miopenBFloat16 : miopenFloat);
[Note] https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1230#discussion_r737886602

2021-11-08 19:57 UTC, atamazov commented on src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
> +void PerformanceConfigAsmImplicitGemmGTCWrwXdlopsNHWC::SetParamsForKSplit(const ConvolutionContext& ctx, const size_t& occupancy)
Resolves https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1230#discussion_r737880526

2021-11-08 20:00 UTC, atamazov requested changes
- This is not fixed: https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1230#discussion_r737532105

2021-11-09 05:29 UTC, shaojiewang commented
> * This is not fixed: [#1230 (comment)](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1230#discussion_r737532105)

let's move to  [#1230 (comment)](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1230#discussion_r737532105)

2021-11-09 13:22 UTC, atamazov approved these changes
LGTM!

2021-11-09 16:26 UTC, merged