Replace deprecated HIP API (SWDEV-318154)
ROCmSoftwarePlatform/MIOpen pull request #1394
Opened 2022-01-31 15:06 UTC by averinevg

`hipCtxGetCurrent()` and `hipCtxSetCurrent()` were added to better support tensorflow which was using the context API. Since HIP context API were removed from tensorflow codebase (https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/58), these calls can be removed.

Changes:
- `hipCtxGetCurrent()` and `hipCtxSetCurrent()` removed
- `hipHccModuleLaunchKernel()` replaced with `hipExtModuleLaunchKernel()`
- `-Wno-deprecated-declarations` removed
- `MIOPEN_WORKAROUND_ROCM_COMPILER_SUPPORT_ISSUE_30` for https://github.com/RadeonOpenCompute/ROCm-CompilerSupport/issues/30 is not necessary since ROCm 4.3.

2022-01-31 16:49 UTC, atamazov requested changes

2022-01-31 16:49 UTC, atamazov commented on src/hip/handlehip.cpp
> +static void toCallHipInit() __attribute__((constructor(1000)));
This is not necessary in unnamed namespace.

2022-01-31 16:49 UTC, atamazov commented on src/hip/handlehip.cpp
> +static hipCtx_t get_ctx()
Please define local functions in unnamed namespace (instead of static)

2022-01-31 16:50 UTC, atamazov commented on src/hip/handlehip.cpp
> +static hipCtx_t get_ctx()
Or keep this as is.

2022-02-04 18:08 UTC, shurale-nkn approved these changes
LGTM

2022-02-04 19:45 UTC, atamazov requested changes

2022-02-04 19:45 UTC, atamazov commented on cmake/EnableCompilerWarnings.cmake
> +                -Wno-global-constructors
Hmm... Why we need this new suppression?

2022-02-04 19:45 UTC, atamazov commented on src/hip/handlehip.cpp
> -#define MIOPEN_WORKAROUND_ROCM_COMPILER_SUPPORT_ISSUE_30 (MIOPEN_USE_COMGR && BUILD_SHARED_LIBS)
Is it so that we no longer need a workaround for https://github.com/RadeonOpenCompute/ROCm-CompilerSupport/issues/30 ?

2022-02-08 14:52 UTC, atamazov commented on src/hip/handlehip.cpp
> -#define MIOPEN_WORKAROUND_ROCM_COMPILER_SUPPORT_ISSUE_30 (MIOPEN_USE_COMGR && BUILD_SHARED_LIBS)
[process] @averinevg Let me "resolve" my review comments myself (unless the case is trivial), thanks!

2022-02-08 15:45 UTC, atamazov approved these changes
LGTM!

2022-02-10 15:26 UTC, merged