Fix Headers for Boost v1.78+
ROCmSoftwarePlatform/MIOpen pull request #1490
Opened 2022-03-30 12:00 UTC by JP-Ellis

Boost's issues with `noinline` (see #658) have been fixed upstream in
boostorg/config#393 which was included in v1.78 of Boost; however, in order for
it to work properly Boost library headers must be included after we include
headers which define `HIP_VERSION` (which come through `kernel.hpp` and headers
therein).

Whilst most files worked fine, there were a small number which included a Boost
library before `HIP_VERSION` was defined causing a compilation error.

This will also allow MIOpen to be built against the system Boost instead of
requiring it to be compiled specifically for MIOpen.

Fixes #1489.

2022-04-07 09:33 UTC, atamazov approved these changes
No objections other than couple of formatting issues.

2022-04-07 09:33 UTC, atamazov commented on src/include/miopen/mlo_internal.hpp
> +                           : batch * batch_stride * channel_stride * stride * w_stride * data_len;
Please revert this.

2022-04-07 09:33 UTC, atamazov commented on src/include/miopen/mlo_internal.hpp
> +                           : batch * batch_stride * channel_stride * stride * w_stride * data_len;
Ditto.

2022-04-08 01:59 UTC, junliume commented
@JP-Ellis  @atamazov  It's on roadmap that when we update to C++17 standard we may not need boost after all.

2022-04-08 02:56 UTC, JP-Ellis commented
Sorry for the extra formatting changes.  Perhaps that was the result of an automatic format-on-save.  The changes in the PR now only add new headers.

2022-04-08 02:57 UTC, JP-Ellis commented on src/include/miopen/mlo_internal.hpp
> +                           : batch * batch_stride * channel_stride * stride * w_stride * data_len;
Fixed in latest commit.

2022-04-08 14:04 UTC, atamazov commented
@JP-Ellis Nada problemas))

2022-04-08 14:04 UTC, atamazov approved these changes

2022-04-26 15:18 UTC, atamazov commented
> Boost's issues with `noinline` (see #658) have been fixed upstream in [boostorg/config#393](https://github.com/boostorg/config/pull/393) which was included in v1.78 of Boost; 

The reason of the above problem is incorrect fix in BOOST (https://github.com/boostorg/config/pull/393#discussion_r858808126). 

> however, in order for it to work properly Boost library headers must be included after we include headers which define `HIP_VERSION` (which come through `kernel.hpp` and headers therein).

kernep.hpp is too much, -- it imports too may declarations to the places where such declarations are not really required.

The recommendation is adding a workaround to `config.h.in` like this:
```C++
/// Workaround for https://github.com/boostorg/config/issues/392#issuecomment-1109889533
/// \todo Remove the W/A as soon we switch to the properly fixed boost.
#if MIOPEN_BACKEND_HIP
#include <hip/hip_version.h>
#endif
```
And then include config.h instead of kernel.hpp where required.

The W/A is to be removed when we switch to the properly fixed boost.

2022-04-26 15:19 UTC, atamazov requested changes
Let's add W/A into config.h and revert (almost all) other changes. Please see https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1490#issuecomment-1109928102 for more info.

2022-05-11 22:21 UTC, junliume commented
Hi @JP-Ellis, can you make the recommended changes? I have tested on dev machines and they are working properly. We just want to let it run through the whole set of CI first.
If you do not have time, I can try to create another PR for the purpose. Thanks!
CC: @atamazov

2022-05-24 18:47 UTC, junliume commented
Close this one and replaced with #1543

2022-05-24 18:47 UTC, closed without merging