[enhancement] ConvBinWinogradRxSf2x3 / f3x2 solvers merge
ROCmSoftwarePlatform/MIOpen pull request #1533
Opened 2022-04-28 17:19 UTC by johnny-keker

This PR merges almost similar `ConvBinWingradRxSf2x3` and `ConvBinWingradRxSf3x2` solvers into one `ConvBinWinoRxS` solver, which reduces the amount of duplicated code. In order to provide similar functionality, new solver uses templates:

```
    ConvBinWinoRxS<2, 3>;
    ConvBinWinoRxS<3, 2>;
```

@atamazov please review

2022-04-29 00:47 UTC, junliume commented
@Slimakanzer We are having some issues with Perf DB Deserialize Test. I think it is because of the merge of two solvers.
@JehandadKhan maybe the DB should be updated?

2022-04-29 20:22 UTC, atamazov requested changes
If a solver is renamed, then
- correctness: the affected solver must be registered with different Solver Id.
- performance: find-db must be updated at least. If solver is tunable, then perf-db must be updated too.

2022-04-29 20:24 UTC, atamazov commented on src/solver.cpp
> -    RegisterWithSolver(registry, ++id, ConvBinWinogradRxSf3x2{}, miopenConvolutionAlgoWinograd);
here

2022-04-29 20:24 UTC, atamazov commented on src/solver.cpp
> -    RegisterWithSolver(registry, ++id, ConvBinWinogradRxSf2x3{}, miopenConvolutionAlgoWinograd);
and here

2022-04-29 20:43 UTC, atamazov commented
@johnny-keker BTW you have to update doc/DebuggingAndLogging.md

Or you can implement custom GetSolverDbId() functions and keep solver names intact. I think this is the best solution.

2022-05-02 20:57 UTC, johnny-keker commented
> @johnny-keker BTW you have to update doc/DebuggingAndLogging.md
> ### green_circle Or you can implement custom GetSolverDbId() functions and keep solver names intact. I think this is the best solution.

Thanks for the suggestion! Implemented in [74c72f6](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1533/commits/74c72f64ecd7939b7272d00bab0fac7f46d7f016)

2022-05-04 15:29 UTC, Slimakanzer commented on src/solver/conv_winoRxS.cpp
> +    if (! (params.kernel_stride_w == 1
Please check these changes. 
It means that the case is applicable only with `kernel_stride=1`, even if it was _F2x3_ solver.

2022-05-05 15:23 UTC, atamazov requested changes
Almost good, but no go yet.

Please also resolve https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1533#discussion_r864978898, that comment is blocking.

2022-05-05 15:23 UTC, atamazov commented on src/solver/conv_winoRxS.cpp
> +        return boost::none;
[Recommendation] This should construct an instance of `boost::optional<PerformanceConfigConvBinWinogradRxS>` that is empty:
```suggestion
        return {};
```

2022-05-05 15:23 UTC, atamazov commented on src/solver/conv_winoRxS.cpp
> +        boost::optional<PerformanceConfigConvBinWinogradRxS> fromEnv =
```suggestion
        const auto fromEnv =
```

2022-05-05 15:23 UTC, atamazov commented on src/solver/conv_winoRxS.cpp
> +        // if(params.kernel_stride_w == 1)
Do we need this comment?

2022-05-05 15:27 UTC, atamazov commented
@johnny-keker Can you please also describe how the refactored solvers were tested?

2022-05-09 06:45 UTC, junliume approved these changes

2022-05-09 06:48 UTC, junliume requested changes
Second thoughts, maybe not quite there yet. I am checking CI pipelines again.

2022-05-15 05:21 UTC, junliume commented
@Slimakanzer  and @johnny-keker CI have passed. However, there are some merge conflicts. Could you please resolve them and try to merge this PR?

2022-05-24 16:39 UTC, johnny-keker commented
@junliume I resolved the conflicts, and CI seems to be passed. Should we consider merging?

2022-05-25 16:10 UTC, junliume approved these changes

2022-05-26 16:52 UTC, merged