[#1537][#1557] Explicitly require MIOpenGEMM for OpenCL and Fix tensor_ops.cpp debug issue
ROCmSoftwarePlatform/MIOpen pull request #1561
Opened 2022-05-26 22:29 UTC by junliume

Fix #1537 and #1557

2022-05-27 16:34 UTC, averinevg requested changes

2022-05-27 16:34 UTC, averinevg commented on README.md
> +## Installing MIOpen kernels package
```suggestion
## Installing MIOpen kernels package
```

2022-05-27 17:53 UTC, junliume commented
Thank you, @averinevg !

2022-05-27 21:43 UTC, averinevg approved these changes

2022-05-28 08:11 UTC, DrizztDoUrden approved these changes

2022-05-29 07:33 UTC, merged