[Enhancement][#1583] Disable usage of entities from miopenDataType_t
ROCmSoftwarePlatform/MIOpen pull request #1608
Opened 2022-06-27 09:35 UTC by MelanieWindt

Fix for an issue #1583

2022-06-27 16:21 UTC, atamazov requested changes
Almost done! Please do not hesitate to provide your comments (or simply phone me if you would like).

2022-06-27 16:26 UTC, atamazov commented on src/include/miopen/miopen_api_wrapper.hpp
> +#ifndef GUARD_MIOPEN_API_WRAPPERS_HPP_
> ⚠️ The file should **_replace_** miopen.h in library sources.

The above means that there should be no `#include <miopen/miopen.h>` in the codebase after your change.

2022-06-27 19:37 UTC, atamazov commented
@pfultz2 Answered at https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1583#issuecomment-1167782957

2022-07-02 17:17 UTC, atamazov requested changes

2022-07-02 17:17 UTC, atamazov commented on driver/conv_driver.hpp
> +        auto din_tmp = tensor<Tgpu>(miopen::ToApi(miopen::deref(inputTensor).GetType()));
`ToApi` should not be here. It should be used only when we want to call public API function, e.g. `miopenSetTensorDescriptor`.

When you remove `ToApi`, you will see a build error. The reason of the error is incorrect `.GetType()` which should be removed.

2022-07-02 17:20 UTC, atamazov commented on src/include/miopen/miopen_api_wrapper.hpp
> +inline DataType miopenApiToInternal(miopenDataType_t type) {
Resolved

2022-07-02 17:20 UTC, atamazov commented on src/include/miopen/miopen_api_wrapper.hpp
> +inline miopenDataType_t miopenInternalToApi(DataType wrapper_type) {
Resolved

2022-07-02 17:20 UTC, atamazov commented on src/include/miopen/miopen_api_wrapper.hpp
> +#ifndef GUARD_MIOPEN_API_WRAPPERS_HPP_
Resolved

2022-07-02 17:20 UTC, atamazov commented on driver/InputFlags.hpp
> +#include <miopen/miopen_api_wrapper.hpp>
Resolved

2022-07-27 01:19 UTC, junliume commented
@MelanieWindt could you help to push forward with this PR? It's better if you can contribute directly instead of creating PR from forked repos, so the CI can automatically start. Thanks!

2022-07-27 03:50 UTC, junliume commented
@MelanieWindt  Strange error:
```
/home/jenkins/workspace/MLLibs_MIOpen_PR-1608/src/include/miopen/api/miopen.hpp:63:2: error: namespace 'miopen' ends with an unrecognized comment [google-readability-namespace-comments,llvm-namespace-comment,-warnings-as-errors]
[2022-07-27T02:08:27.586Z] } // miopen namespace

2022-08-03 07:15 UTC, junliume commented
> @MelanieWindt Strange error:
> 
> ```
> /home/jenkins/workspace/MLLibs_MIOpen_PR-1608/src/include/miopen/api/miopen.hpp:63:2: error: namespace 'miopen' ends with an unrecognized comment [google-readability-namespace-comments,llvm-namespace-comment,-warnings-as-errors]
> [2022-07-27T02:08:27.586Z] } // miopen namespace
> ```

@MelanieWindt could you follow up on this PR?

2022-08-03 22:25 UTC, atamazov commented
@junliume @MelanieWindt I do not think we'll merge this because of https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1608#discussion_r907621191. However I am going to use this branch to perform similar checks with other public enums (as soon as I have suitable time for this) in order to make sure we use them correctly everywhere. I would recommend converting this to a draft for now.

> // miopen namespace

That's simple and funny. llvm and google want either nothing or `// namespace <NAME>` after closure of a namespace and we have this weird warning enabled.

2022-08-09 15:21 UTC, DrizztDoUrden commented on src/include/miopen/miopen_api_wrapper.hpp
> +#define miopenDouble    miopen::DataType::Double
Otherwise, almost no one would be using new code and macros usage would keep being propagated everywhere.

2023-10-30 15:48 UTC, JehandadKhan commented
@atamazov  From the discussion on the issue, I am of the opinion that we should implement this as a tidy check instead of adding a wrapper in code.

2023-10-30 19:34 UTC, atamazov commented
@JehandadKhan No objections. Let's close this.

2023-10-30 20:02 UTC, closed without merging