Fixed pooling command printing
ROCmSoftwarePlatform/MIOpen pull request #1649
Opened 2022-07-26 17:33 UTC by DrizztDoUrden

Command is now printed with args in a driver-accepted format, rather than old non supported one.

2022-07-26 17:35 UTC, DrizztDoUrden commented
@atamazov I can't set you as a reviewer, but here we are.

2022-07-26 18:41 UTC, junliume commented
@DrizztDoUrden  I built your branch and tried to test locally:
```
/root/MIOpen/build# ./bin/MIOpenDriver pool -M 0 -n 2 -c 2 -H 1 -W 5 -y 1 -x 1 -p 0 -q 0 -v 1 -u 1 -m avg -F 1 -t 1
MIOpenDriver pool -M 0 -n 2 -c 2 -H 1 -W 5 -y 1 -x 1 -p 0 -q 0 -v 1 -u 1 -m avg -F 1 -t 1
Input Flag: n Not Found !
```
anything I might have missed here?

2022-07-26 21:23 UTC, junliume commented on src/pooling_api.cpp
> +        switch(miopen::deref(tensorDesc).GetType())
[2022-07-26T19:02:47.992Z] /home/jenkins/workspace/MIOpen_ddu_fix_pooling_cmd_print/src/pooling_api.cpp:45:16: error: 5 enumeration values not explicitly handled in switch: 'miopenInt32', 'miopenInt8', 'miopenInt8x4'... [clang-diagnostic-switch-enum,-warnings-as-errors]

[2022-07-26T19:02:47.992Z]         switch(miopen::deref(tensorDesc).GetType())

[2022-07-26T19:02:47.992Z]                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[2022-07-26T19:02:47.992Z] src/CMakeFiles/tidy-target-MIOpen-pooling_api_cpp.dir/build.make:57: recipe for target 'src/CMakeFiles/tidy-target-MIOpen-pooling_api_cpp' failed

2022-07-27 12:01 UTC, DrizztDoUrden commented
@jun that line won't be parced by the library at all since the command line args update. The correct line would be like this:
```
/root/MIOpen/build# ./bin/MIOpenDriver pool -M 0 --input 2x2x1x5 -y 1 -x 1 -p 0 -q 0 -v 1 -u 1 -m avg -F 1 -t 1
```
My fix doesn't change the arguments, it changes the printout to the correct format. You could use short key instead of input, but i don't remember which one, should be in --help if you care, but that makes it unreadable for anyone unfamiliar with the syntax.

2022-07-27 14:41 UTC, atamazov requested changes

2022-07-27 14:41 UTC, atamazov commented on src/pooling_api.cpp
>          default: MIOPEN_THROW(miopenStatusNotImplemented);
Let's avoid fatal errors in the debugging code. It is the library core that should do that. Here I recommend printing things like "poolint8_UNIMPLEMENTED", "poolbfp16_UNIMPLEMENTED", "poolfp64_UNIMPLEMENTED".

2022-07-27 14:46 UTC, atamazov commented
@junliume 
> ```
> MIOpenDriver pool -M 0 -n 2 -c 2 -H 1 -W 5 -y 1 -x 1 -p 0 -q 0 -v 1 -u 1 -m avg -F 1 -t 1
> Input Flag: n Not Found !
> ```
> 
> anything I might have missed here?

Please look at #1313 for more info about the new syntax.

2022-07-27 14:57 UTC, junliume commented
> @junliume
> 
> > ```
> > MIOpenDriver pool -M 0 -n 2 -c 2 -H 1 -W 5 -y 1 -x 1 -p 0 -q 0 -v 1 -u 1 -m avg -F 1 -t 1
> > Input Flag: n Not Found !
> > ```  
> >   
> > anything I might have missed here?
> 
> Please look at #1313 for more info about the new syntax.

Thanks, @atamazov !

These lines are grepped from the debug output from https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1642

So I guess something need to be changed in the debug output?

BTW~ #1642 is still an urgent issue :(

2022-07-27 19:22 UTC, atamazov commented
@junliume We are working on #1642 together with @DrizztDoUrden

2022-07-27 19:23 UTC, atamazov commented on src/pooling_api.cpp
> +           << " -F " << ((is_fwd) ? "1" : "2") << " -t 1"; // clang-format on
If `-F 2` is not actually functional, shall we better output `-F 0` instead?

2022-07-27 19:25 UTC, atamazov commented on src/pooling_api.cpp
>          default: MIOPEN_THROW(miopenStatusNotImplemented);
Resolved.

2022-07-28 18:05 UTC, DrizztDoUrden commented
@junliume As it only changes log lines not even used in the tests, I don't think we need to spend CI time for the rest of the tests, but the PR is no hurry either.

2022-08-05 10:43 UTC, DrizztDoUrden commented
@junliume this has passed the CI

2022-08-05 17:34 UTC, junliume approved these changes

2022-08-08 05:13 UTC, merged