[Hotfix] Issue 1653, Inappropriate Host API usage
ROCmSoftwarePlatform/MIOpen pull request #1657
Opened 2022-07-28 07:49 UTC by aska-0096

Fix for #1653 
Change the tensor constructor to avoid datatype not match error when construct the destination host tensor.

2022-07-28 20:12 UTC, junliume commented
Thanks, @aska-0096 ! I can verify that with this branch the issue is gone, while it really takes a long time to process to run this kernel **with CPU verification**. Mmm ... the kernel for this case surely can be optimized.
```
build git:(hotfix_issue_1653) ✗ ./bin/MIOpenDriver convfp16 -W 300 -H 100 -c 1024 -n 1 -k 4 -x 256 -y 256 -p 0 -q 0 -u 1 -v 1 -F 1 -t 1 -V 1 -l 2
MIOpenDriver convfp16 -W 300 -H 100 -c 1024 -n 1 -k 4 -x 256 -y 256 -p 0 -q 0 -u 1 -v 1 -F 1 -t 1 -V 1 -l 2
MIOpen(HIP): Info [get_device_name] Raw device name: gfx1030
MIOpen(HIP): Info [Handle] stream: 0x18c4c00, device_id: 0
MIOpen(HIP): Info [GetFindModeValueImpl] MIOPEN_FIND_MODE = NORMAL(1)
MIOpen(HIP): Info [ForwardGetWorkSpaceSize] 
MIOpen(HIP): Info [AmdRocmMetadataVersionDetect] ROCm MD version AMDHSA_COv3, HIP version 5.2.22181, MIOpen version 2.18.0.4306d3574
MIOpen(HIP): Info [GetEnvFindOnlySolverImpl] 91
MIOpen(HIP): Info [FindConvFwdAlgorithm] requestAlgoCount = 2, workspace = 6039797760
MIOpen(HIP): Info [Measure] RamDb::Prefetch time: 0.02136 ms
MIOpen(HIP): Info [TryLoad] Find-db regenerating.
MIOpen(HIP): Info [FindSolutionImpl] GemmFwdRest (not searchable)
MIOpen(HIP): Info [PrintVersionImpl] COMgr v.2.4.0, USE_HIP_PCH: 1
MIOpen(HIP): Info [EvaluateInvokers] GemmFwdRest: : 349.273 < 3.40282e+38
MIOpen(HIP): Info [EvaluateInvokers] Selected: GemmFwdRest: : 349.273, workspace_sz = 6039797760
MIOpen(HIP): Info [FindConvFwdAlgorithm] miopenConvolutionFwdAlgoGEMM	349.273	6039797760
MIOpen(HIP): Info [FindConvFwdAlgorithm] FW Chosen Algorithm: GemmFwdRest , 6039797760, 349.273
MIOpen(HIP): Info [ConvolutionForward] algo = 0, workspace = 6039797760
MIOpen(HIP): Info [ConvolutionForward] algo = 0, workspace = 6039797760
MIOpen(HIP): Info [ConvolutionForward] algo = 0, workspace = 6039797760
MIOpen(HIP): Info [ConvolutionForward] algo = 0, workspace = 6039797760
MIOpen(HIP): Info [ConvolutionForward] algo = 0, workspace = 6039797760
MIOpen(HIP): Info [ConvolutionForward] algo = 0, workspace = 6039797760
MIOpen(HIP): Info [ConvolutionForward] algo = 0, workspace = 6039797760
MIOpen(HIP): Info [ConvolutionForward] algo = 0, workspace = 6039797760
MIOpen(HIP): Info [ConvolutionForward] algo = 0, workspace = 6039797760
MIOpen(HIP): Info [ConvolutionForward] algo = 0, workspace = 6039797760
MIOpen Forward Conv. Algorithm: 0, Solution: 91/GemmFwdRest
GPU Kernel Time Forward Conv. Elapsed: 337.561920 ms (average)
stats: name, n, c, ho, wo, x, y, k, flopCnt, bytesRead, bytesWritten, GFLOPs, GB/s, timeMs
stats: fwd-conv256x256u1, 1, 1024, 1, 45, 256, 256, 4,  24159191040, 598310912, 360, 72, 2, 337.561920
Forward Convolution Verifies OK on CPU reference (0.000164426)

2022-07-28 20:13 UTC, junliume approved these changes

2022-07-28 20:47 UTC, shurale-nkn requested changes
I don't like that `TensorDescriptor` inside `tensor` will have different datatype than `tensor` and data buffer.
Someone in the future may use information from the descriptor of this tensor, disinformation cannot be allowed

2022-07-29 02:31 UTC, aska-0096 commented
> I don't like that `TensorDescriptor` inside `tensor` will have different datatype than `tensor` and data buffer. Someone in the future may use information from the descriptor of this tensor, disinformation cannot be allowed

You are right.
Made it consistent now.

2022-07-29 14:07 UTC, shurale-nkn approved these changes
LGTM

2022-07-29 15:45 UTC, atamazov commented
@aska-0096 @junliume This PR does not change the library. Please add tag `[driver]` to the title of this PR.

2022-07-29 16:41 UTC, JehandadKhan approved these changes

2022-07-29 18:07 UTC, junliume approved these changes

2022-07-29 18:56 UTC, merged

2022-08-04 14:10 UTC, atamazov commented
> @aska-0096 @junliume This PR does not change the library. Please add tag `[driver]` to the title of this PR.

Not done and merged as is. The commit message gives an impression that this is a hotfix for the library, which is not really so.

2022-08-04 21:10 UTC, junliume commented
> > @aska-0096 @junliume This PR does not change the library. Please add tag `[driver]` to the title of this PR.
> 
> Not done and merged as is. The commit message gives an impression that this is a hotfix for the library, which is not really so.

Yikes a little bit late to see this message now.