Fixed MLIR kernel count retrieval
ROCmSoftwarePlatform/MIOpen pull request #1801
Opened 2022-10-03 08:39 UTC by manupak

This commit fixes the kernel count retrieval
to include perf_config used as part of the string
that is generated to pass to the Miir API.

Note this does not change the API per se but
includes extra information (additive) to passed
on to rocMLIR side.

2022-10-03 09:17 UTC, manupak commented
This is my first PR for MIOpen and not familiar with the process. 
Any pointers on the next stepas to incorporate these changes to MIOpen would be really appreciated.

2022-10-03 13:06 UTC, jerryyin commented
Your changes looks good to me. I think one solver is missing from the list: src/solver/conv_mlir_igemm_wrw.cpp

2022-10-03 13:54 UTC, atamazov requested changes
Please resolve https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1801#issuecomment-1265411098

2022-10-04 13:01 UTC, manupak commented
@jerryyin ,

I could not find a call to MiirGetKernelCount there...

https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/src/solver/conv_mlir_igemm_wrw.cpp#L89-L119

2022-10-04 13:56 UTC, jerryyin approved these changes
I just double checked our wrw kernel count decision and you are right nonxdlops kernel will always be 1. I think we are good with this PR since we are consistent. https://github.com/ROCmSoftwarePlatform/rocMLIR/blob/d24b416757331193d1fec548e5ad6d32ffb0dfad/mlir/lib/Dialect/Rock/Generator/Conv2dGenerator.cpp#L305-L338

2022-10-04 17:00 UTC, atamazov approved these changes
LGTM!

2022-10-06 13:34 UTC, manupak commented
I just rebased and pushed the branch as there were some CI failure that seemed unrelated.

2022-10-06 21:55 UTC, junliume approved these changes

2022-10-06 21:56 UTC, merged

2022-10-07 13:38 UTC, jerryyin commented
@manupak Now that this is merged, could you file the follow-up PR to dial our tracking commit of MIOpen back to develop?

2022-10-10 09:27 UTC, manupak commented
@jerryyin will do!