New target additional list file changes
ROCmSoftwarePlatform/MIOpen pull request #1923
Opened 2023-01-06 22:23 UTC by muralinr

target addition list file changes

2023-01-09 19:18 UTC, atamazov requested changes

2023-01-09 19:18 UTC, atamazov commented on test/CMakeLists.txt
> +option( MIOPEN_TEST_GFX110X "Test on Navi31/32 (gfx1100/01)" OFF )
Typo
```suggestion
option( MIOPEN_TEST_GFX110X "Test on Navi31/32 (gfx1100/02)" OFF )
```

2023-01-09 19:21 UTC, atamazov commented
@muralinr Please prepend `[GFX11][tests]` to the title of this PR.

2023-01-09 19:25 UTC, atamazov commented on test/CMakeLists.txt
> +        elseif(ROCMINFO_OUTPUT MATCHES "gfx1100")
@muralinr Please append `OR MIOPEN_TEST_GFX110X` to line 80.

2023-01-09 19:27 UTC, atamazov commented
@muralinr Please insert
```
message(STATUS "MIOPEN_TEST_GFX110X ${MIOPEN_TEST_GFX110X}")
```
just after this:
```
message(STATUS "MIOPEN_TEST_GFX103X ${MIOPEN_TEST_GFX103X}")
```

2023-01-09 19:32 UTC, atamazov commented
@junliume @muralinr [Important] No **_custom tests_** are enabled for the new target right now. Should we enable the same custom tests as for the GFX103X? I can make a PR for this.

2023-01-09 20:13 UTC, muralinr commented
> @junliume @muralinr [Important] No **_custom tests_** are enabled for the new target right now. Should we enable (approximately) the same custom tests as we have for GFX103X? I can make a PR for this.

Yes Artem. Can you please make a PR?

2023-01-09 20:26 UTC, atamazov commented
@muralinr Sure. I can do that after this PR merged, or I can consolidate changes from here + my changes into a new PR. If you prefer the latter way, please close this one.

2023-01-09 20:27 UTC, atamazov approved these changes
LGTM!

2023-01-09 22:09 UTC, muralinr commented
> @muralinr Sure. I can do that after this PR merged, or I can consolidate changes from here + my changes into a new PR. If you prefer the latter way, please close this one.

Sure Artem. Either way is fine. I will close this PR if you put these changes in your PR. Thank you.

2023-01-09 22:56 UTC, atamazov commented
@muralinr #1925 created, this PR can be closed now.

Can you please #1925 it on the appropriate target and make sure it passes our CI? Thanks! In case of any problem please let me know or fix it yourself. In order to make changes in my PR, please accept the invitation to my fork of MIOpen, https://github.com/atamazov/MIOpen (I've sent the invitation several mins ago). Then you'll be able to `git remote add atamazov_miopen https://github.com/atamazov/MIOpen`, pull branches from there, edit and push them back as usual.

[Informative] If you're curious, I am unable to create branches in this repo due to lack of privileges.

2023-01-11 08:22 UTC, closed without merging

2023-01-27 22:27 UTC, atamazov commented on test/CMakeLists.txt
> +        elseif(ROCMINFO_OUTPUT MATCHES "gfx1100")
+gfx1101?