[W/A] disable group conv in asm igemm solver
ROCmSoftwarePlatform/MIOpen pull request #1978
Opened 2023-02-11 06:50 UTC by junliume

disable group conv in asm igemm solver.

2023-02-11 06:57 UTC, carlushuang submitted a review, later dismissed
LGTM

2023-02-11 07:04 UTC, carlushuang submitted a review, later dismissed
LGTM

2023-02-11 22:36 UTC, atamazov requested changes
- PR description is missing the reasoning
- W/A does not comply #1685 

Please do not hesitate to ask for assistance, if you need it (or if do not have time).

2023-02-12 03:09 UTC, junliume commented
@carlushuang  @atamazov : updated this PR to comply with [MIOpen lifecycle of workarounds](https://github.com/ROCmSoftwarePlatform/MIOpen/discussions/1685)

2023-02-12 15:14 UTC, atamazov approved these changes
LGTM!

2023-02-12 15:14 UTC, atamazov commented on src/include/miopen/conv/asm_implicit_gemm.hpp
> +/// https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1979
[Notice] Basically, `WORKAROUND_ISSUE_1979` says everything so the comment is not required.

2023-02-12 15:14 UTC, atamazov commented on test/CMakeLists.txt
> -option( WORKAROUND_ISSUE_1053 "" OFF) # TODO: Remove this W/A after ~6 months (in January 2023)
[Notice] The removal of `WORKAROUND_ISSUE_1053` is a by-product which is not mentioned in the description.

2023-02-13 05:41 UTC, carlushuang approved these changes
LGTM

2023-02-13 05:43 UTC, merged