Add note about local compiled kernel cache
ROCmSoftwarePlatform/MIOpen pull request #2000
Opened 2023-02-25 15:51 UTC by onitake

This adds a note to the readme that compiled kernels will be cached not installing the precompiled kernel package will only make a difference on the first run.

Closes: #1999

2023-02-27 16:36 UTC, JehandadKhan submitted a review, later dismissed

2023-02-27 16:53 UTC, atamazov requested changes

2023-02-27 16:53 UTC, atamazov commented on README.md
> +Note that all compiled kernels are locally cached in the folder `$HOME/.cache/miopen/`, so the performance impact will only apply to the first execution of a new compute kernel. There is no startup t
```suggestion
Note that all compiled kernels are locally cached in the folder `$HOME/.cache/miopen/`, so precompiled kernels reduce the startup latency only for the first execution of a neural network. Precompiled kernels do not reduce startup time on subsequent runs.
```

2023-02-27 16:54 UTC, atamazov commented on README.md
> +Note that all compiled kernels are locally cached in the folder `$HOME/.cache/miopen/`, so the performance impact will only apply to the first execution of a new compute kernel. There is no startup t
I hope this looks clearer.

2023-02-27 16:56 UTC, atamazov commented
Actually we already have a note about this at https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/doc/src/cache.md#installing-pre-compiled-kernels

2023-02-27 17:06 UTC, atamazov requested changes
I recommend updating the paragraph that begins with "Not installing these packages would not impact the functioning of MIOpen..." instead of this change.

Plus, provide there a link (`More info can be found [here](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/doc/src/cache.md#installing-pre-compiled-kernels)`)

2023-03-03 17:00 UTC, junliume commented
> I recommend updating the paragraph that begins with "Not installing these packages would not impact the functioning of MIOpen..." instead of this change.
> 
> Plus, provide there a link (`More info can be found [here](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/doc/src/cache.md#installing-pre-compiled-kernels)`)

@onitake are you interested in taking this in this PR? We can do it separately too.

2023-03-03 17:00 UTC, junliume approved these changes, later dismissed

2023-03-03 20:25 UTC, onitake commented
Great, thanks for the review!
I'll add the link as suggested.

2023-03-04 06:47 UTC, junliume approved these changes

2023-03-09 22:43 UTC, merged