Fixes for conv_asm perf config validity check.
ROCmSoftwarePlatform/MIOpen pull request #2111
Opened 2023-04-25 15:52 UTC by cderb

Remove k-split comparison with output size.
Update IsValidValue so that it is stateless, allows IsValidPerformanceConfig to be called without state.

2023-04-26 14:31 UTC, carlushuang submitted a review, later dismissed
LGTM

2023-04-26 15:17 UTC, averinevg requested changes

2023-04-26 15:17 UTC, averinevg commented on src/solver/conv_asm_implicit_gemm_gtc_bwd_nhwc.cpp
> +    return miopen::any_of(config_list, [&](auto v) { return (*this == v); });
```suggestion
    if(index < config_list.size() && *this == config_list[index])
        return true;
    return miopen::any_of(config_list, [&](auto v) { return (*this == v); });
```

2023-04-26 15:17 UTC, averinevg commented on src/solver/conv_asm_implicit_gemm_gtc_fwd_nchwc.cpp
> +    return miopen::any_of(config_list, [&](auto v) { return (*this == v); });
```suggestion
    if(index < config_list.size() && *this == config_list[index])
        return true;
    return miopen::any_of(config_list, [&](auto v) { return (*this == v); });
```

2023-04-26 15:17 UTC, averinevg commented on src/solver/conv_asm_implicit_gemm_gtc_fwd_nhwc.cpp
> +    return miopen::any_of(config_list, [&](auto v) { return (*this == v); });
```suggestion
    if(index < config_list.size() && *this == config_list[index])
        return true;
    return miopen::any_of(config_list, [&](auto v) { return (*this == v); });
```

2023-04-26 15:17 UTC, averinevg commented on src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp
> +    return miopen::any_of(config_list, [&](auto v) { return (*this == v); });
```suggestion
    if(index < config_list.size() && *this == config_list[index])
        return true;
    return miopen::any_of(config_list, [&](auto v) { return (*this == v); });
```

2023-04-27 16:35 UTC, averinevg approved these changes

2023-05-16 19:20 UTC, JehandadKhan commented
@junliume Can we merge this ?

2023-05-19 04:41 UTC, junliume approved these changes

2023-05-19 04:41 UTC, merged