[Tuning][MI250] Gold17
ROCmSoftwarePlatform/MIOpen pull request #2113
Opened 2023-04-26 20:33 UTC by cderb

Tuning for ticket SWDEV-391534
followup to #2112

2023-04-29 02:47 UTC, junliume approved these changes, later dismissed

2023-05-03 21:15 UTC, JehandadKhan requested changes
The format of FDB values in this PR is incorrect. This causes MIOpen to fail when loading the entries from the db. May be reproduced by running 

``` bash
MIOpenDriver conv -c 128 -k 128 -x 3 -y 3 -H 224 -W 224 -n 1 -p 1 -q 1 -u 2 -v 2 -F 1 -V 0
MIOpen(HIP): Info [get_device_name] Raw device name: gfx908:sramecc+:xnack-
MIOpen(HIP): Info [Handle] stream: 0xafb240, device_id: 0
MIOpen(HIP): Info [GetFindModeValueImpl] MIOPEN_FIND_MODE = DYNAMIC_HYBRID(5)
MIOpen(HIP): Info [AmdRocmMetadataVersionDetect] ROCm MD version AMDHSA_COv3, HIP version 5.4.22505, MIOpen version 2.20.0.
MIOpen(HIP): Info [GetForwardSolutions] 
MIOpen(HIP): Info [Measure] ReadonlyRamDb::Prefetch time: 195.623 ms
MIOpen(HIP): Info [Prefetch] File is unreadable: /root/.config/miopen//gfx90878.HIP.2_20_0_.ufdb.txt
MIOpen(HIP): Info [Measure] RamDb::Prefetch time: 0.015946 ms
MIOpen Error: /data/repos/MIOpen/src/conv_algo_name.cpp:56: Bad algorithm: 57802752
MIOpen(HIP): Info [FindConvFwdAlgorithm] requestAlgoCount = 2, workspace = 0
MIOpen(HIP): Info [GetForwardSolutions] 
MIOpen Error: /data/repos/MIOpen/src/conv_algo_name.cpp:56: Bad algorithm: 57802752
RunForwardGPU() FAILED, rc = 0x5
```

2023-05-11 23:20 UTC, cderb commented
@JehandadKhan 
Changed fdb format to:
<solver_name>:<kernel_time>,<workspace_sz>,<alg_lib>

2023-05-17 17:04 UTC, cderb commented
closing in favor of #2152

2023-05-17 17:04 UTC, closed without merging