remove MIOPEN_BUILD_DEV cmake var and convert to Env Var
ROCmSoftwarePlatform/MIOpen pull request #2167
Opened 2023-05-24 23:13 UTC by JehandadKhan

2023-05-24 23:14 UTC, JehandadKhan commented
@atamazov Please take a look

2023-05-24 23:15 UTC, JehandadKhan commented on test/main.cpp
> -#if MIOPEN_BUILD_DEV
@atamazov  Do you know what is going on here ?

2023-05-25 14:29 UTC, atamazov commented on test/main.cpp
> -#if MIOPEN_BUILD_DEV
Please see https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1739#issuecomment-1451016398.

How we create non-NULL stream for DEV: https://github.com/ROCmSoftwarePlatform/MIOpen/blob/b144e9dfc6e5e504d1b73b0bc072639652b057b1/src/hip/handlehip.cpp#L286

Why -- I do not know. I hope that @pfultz2 remembers this.

2023-05-25 15:00 UTC, atamazov requested changes

2023-05-25 15:00 UTC, atamazov commented on Jenkinsfile
> +    if (package_build == true && (env.BRANCH_NAME == "develop" || env.BRANCH_NAME == "main" ||
I thought that the master branch name is "master". Do we use "main" as a master branch?
Perhaps comment is outdated.

2023-05-25 15:00 UTC, atamazov commented on README.md
> +cmake -DMIOPEN_BACKEND=OpenCL ..
```suggestion
export MIOPEN_DEBUG_DEV_MODE=1
```
or remove

2023-05-25 15:00 UTC, atamazov commented on include/miopen/config.h.in
> +#define MIOPEN_INSTALLABLE (MIOPEN_NDEBUG)
The definition with correct semantics now is
```C++
#define (MIOPEN_INSTALLABLE && !(miopen::IsEnabled(MIOPEN_DEBUG_DEV_MODE{})))
```
but it is wrong from C++ point of view. Let's remove `MIOPEN_INSTALLABLE` and use equivalent C++ constructs instead of it (in logger.hpp, clhelper.hpp).

```suggestion
```

2023-05-25 15:00 UTC, atamazov commented on src/hip/handlehip.cpp
> +    if(miopen::IsEnabled(MIOPEN_DEBUG_DEV_MODE{}))
[Note] This is where we create non-null stream for DEV.

2023-05-25 15:00 UTC, atamazov commented on src/hip/handlehip.cpp
> -#if MIOPEN_BUILD_DEV
This is missing in this file:
```C++
MIOPEN_DECLARE_ENV_VAR(MIOPEN_DEBUG_DEV_MODE)
```

2023-05-25 15:00 UTC, atamazov commented on test/CMakeLists.txt
> +    set_tests_properties(${NAME} PROPERTIES ENVIRONMENT "MIOPEN_DEBUG_DEV_MODE=1;MIOPEN_USER_DB_PATH=${CMAKE_CURRENT_BINARY_DIR}")
Please revert this.

2023-05-25 15:00 UTC, atamazov commented on test/handle_test.cpp
> -#if MIOPEN_BUILD_DEV
Please check environment as usual and skip if DEV mode is not enabled. It's Ok for the test I think.

2023-05-25 15:00 UTC, atamazov commented on test/main.cpp
> -#if MIOPEN_BUILD_DEV
Ditto.

2023-05-25 15:00 UTC, atamazov commented on test/main.cpp
> -#else
Ditto.

2023-05-25 15:00 UTC, atamazov commented on test/main.cpp
> -#if MIOPEN_BUILD_DEV
Ditto

2023-05-25 15:00 UTC, atamazov commented on Jenkinsfile
> +        MIOPEN_DEBUG_DEV_MODE = "1"
Do we want to test only the library only in DEV mode? If not, then let's revert this and invent some method to control DEV mode for each stage, individually.

2023-05-25 15:00 UTC, atamazov commented on test/nightlies/JenkinsfileNightlyAux
> +        buildflag = ' -DMIOPEN_TEST_ALL=On -DCMAKE_BUILD_TYPE=releasewithdebug -DCMAKE_PREFIX_PATH=/opt/rocm'
Perhaps
```suggestion
        buildflag = ' -DMIOPEN_TEST_ALL=On -DCMAKE_BUILD_TYPE=releasewithdebug -DCMAKE_PREFIX_PATH=/opt/rocm'
        MIOPEN_DEBUG_DEV_MODE = "1"
```
The same for other changes in test/nighties

2023-08-14 16:27 UTC, closed without merging