[driver] Fix prng seed by default
ROCmSoftwarePlatform/MIOpen pull request #2319
Opened 2023-08-11 12:05 UTC by CAHEK7

Proposed solution for #2313

Probably new env variable should be documented somewhere.

@atamazov could you take a look?

2023-08-11 20:40 UTC, atamazov requested changes
Almost good!

What if we'll use environment variable (e.g. `MIOPEN_DRIVER_PRNG_LEGACY=1/0` etc) to fall back to the old code? Developers who want to use old cached data (like me) would appreciate that. I suspect that regeneration of huge amount of data may take dozen of hours.

2023-08-11 20:40 UTC, atamazov commented on driver/random.hpp
> +        MIOPEN_LOG_I("Random seed: " << seed);
Please go not use MIOPEN_LOG macros in the driver. Just output to `cout`.

2023-08-15 11:19 UTC, CAHEK7 commented
Added MIOPEN_USE_LEGACY_PRNG and MIOPEN_DRIVER_PRNG_SEED env variables.
If MIOPEN_DRIVER_PRNG_SEED == 0, it means random seed - can be useful for smoke testing.

2023-08-15 13:18 UTC, closed without merging

2023-08-15 13:20 UTC, dmikushin commented
Please take note that std::random_device [takes some costs](https://stackoverflow.com/a/39301751/4063520) associated with random state creation taken seriously. Almost definitely it should be enough to produce a time()-based seed.