cmake: generate export header function
ROCmSoftwarePlatform/MIOpen pull request #2348
Opened 2023-08-31 20:37 UTC by apwojcik

The threats model on Windows for UIF requires exporting only public API from dynamically linked libraries. Using EXPORT_ALL_SYMBOLS, CMake will export all public symbols from compilation units, including API, which is the threat model violation.
Moreover, the number of symbols allowed for exporting per single DLL on Windows is limited to 64K. Again, using the EXPORT_ALL_SYMBOLS property, we lose control over what and how it is exported.

2023-09-07 13:20 UTC, averinevg reviewed
Wouldn't it be easier to just uncomment [this line](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/src/CMakeLists.txt#L813)?

2023-10-11 22:01 UTC, JehandadKhan requested changes, later dismissed
Minor nitpick.

2023-10-11 22:01 UTC, JehandadKhan commented on src/tensor.cpp
>  // TODO(paul): Remove
The comment can go as well!

2023-10-27 00:07 UTC, junliume approved these changes

2023-10-27 00:08 UTC, merged