cmake: make building tests optional
ROCmSoftwarePlatform/MIOpen pull request #2351
Opened 2023-08-31 21:13 UTC by apwojcik

The module `CTest` automatically creates the `BUILD_TESTING` option that we use to select whether to enable testing support. The option is `ON` by default. Refer to https://cmake.org/cmake/help/latest/module/CTest.html for details.

Moreover, explicitly calling `enable_testing()` is unnecessary because the command is automatically invoked when the `CTest` module is included. Refer to https://cmake.org/cmake/help/latest/command/enable_testing.html for details.

2023-09-18 15:12 UTC, atamazov commented
@apwojcik So this is a kind of refactoring that should not lead to any functional changes?

2023-09-25 08:18 UTC, apwojcik commented
> @apwojcik So this is a kind of refactoring that should not lead to any functional changes?

Correct. The only change is when PR is merged, one may decide not to build tests while building MIOpen. For instance, that is when we build MIOpen as a dependency for MIGraphX in Windows CI.

2023-10-11 21:52 UTC, JehandadKhan approved these changes

2023-11-13 04:53 UTC, junliume approved these changes

2023-11-13 04:54 UTC, junliume requested changes, later dismissed
```
CMake Error at test/gtest/CMakeLists.txt:1 (include):

  include could not find requested file:



    googletest
```

2023-11-13 19:22 UTC, junliume approved these changes

2023-11-13 19:31 UTC, merged