comgr: fix compiling with HIP SDK 5.5+ on Windows
ROCmSoftwarePlatform/MIOpen pull request #2364
Opened 2023-08-31 23:02 UTC by apwojcik

2023-09-05 20:46 UTC, atamazov requested changes

2023-09-05 20:46 UTC, atamazov commented on src/comgr.cpp
> +#if !defined(_WIN32) && (HIP_PACKAGE_VERSION_FLAT >= 5004000000ULL)
Why in Windows the location of amd_comgr.h does not correspond to the one in Linux? Is it a bug?

2023-09-06 13:17 UTC, apwojcik commented on src/comgr.cpp
> +#if !defined(_WIN32) && (HIP_PACKAGE_VERSION_FLAT >= 5004000000ULL)
It is not a bug. We must build comgr from source code on Windows. We're talking with the respective people from HIP SDK not to build the comgr on our own. We prefer they provide the package instead. But that discussion has just started, and it is pending.

2023-10-11 21:37 UTC, JehandadKhan approved these changes

2023-10-19 17:31 UTC, junliume approved these changes

2023-10-19 17:31 UTC, merged