Bg/lwpmiopen 193 bn back
ROCmSoftwarePlatform/MIOpen pull request #2385
Opened 2023-09-11 02:19 UTC by bghimireamd

* enable BF16 in `miopenBatchNormalizationBackward`
* add CK's Batch Norm Backwards solver for `F16,  F32, F64, BF16` types
* Test added

2023-09-12 16:31 UTC, junliume commented
@bghimireamd we are having some problems with the test:
```
[2023-09-12T09:05:07.776Z] /home/jenkins/workspace/_MIOpen_bg_LWPMIOPEN-193_bn_back/build/bin/test_bn_spatial_nhwc_test --half --input {4, 64, 28, 28}, {50176, 1, 1792, 64}, packed,  
[2023-09-12T09:05:07.776Z] FAILED: -nan
[2023-09-12T09:05:07.776Z] Iteration: 0
[2023-09-12T09:05:07.776Z] Backward Batch Spatial Normalization Recalc Mean and Variance: 
[2023-09-12T09:05:07.776Z] X Input tensor: 4, 64, 28, 28
[2023-09-12T09:05:07.776Z] Delta Y Input tensor: 4, 64, 28, 28
[2023-09-12T09:05:07.776Z] Delta X output tensor output failed verification.
[2023-09-12T09:05:07.776Z] Max diff: 47584
[2023-09-12T09:05:07.776Z] Mismatch at 0: 0.000249147 != 6.37891
[2023-09-12T09:05:07.776Z] Non finite number found in gpu at 18: -nan
[2023-09-12T09:05:07.776Z] /home/jenkins/workspace/_MIOpen_bg_LWPMIOPEN-193_bn_back/build/bin/test_bn_spatial_nhwc_test --half --input {4, 64, 28, 28}, {50176, 1, 1792, 64}, packed,  
[2023-09-12T09:05:07.776Z] FAILED: -nan
[2023-09-12T09:05:07.776Z] Iteration: 0
[2023-09-12T09:05:07.776Z] Backward Batch Spatial Normalization Use Saved Mean and Variance: 
[2023-09-12T09:05:07.776Z] X Input tensor: 4, 64, 28, 28
[2023-09-12T09:05:07.776Z] Delta Y Input tensor: 4, 64, 28, 28
[2023-09-12T09:05:07.776Z] Delta X output tensor output failed verification.
[2023-09-12T09:05:07.776Z] Max diff: 42560
[2023-09-12T09:05:07.776Z] Mismatch at 0: 0.000249147 != 0.000611782
[2023-09-12T09:05:07.776Z] Non finite number found in gpu at 106: -nan

2023-09-12 18:43 UTC, CAHEK7 commented on test/fusionHost.hpp
> +void batchNormSpatialHostBwdTrain(const tensor<U>& x_input,
I know it's an old code and you've just rearranged the types. But may I ask to rename the types as well? It's not so clear what does `U` and `T` mean. And why some types were replaced.

2023-09-14 14:53 UTC, CAHEK7 commented
Could you please apply #2379

2023-09-14 16:13 UTC, junliume commented
> Could you please apply #2379

Ping @bghimireamd :)

2023-09-19 13:35 UTC, CAHEK7 requested changes

2023-09-19 13:35 UTC, CAHEK7 commented on test/gtest/bn_test_data.hpp
> +        };
```suggestion
        auto gen_value = [](auto...) {
            return prng::gen_descreet_uniform_sign(static_cast<ScaleDataType>(1e-2), 100);
        };
```
See #2397 for details.

2023-09-19 13:35 UTC, CAHEK7 commented on test/gtest/bn_test_data.hpp
> +        };
Also `#include <random>` at line 28 should be replaced with `#include "random.hpp"`.

2023-09-19 14:48 UTC, CAHEK7 commented on test/gtest/bn_test_data.hpp
> +        auto gen_var = [&](auto...) { return 1e-2 * (static_cast<MeanVarDataType>(d(gen)) + 1); };
```suggestion
        auto gen_var = [](auto...) {
            return static_cast<T>(1e-2) * static_cast<MeanVarDataType>(prng::gen_0_to_B(100) + 1);
        };
```

2023-09-28 10:50 UTC, CAHEK7 approved these changes, later dismissed

2023-10-05 14:38 UTC, junliume approved these changes

2023-10-05 14:38 UTC, merged