bg/LWPMIOPEN-192: add batch norm foward CK kernel
ROCmSoftwarePlatform/MIOpen pull request #2386
Opened 2023-09-11 14:19 UTC by bghimireamd

* add CK's Batch Norm Forward Training solver for F16,  F32, F64, BF16 types
* NHWC Layout
* GTest added

2023-09-12 16:32 UTC, junliume commented
@bghimireamd the following test is not passing
```
 test_bn_spatial_nhwc_test

2023-09-14 14:53 UTC, CAHEK7 commented
Could you please apply #2379

2023-09-19 14:50 UTC, CAHEK7 requested changes

2023-09-19 14:50 UTC, CAHEK7 commented on test/gtest/bn_test_data.hpp
> +        };
```suggestion
        auto gen_value = [](auto...) {
            return prng::gen_descreet_uniform_sign(static_cast<ScaleDataType>(1e-2), 100);
        };
```
See #2397 for details.
Also #include <random> at line 28 should be replaced with #include "random.hpp".

2023-09-19 14:50 UTC, CAHEK7 commented on test/gtest/bn_test_data.hpp
> +        auto gen_var = [&](auto...) { return 1e-2 * (static_cast<MeanVarDataType>(d(gen)) + 1); };
```suggestion
        auto gen_var = [](auto...) {
            return static_cast<T>(1e-2) * static_cast<MeanVarDataType>(prng::gen_0_to_B(100) + 1);
        };
```

2023-09-28 10:51 UTC, CAHEK7 approved these changes

2023-10-05 04:04 UTC, junliume approved these changes

2023-10-05 05:08 UTC, merged