Update the SyncDB tests to use multi-threading
ROCmSoftwarePlatform/MIOpen pull request #2407
Opened 2023-09-21 16:41 UTC by JehandadKhan

The SyncDB tests were previously serial and needed a long time to run. With the updates, they can finish in less than 10 mins per GPU arch making it realistic to add them to the CI.

2023-09-22 04:39 UTC, junliume commented on test/gtest/db_sync.cpp
> +void BuildKernel(const std::string& program_file, const std::string& program_args, miopen::Handle& handle)
```suggestion
void BuildKernel(const std::string& program_file, const std::string& program_args, [[maybe_unused]] miopen::Handle& handle)
```

2023-09-22 11:10 UTC, CAHEK7 reviewed
Since the code has been changed, I guess it's better to do some minor improvements and cleanups like container misuse or function signature.

The loops may stay unchanged as well as atomic operations, it's not so perf critical code where we want to get any second of execution time.

2023-09-22 11:10 UTC, CAHEK7 commented on test/gtest/db_sync.cpp
> +    std::map<std::pair<std::string, std::string>, bool> kdb_cache;
I guess you've meant `std::set`.

2023-09-22 11:10 UTC, CAHEK7 commented on test/gtest/db_sync.cpp
> +    std::unordered_map<KDBKey, bool> checked_kdbs;
And `std::unordered_set`.

2023-09-22 11:10 UTC, CAHEK7 commented on test/gtest/db_sync.cpp
> +    std::unordered_map<KDBKey, bool> checked_kdbs;
And `std::unordered_set`.

2023-09-22 11:10 UTC, CAHEK7 commented on test/gtest/db_sync.cpp
> +    std::unordered_map<KDBKey, bool> checked_kdbs;
And `std::unordered_set`.

2023-09-22 11:10 UTC, CAHEK7 commented on test/gtest/db_sync.cpp
> +    const int total_threads = (std::thread::hardware_concurrency() > 32 )? 32 : std::thread::hardware_concurrency();
```suggestion
    const int total_threads = std::min(static_cast<int>(std::thread::hardware_concurrency()), 32);
```

2023-09-22 11:10 UTC, CAHEK7 commented on test/gtest/db_sync.cpp
> +        ++counter;
`counter.fetch_add(1, std::memory_order_relaxed);` yields to better performance.
Defaults memory order for `operator++` is too strict.

2023-09-22 11:10 UTC, CAHEK7 commented on test/gtest/db_sync.cpp
> +        std::ignore = counter;
I'm not sure that we need this line.

2023-09-22 11:10 UTC, CAHEK7 commented on test/gtest/db_sync.cpp
> +    for(auto kidx = thread_index; kidx < data_size; kidx += total_threads)
While it's a perfect solution for GPU loops, it's not so good for CPU multicore systems, since it may have bad cache locality.

2023-09-22 11:10 UTC, CAHEK7 commented on test/gtest/db_sync.cpp
> +    const int total_threads = (std::thread::hardware_concurrency() > 32 )? 32 : std::thread::hardware_concurrency();
```suggestion
    const int total_threads = std::min(static_cast<int>(std::thread::hardware_concurrency()), 32);
```

2023-09-22 11:10 UTC, CAHEK7 commented on test/gtest/db_sync.cpp
> +        ++counter;
`counter.fetch_add(1, std::memory_order_relaxed);` yields to better performance.
Defaults memory order for `operator++` is too strict.

2023-09-22 11:10 UTC, CAHEK7 commented on test/gtest/db_sync.cpp
> +    for(auto kidx = thread_index; kidx < data_size; kidx += total_threads)
While it's a perfect solution for GPU loops, it's not so good for CPU multicore systems, since it may have bad cache locality.

2023-09-22 11:10 UTC, CAHEK7 commented on test/gtest/db_sync.cpp
>  }
```suggestion
bool CheckKDBObjects(const boost::filesystem::path& filename,
                     const std::string& kernel_name,
                     const std::string& kernel_args)
{
    static const auto kdb_cache = LoadKDBObjects(filename);
    return kdb_cache.find(std::make_pair(kernel_name, kernel_args)) != kdb_cache.end();
}
```
And adjust all the callee code.

2023-09-22 11:10 UTC, CAHEK7 commented on test/gtest/db_sync.cpp
>                      miopen::CheckKDBObjects(kdb_file_path, program_file, compile_options, found);
`bool found = miopen::CheckKDBObject...`

2023-09-22 20:12 UTC, JehandadKhan commented on test/gtest/db_sync.cpp
> +    std::map<std::pair<std::string, std::string>, bool> kdb_cache;
I did indeed :)

2023-09-22 20:17 UTC, JehandadKhan commented on test/gtest/db_sync.cpp
> +    for(auto kidx = thread_index; kidx < data_size; kidx += total_threads)
I would need to think about this a little more, meanwhile, I am open to suggestions

2023-09-22 20:20 UTC, JehandadKhan commented on test/gtest/db_sync.cpp
>  }
Done!

2023-10-03 15:34 UTC, CAHEK7 approved these changes

2023-10-13 16:27 UTC, cderb approved these changes

2023-10-13 16:27 UTC, cderb commented on test/gtest/db_sync.cpp
> +    for(auto kidx = thread_index; kidx < data_size; kidx += total_threads)
Something like if all threads have adjacent memory indexes?
```
const size_t data_block = (data_size + total_threads - 1) / total_threads //round up
const auto end_idx = std::min( (thread_index+1) * data_block, data_size );
for(auto kidx = thread_index * data_block; kidx < end_idx; ++kidx)
```

2023-10-13 16:51 UTC, JehandadKhan commented on test/gtest/db_sync.cpp
> +        ++counter;
Done

2023-10-16 16:23 UTC, cderb requested changes

2023-10-16 16:23 UTC, cderb commented on test/gtest/db_sync.cpp
> +    setenv("MIOPEN_DEVICE_CU", std::to_string(num_cu).c_str(), 1);
Setting the env this way doesn't achieve the desired result.
For 90a 104 / 110, there is no cu change and the same test runs 2x.

2023-10-18 22:00 UTC, cderb approved these changes
lgtm

2023-10-19 19:05 UTC, cderb commented
Added some changes for the weights tensor descriptor. Lengths index 1 needed division by group count. Channels needed to be swapped for backwards direction.

2023-10-30 15:15 UTC, JehandadKhan commented
@cderb  A few entries are missing in the kdb file.

2023-11-03 15:07 UTC, cderb commented
Added missing gfx90a68 kdb entries.
Added cmake switch for db_sync.
Added jenkins test stages for db_sync.

2023-11-07 17:01 UTC, JehandadKhan commented
@junliume  Can we please merge this.

2023-11-07 17:33 UTC, junliume approved these changes

2023-11-07 17:34 UTC, merged

2023-11-08 15:55 UTC, atamazov reviewed
@JehandadKhan Some recommendations for randomly found things

2023-11-08 15:55 UTC, atamazov commented on Jenkinsfile
> +			execute_cmd='./bin/test_db_sync'
[formatting] Tabs -> spaces

2023-11-08 15:55 UTC, atamazov commented on Jenkinsfile
> +			execute_cmd='./bin/test_db_sync'
[formatting] Tabs -> spaces

2023-11-08 15:55 UTC, atamazov commented on Jenkinsfile
> +                                                        needs_gpu:false, needs_reboot:false, build_install: "true")
[Recommendation] I would reformat this like
```C++
                        buildHipClangJobAndReboot(lfs_pull: true,
                                                  setup_flags: setup_flags,
                                                  config_targets: config_targets,
                                                  execute_cmd: execute_cmd,
                                                  needs_gpu:false,
                                                  needs_reboot:false,
                                                  build_install: "true")
```

2023-11-08 15:55 UTC, atamazov commented on Jenkinsfile
> +                                                        needs_gpu:false, needs_reboot:false, build_install: "true")
Ditto

2023-11-08 15:59 UTC, atamazov commented on Jenkinsfile
> +			execute_cmd='./bin/test_db_sync'
[Recommandation] @JehandadKhan These variables are used only once, and like `setup_flags: setup_flags` so maybe it is better to remove them and write simply `setup_flags: "-DMIOPEN_TEST_DBSYNC=1"`?

2023-12-21 13:32 UTC, atamazov commented on Jenkinsfile
> +			config_targets='test_db_sync'
@JehandadKhan What is the purpose of thinks like
```
config_targets='test_db_sync'
```
and then
```
buildHipClangJobAndReboot(... config_targets: config_targets ...)
```

What if we'll simply
```
buildHipClangJobAndReboot(... config_targets: 'test_db_sync' ...)
```
?