Disabling smoke stages for CI branch runs
ROCmSoftwarePlatform/MIOpen pull request #2422
Opened 2023-09-28 17:24 UTC by reidkwja

This PR disables smoke stages for branch runs.

2023-09-28 17:28 UTC, JehandadKhan approved these changes

2023-09-29 14:30 UTC, atamazov requested changes
Do we have the weekly testing process up and running? If yes, then please make sure that all the tests disabled here are engaged in weekly testing, and that the process of bug reporting is set up, and then we are fine.

Otherwise this PR should be put on hold.

/cc @JehandadKhan @junliume

2023-09-29 16:23 UTC, reidkwja commented
> Do we have the weekly testing process up and running? If yes, then please make sure that all the tests disabled here are engaged in weekly testing, and that the process of bug reporting is set up, and then we are fine.
> 
> Otherwise this PR should be put on hold.
> 
> /cc @JehandadKhan @junliume

We are in the process of setting up Nightly runs for develop [rk_nightly_run](https://github.com/ROCmSoftwarePlatform/MIOpen/compare/develop...rk_nightly_run) It will be done very soon.

2023-09-29 21:21 UTC, atamazov commented
@reidkwja Thanks for feedback.

@junliume https://github.com/ROCmSoftwarePlatform/MIOpen/labels/ON_HOLD

2023-10-03 16:43 UTC, junliume approved these changes

2023-10-03 16:44 UTC, merged