Enabling Nightly Runs for Nightly Branch w/ build_smoke_(fp32 + aux1 + fp16_bf16_int8)
ROCmSoftwarePlatform/MIOpen pull request #2437
Opened 2023-10-05 14:17 UTC by reidkwja

The following PR enables nightly (12 AM Server Time) MIOpen CI runs with the following tests included: 

build_smoke_fp32
build_smoke_aux1
build_smoke_fp16_bf16_int8

The nightly branch is "miopen_nightly" is utilized for demo-run: [miopen_nightly](https://github.com/ROCmSoftwarePlatform/MIOpen/tree/miopen_nightly)**

**Stable/protected branch w/nightly "miopen_nightly" (or another preferred name) can be created for MIOpen upon finalization/merging of this PR.

2023-10-05 15:14 UTC, JehandadKhan requested changes

2023-10-05 15:14 UTC, JehandadKhan commented on Jenkinsfile
> +        cron(env.BRANCH_NAME == "miopen_nightly" ? '0 0 * * *' : '')
Can we take the branch name from the environment? Also, I believe the schedule can be part of the Jenkins config as well

2023-10-11 17:47 UTC, JehandadKhan approved these changes

2023-10-12 20:15 UTC, junliume approved these changes

2023-10-12 20:16 UTC, merged