Workaround for issue #2492 part 2 (improvement)
ROCmSoftwarePlatform/MIOpen pull request #2510
Opened 2023-11-07 18:46 UTC by atamazov

This is continuation of #2507.

- [debug] Disabled MIOPEN_DEBUG_WORKAROUND_ISSUE_2493 during driver warm-up.
  - Fixes small problem in [#2507](#2507) that affects the driver's warmup.
- [quality] Make the computation of max granularity loss more clear.
  - Resolves https://github.com/ROCmSoftwarePlatform/MIOpen/pull/2507#discussion_r1383815382.

## :cyclone: Performance testing results

Preconditions:
- Navi21 (gfx1030/36)
- ROCm 5.7 docker, Ubuntu 20.04.5 LTS
- BUILD_DEV=On, Release build
- branch 6530353d8bed4f6dd96f2bda8231feb9c9e122d2 vs. baseline `develop` 19c6046d1a1d2ac7123fbeaf7775dd7a5749bfd3
- 93 known FP32 convolution configs

Tested modes:
- Immediate mode with default (system) find-db

Bottom line: No performance or correctness regressions on average. Detailed logs & csv files available upon request.

----
[Attribution] @junliume @JehandadKhan
- https://github.com/ROCmSoftwarePlatform/MIOpen/labels/quality
- https://github.com/ROCmSoftwarePlatform/MIOpen/labels/debugging
- https://github.com/ROCmSoftwarePlatform/MIOpen/labels/urgency_high
- https://github.com/ROCmSoftwarePlatform/MIOpen/labels/value_high (fixes warmup in the driver that affects performance testing)
- Proposed reviewers:
  - @JehandadKhan
  - @CAHEK7

2023-11-07 18:49 UTC, JehandadKhan requested changes, later dismissed

2023-11-07 18:49 UTC, JehandadKhan commented on src/solver/conv_winoRxS.cpp
> +    if(!miopen::IsDisabled(MIOPEN_DEBUG_WORKAROUND_ISSUE_2493{}) && !miopen::debug::IsWarmupOngoing)
Why is the rationale behind this?

2023-11-08 05:53 UTC, junliume commented
@cderb @JehandadKhan `dbsync gfx90a` has failed but I think it is expected? KDB update might be required for this PR.

2023-11-08 15:19 UTC, atamazov commented
@junliume I'll look into into this; should be easy to fix.

2023-11-08 15:25 UTC, atamazov commented on src/solver/conv_winoRxS.cpp
> +    if(!miopen::IsDisabled(MIOPEN_DEBUG_WORKAROUND_ISSUE_2493{}) && !miopen::debug::IsWarmupOngoing)
@JehandadKhan Without this fix, Winograd assembling is skipped during warm-up and that leads to inaccurate host-side performance testing results. Specifically, I see false ~36% drop for Average Aux Wall time (Forward) after merging #2507.

2023-11-08 15:49 UTC, atamazov commented
@junliume @JehandadKhan @shurale-nkn The root reason of the issue is that PR #2492 wasn't updated from `develop` and then tested on CI. The immediate reason is that `dbsync` tests require `MIOPEN_DEBUG_WORKAROUND_ISSUE_2493=0` in the environment. I'll prepare the fix and let you know. Most likely, I'll make it right in this PR.

2023-11-08 22:45 UTC, atamazov commented
It wasn't that easy as test was aborting on gfx1030.

2023-11-08 22:52 UTC, atamazov reviewed
Tips for reviewers

2023-11-08 22:52 UTC, atamazov commented on test/gtest/db_sync.cpp
> +            ASSERT_TRUE(TransformFindDbItem10to20(id, values))
Why this is needed: gfx1030 fdb is in legacy format.

2023-11-08 22:52 UTC, atamazov commented on test/gtest/db_sync.cpp
> +            if(val.solver_id == "ConvOclDirectFwdFused")
Strange problem that we can easily postpone for a while.

2023-11-08 22:52 UTC, atamazov commented on test/gtest/db_sync.cpp
> +            << '[' << (++failures) << "] " //
This prints number of failures in current thread.

2023-11-08 22:58 UTC, atamazov commented
@junliume @JehandadKhan @CAHEK7 Made some fixes that should unblock CI. Tested on gfx1030. Some [hints for reviewers](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/2510#pullrequestreview-1721406568) provided. Ready for the next review & CI testing round.

2023-11-10 02:12 UTC, junliume approved these changes
dbsync tests are passing now

2023-11-10 04:14 UTC, merged