Converting 3D Convolution Tests into GTests
ROCmSoftwarePlatform/MIOpen pull request #2554
Opened 2023-11-27 17:09 UTC by reidkwja

GTests cases for 3D Convolution

2023-11-30 04:31 UTC, xinlipn commented on test/gtest/conv3d_test.cpp
> +                  "data type not supported by conv_igemm_dynamic test";
> Change conv_igemm_dynamic to conv2d_test maybe?

2023-11-30 04:38 UTC, xinlipn commented on test/gtest/conv3d_test.cpp
>      const std::vector<TestCase> test_cases = {
[<TestCase>](std::vector<**TestCase**>) wont be necessary for this case, you can use std::vector<std::string> instead. Here's an example

test/gtest/conv_hip_igemm_xdlops.cpp

2023-11-30 04:48 UTC, xinlipn commented
@reidkwja  Maybe a good idea to update/merge with this PR below, which has critical fixes for environment variable updates, e.g. changing MIOPEN_DECLARE_ENV_VAR to MIOPEN_DECLARE_ENV_VAR_BOOL

https://github.com/ROCmSoftwarePlatform/MIOpen/pull/2514

2023-12-01 23:54 UTC, reidkwja commented on test/gtest/conv3d_test.cpp
> +MIOPEN_DECLARE_ENV_VAR(MIOPEN_TEST_FLOAT_ARG)
@xinlipn would this ENV be the right choice for 3DConv?

2023-12-31 16:26 UTC, atamazov requested changes

2023-12-31 16:26 UTC, atamazov commented on test/gtest/conv3d_test.cpp
> +INSTANTIATE_TEST_SUITE_P(Conv3dTest, ConfigWithFloat, testing::ValuesIn(GetTestCases("--float")));
This should be named `Conv3dTestExtra`

2023-12-31 16:26 UTC, atamazov commented on test/gtest/conv3d_test.cpp
> +    return (!s_envVar.empty() && std::strcmp(s_envVar.c_str(), float_arg) == 0);
The test should be also run when both `MIOPEN_TEST_ALL` and `MIOPEN_TEST_FLOAT_ARG` are not defined.

2023-12-31 16:26 UTC, atamazov commented on test/gtest/conv3d_test.cpp
> +    if(IsTestSupportedForDevice(handle) && miopen::IsEnabled(ENV(MIOPEN_TEST_COMPOSABLEKERNEL)) &&
The check of `MIOPEN_TEST_COMPOSABLEKERNEL` should be removed.

2023-12-31 16:26 UTC, atamazov commented on test/gtest/conv3d_test.cpp
> +#if MIOPEN_BACKEND_OPENCL
[Q] Why we need to check MIOPEN_BACKEND_OPENCL? We do not maintain this backend anymore.

2023-12-31 16:26 UTC, atamazov commented on test/gtest/conv3d_test.cpp
> +    if(devName == "gfx94" || devName == "gfx103" || devName == "gfx110")
This test should be run on all devices.

2023-12-31 16:26 UTC, atamazov commented on test/gtest/conv3d_test.cpp
> +                  "test_conv_hip_igemm_xdlops test";
The name of the test is wrong.

2023-12-31 16:28 UTC, atamazov commented
The title should look like "[tests] Converting test_conv3d_extra into GTest". Please also mark this with https://github.com/ROCm/MIOpen/labels/testing.

2024-01-10 13:57 UTC, atamazov commented on test/gtest/conv3d_test.cpp
> +                  "test_conv_hip_igemm_xdlops test";
[resolved]

2024-01-10 13:57 UTC, atamazov commented on test/gtest/conv3d_test.cpp
> +    if(devName == "gfx94" || devName == "gfx103" || devName == "gfx110")
[resolved] but I recommend removing the check of the device.

2024-01-10 13:57 UTC, atamazov commented on test/gtest/conv3d_test.cpp
> +#if MIOPEN_BACKEND_OPENCL
[resolved]

2024-01-10 13:57 UTC, atamazov commented on test/gtest/conv3d_test.cpp
> +    if(IsTestSupportedForDevice(handle) && miopen::IsEnabled(ENV(MIOPEN_TEST_COMPOSABLEKERNEL)) &&
[resolved]

2024-01-10 13:58 UTC, atamazov commented on test/gtest/conv3d_test.cpp
> +INSTANTIATE_TEST_SUITE_P(Conv3dTest, ConfigWithFloat, testing::ValuesIn(GetTestCases("--float")));
[resolved]

2024-01-17 22:29 UTC, junliume commented
@xinlipn @atamazov re-request review

2024-01-18 09:25 UTC, xinlipn commented
> @xinlipn @atamazov re-request review

@junliume , I have updated the code per @atamazov 's comments, may need him revisit the changes.

2024-01-22 15:45 UTC, xinlipn commented
@atamazov , could you help review my latest changes when you have a chance?

2024-01-23 23:20 UTC, atamazov requested changes

2024-01-23 23:20 UTC, atamazov commented on test/gtest/conv3d_test.cpp
> +    return ((!s_envVar.empty() && std::strcmp(s_envVar.c_str(), float_arg) == 0 &&
[Quality] I suspect this line is equivalent to
```C++
    return ((s_envVar == float_arg &&
```

2024-01-23 23:20 UTC, atamazov commented on test/gtest/conv3d_test.cpp
> +            (s_envVar.empty() && miopen::IsUnset(ENV(MIOPEN_TEST_ALL))));
[Recommendation] I think this design looks cleaner:
```suggestion
    if(miopen::IsUnset(ENV(MIOPEN_TEST_ALL)))
        return true; // standalone run
    return miopen::IsEnabled(ENV(MIOPEN_TEST_ALL)) //
        && miopen::GetStringEnv(ENV(MIOPEN_TEST_FLOAT_ARG)) == float_arg;
```
line 42 is not needed anymore.

2024-01-23 23:21 UTC, atamazov commented on test/gtest/conv3d_test.cpp
> +    return (!s_envVar.empty() && std::strcmp(s_envVar.c_str(), float_arg) == 0);
[resolved] but please see recent updates at https://github.com/ROCm/MIOpen/issues/1843#issue-1420976061

2024-01-23 23:23 UTC, atamazov commented
@xinlipn 

> @atamazov , could you help review my latest changes when you have a chance?

Sure. I think this can be merged in, but I recommend making changes suggested at https://github.com/ROCm/MIOpen/pull/2554#discussion_r1464106309 first.

2024-01-23 23:24 UTC, atamazov commented on test/gtest/conv3d_test.cpp
> +            (s_envVar.empty() && miopen::IsUnset(ENV(MIOPEN_TEST_ALL))));
@xinlipn Please see updated https://github.com/ROCm/MIOpen/issues/1843#issue-1420976061 for more info.

2024-02-09 21:06 UTC, junliume approved these changes

2024-02-09 21:07 UTC, merged