[DRAFT] cpu multi head attention
ROCmSoftwarePlatform/MIOpen pull request #2563
Opened 2023-11-30 12:22 UTC by bghimireamd

First attempt for cpu implementation of multi-head attention. Only inference is done. Currently working on backward.

2023-12-25 16:45 UTC, CAHEK7 requested changes

2023-12-25 16:45 UTC, CAHEK7 commented on test/gtest/cpu_multi_head_attention.hpp
> +}
Seems it just returns `std::sqrt`, is there any purpose for this?

2023-12-25 16:45 UTC, CAHEK7 commented on test/gtest/cpu_multi_head_attention.hpp
> +        T sum(0);
I would recommend to use `double` as accumulator.

2023-12-25 16:45 UTC, CAHEK7 commented on test/gtest/cpu_multi_head_attention.hpp
> +        std::lock_guard<std::mutex> guard(coutMutex);
If `ret_value.par_for_each` access to unique elements of `ret_value` then mutex is not needed, especially before the loop.
Currently is serializes almost all the computation.

2023-12-25 16:45 UTC, CAHEK7 commented on test/gtest/cpu_multi_head_attention.hpp
> +        std::lock_guard<std::mutex> guard(coutMutex);
See `void ParMul` comment.

2023-12-25 16:45 UTC, CAHEK7 commented on test/gtest/cpu_multi_head_attention.hpp
> +            T max_score_in_row;
The value can be assigned to `m_tensor` directly, without this variable.

2023-12-25 16:45 UTC, CAHEK7 commented on test/gtest/cpu_multi_head_attention.hpp
> +            T sum(0);
The value can be assigned to `zinv_tensor` directly, without this variable.

2023-12-25 16:45 UTC, CAHEK7 commented on test/gtest/cpu_multi_head_attention.hpp
> +        double drop_out_scale = 1.0 / (1.0 - d_k);
scale depends on `drop_out_rate`.

2024-01-25 12:06 UTC, CAHEK7 requested changes
Dropout uses random number generator and if we want to get comparable results, we must use the same generators for GPU and CPU.
Take a look at the dropout tests - they have implemented cpu version of the same generator.

2024-01-25 12:06 UTC, CAHEK7 commented on test/gtest/cpu_multi_head_attention.hpp
> +    rand_dis.generate(GenData<T>{});
We won't get similar mask tensor on gpu. It would be hardly possible to compare the results.

2024-01-29 05:41 UTC, bghimireamd commented
> Dropout uses random number generator and if we want to get comparable results, we must use the same generators for GPU and CPU. Take a look at the dropout tests - they have implemented cpu version of the same generator.

Agreed! I will change the code accordingly.

2024-03-26 03:11 UTC, CAHEK7 commented
I've done some significant code refactoring:

- Separated fp32 and fp8 tests and check f8 version (previously only fp32 version checked).
- Made fp8 test self-sufficient (previously it can't be run without fp32)
- Unbound tests with hardcoded reference data from random number generator
- Used `string_view` instead of strings
- Used proper gtest macros for result verification
- Used float instead of double for some intermediate data (which is supposed to be float)

Also I merged https://github.com/ROCm/MIOpen/pull/2819

2024-04-03 16:13 UTC, CAHEK7 approved these changes
mha_helper may use some more generic variants of operations (like `Dot_4D_4D` and all the transposed variants are identical except the index order), but overall it works.
I did some testing against gpu implementation and it works fine.

It's also a base PR for my numerical fwd-mha testing, so it would be nice to merge it before.

2024-04-03 16:19 UTC, CAHEK7 commented
Sidenote - this code is a subject to change during integration with GPU implementation.
If somebody has any architecture suggestions - they will be taken into account in the following PRs.

Also this PR is a base for bwd-cpu implementation.

2024-04-03 17:00 UTC, binarman commented on test/gtest/mha_helper.hpp
> +// }
nitpick: looks redundant or comment/TODO is missing

2024-04-03 17:01 UTC, binarman commented on test/gtest/cpu_multi_head_attention.hpp
> +        // SetupMask(mask);
redundant?

2024-04-03 17:01 UTC, binarman commented on test/gtest/cpu_multi_head_attention.hpp
> +        // cpu_mha_test_case.num_heads, d_k, cpu_mha_test_case.problem_dimension
and this

2024-04-04 14:50 UTC, Vsevolod1983 approved these changes

2024-04-04 17:49 UTC, CAHEK7 commented
@junliume may I ask to merge it.
It prevents https://github.com/ROCm/MIOpen/pull/2875 to be reviewed, since it contains the changes from this PR.

2024-04-08 05:39 UTC, junliume approved these changes

2024-04-08 05:39 UTC, merged

2024-04-08 14:58 UTC, amberhassaan reviewed
some comments.

2024-04-08 14:58 UTC, amberhassaan commented on test/tensor_util.hpp
> +void output_tensor_to_screen(const tensor<T>& tensor_val,
minor: simpler name could be `print_tensor`.

2024-04-08 14:58 UTC, amberhassaan commented on test/gtest/mha_helper.hpp
> +T FindMax4D(const tensor<T>& max_of_tensor)
A lot of these helper functions on tensors can benefit from variadic lambda parameters like this: 
```
max_of_tensor.for_each([&] (auto... indices) {
   maxVal = std::max(maxVal, max_of_tensor(indices...));
});
```

2024-04-08 15:21 UTC, atamazov commented
@junliume Thanks for renaming this to "[MHA] CPU multi head attention" during merging.

@bghimireamd I highly recommend naming PRs as clearly as possible. For this specific PR I would consider prefixing PR name with `[MHA][tests]` 🤝