removing gfx908 and vega builds node from smoke tests
ROCmSoftwarePlatform/MIOpen pull request #2876
Opened 2024-04-04 21:57 UTC by reidkwja

removes gfx908 and vega from getting picked up for smoke tests runs.

2024-04-05 21:22 UTC, atamazov commented
@reidkwja this is not an enhancement, this is workaround.

2024-04-05 21:35 UTC, atamazov requested changes

2024-04-05 21:35 UTC, atamazov commented on Jenkinsfile
>                  stage('Fp32 Hip AnyGPU') {
Here and everywhere: if only gfx90a is left, please use "gfx90a" in the stage name instead of "AnyGPU"

2024-04-05 21:35 UTC, atamazov commented on Jenkinsfile
Line 470:
```groovy
        booleanParam(
            name: "TARGET_GFX908",
            defaultValue: env.BRANCH_NAME == env.NIGHTLY_BRANCH ? true : false,
description: "")
```
This totally excludes MI100 nodes from testing except nightly. Who will triage and fix the bugs found during nightly?

If we are excluding MI100s from smoke tests now, then I highly recommend enabling them in Full tests, **_in develop at least._**

2024-04-05 21:35 UTC, atamazov commented on Jenkinsfile
/cc @junliume

2024-04-09 19:56 UTC, cderb commented on Jenkinsfile
I'll echo this comment.
Limiting the smoke tests to gfx90a is acceptable in my opinion, because the test stage is then more deterministic in the CI.
However, there is still a need to identify architecture specific bugs which may arise. Perhaps the full test is the stage to address this in. gfx908 and vega tests will still be necessary in the regular CI to provide immediate feedback for developers.

2024-04-17 00:07 UTC, junliume approved these changes

2024-04-17 00:07 UTC, merged