[DRAFT] Convert MIOpenDriver tests into shell script
ROCmSoftwarePlatform/MIOpen pull request #2878
Opened 2024-04-08 07:52 UTC by xinlipn

The shell script has dependency on the binary, MIOpenDriver

2024-04-11 07:42 UTC, xinlipn commented
1. Create a shell script for MIOpenDriver tests, which will be packed along with single gTest binary, miopen_gtest

2. Shell script depends on the binary, /MIOpen/build/bin/MIOpenDriver, ie LN128

3. These two env vars, MIOPEN_TEST_WITH_MIOPENDRIVER and MIOPEN_TEST_ALL, are used to control miopen tests 

4. Test logs attached. Tested on 10.7.47.119 (MI200), with rocm/miopen:ci_fd8d66 
[miopendriver_test.log](https://github.com/ROCm/MIOpen/files/14942920/miopendriver_test.log)

2024-04-11 18:00 UTC, junliume commented
Adding @atamazov , this looks like *adding* a functionality which will eventually replace/convert an existing one, I would suggest moving forward if no objections.

2024-04-11 18:36 UTC, atamazov requested changes
Unfortunately does not comply #1843 and other things. I recommend implementing these tests just like we do other tests (but set normal environment and then exec MIOpenDriver with necessary command-line arguments instead of instantiating and using test classes from the ./test directory).

2024-04-15 19:33 UTC, xinlipn commented
> Unfortunately does not comply #1843 (2) and other things. I recommend implementing these tests just like we do other tests (but set normal environment and then exec MIOpenDriver with necessary command-line arguments instead of instantiating and using test classes from the ./test directory).

Hi @atamazov, thanks for the input. Unlike converting other cTests to gTest by implementing test classes and pack them into a single binary as this PR below, what the script does is to call MIOpenDriver binary with arguments like what you commented. 

https://github.com/ROCm/MIOpen/pull/2806

The shell script has dependency on MIOpenDriver binary and also needs to have environment variables set. The reason is 

1) Previous MIOpenDriver test didn't use the test drivers, e.g. conv2d_driver, a shell script seems to be a feasible solution at this stage after discussion. This script along with the single gTest binary miopen_gtest will be delivered and pack to other internal teams.

2) Although this shells script isn't part of cTest but it meant to have the same coverage as cTest. From this perspective, it's not meant to be standalone, so I kept  the same logic and environment variable i.e. MIOPEN_TEST_ALL

Thanks

2024-04-16 13:31 UTC, atamazov commented
@xinlipn 
> Unlike converting other cTests to gTest by implementing test classes and pack them into a single binary as this PR below, what the script does is to call MIOpenDriver binary with arguments like what you commented.

What I am proposing is implementing the minimum test classes and calling MIOpenDriver from within the test, just like the script does. The advantage is that the test can work standalone -- it can check the GPU type, XNACK feature etc. But of course is will require the driver to exist, i.e. there is a dependence.

2024-04-16 14:58 UTC, xinlipn commented
> @xinlipn
> 
> > Unlike converting other cTests to gTest by implementing test classes and pack them into a single binary as this PR below, what the script does is to call MIOpenDriver binary with arguments like what you commented.
> 
> What I am proposing is implementing the minimum test classes and calling MIOpenDriver from within the test, just like the script does. The advantage is that the test can work standalone -- it can check the GPU type, XNACK feature etc. But of course is will require the driver to exist, i.e. there is a dependence.

This script can check GPU type at runtime and is kind of a quick solution to start testing. We can do it with a class as proposed in another implementation. FYI, this script does run by itself (given the presence of MIOpenDriver) if this makes sense. Thanks

2024-04-24 05:47 UTC, xinlipn commented
> @xinlipn
> 
> > Unlike converting other cTests to gTest by implementing test classes and pack them into a single binary as this PR below, what the script does is to call MIOpenDriver binary with arguments like what you commented.
> 
> What I am proposing is implementing the minimum test classes and calling MIOpenDriver from within the test, just like the script does. The advantage is that the test can work standalone -- it can check the GPU type, XNACK feature etc. But of course is will require the driver to exist, i.e. there is a dependence.

 Creating a gTest to run MIOpenDriver is probably a better way than shell script. Will close this PR and create a new one for new implementation.

2024-06-10 10:47 UTC, CAHEK7 commented
I guess it can be closed, since #2984 has been merged.

2025-07-14 05:59 UTC, BradPepersAMD commented
MIOpen is moving to the monorepo and old PR's need to be closed for this to happen.  If needed, this PR can be re-opened in the new repo.

2025-07-14 05:59 UTC, closed without merging