Consider workspace constraints when loading convolution solutions from database
ROCmSoftwarePlatform/MIOpen pull request #2888
Opened 2024-04-11 23:46 UTC by tbennun

Trying to find a convolution algorithm with a workspace size constraint works when the database needs to be regenerated. This PR enables using that same constraint when the database already exists.

This is important for memory-limited environments with large neural networks.

2024-04-13 19:15 UTC, atamazov commented
@tbennun Please explain why you need this feature. Please include a use case scenario (at high level; I do not need a complete C++ program or alike). Thanks.

2024-04-13 19:20 UTC, atamazov requested changes
This PR includes a quiet change of the public API. Such a change must be made explicit at least.

2024-04-13 19:31 UTC, tbennun commented
@atamazov Thank you for reviewing.

> @tbennun Please explain why you need this feature. Please include a use case scenario (at high level; I do not need a complete C++ program or alike). Thanks.

A deep learning library trains a neural network. Since the network has high demands on GPU memory (e.g., activation tensor size), the workspace allocation is limited to X GiB. If the database does not exist, calling `miopenFindConvolutionForwardAlgorithm` with a given workspace size will (correctly) choose algorithms that conform to the workspace size (in [EvaluateInvokers](https://github.com/ROCm/MIOpen/blob/develop/src/conv/solver_finders.cpp#L241).
However, if a database already exists, it will only choose the fastest one, failing or segfaulting later due to insufficient workspace.

> This PR includes a quiet change of the public API. Such a change must be made explicit at least.

I was not aware that this PR changes public API, as the behavior already occurs the first time `miopenFindConvolution*` is called.

2024-04-13 20:01 UTC, atamazov commented
@tbennun 
> Trying to find a convolution algorithm with a workspace size constraint works when the database needs to be regenerated.

It may randomly work in some specific cases, but IIRC the Find API still requires workspace to be not smaller than the respective GetWorkspaceSize API call informs. We thought about allowing Find to return the "best possbile" results if the workspace size is insufficient, but for now the decision is to keep API "strict". The reason is that this may prevent the most performant kernels to be found and used, which is against the purpose of the library -- it exists to deliver performance (perhaps this reasoning is somewhat superficial and we are open for discussion).

2024-04-13 20:03 UTC, atamazov commented
@tbennun Oops, I see EvaluateInvokers, let me check why this is so...

2024-04-13 20:15 UTC, atamazov commented
@tbennun Yes we have this relaxation, it was implemented in https://github.com/AMDComputeLibraries/MLOpen/pull/2499 (private MIOpen repo). I need to discuss this with the team.

/cc @DrizztDoUrden

2024-04-13 20:26 UTC, atamazov commented
@tbennun Right now you can use 
```bash
export MIOPEN_FIND_MODE=Normal
```
That would enforce the library to ignore existing find-db records during Find calls. The new records will be written into the user-find-db, and these new records override the old ones.

After the network is run once, you can unset MIOPEN_FIND_MODE. This is recommended because the Normal Find mode has substantial host-side overhead which may slowdown your network.

[Notice] The by-product of this approach is that you'll likely get the best possible performance for your specific system, because in Normal Find Mode the library builds and benchmarks kernels right on your HW.

2024-04-13 20:29 UTC, atamazov commented
@tbennun 
> I was not aware that this PR changes public API, as the behavior already occurs the first time miopenFindConvolution* is called.

My review was incorrect and now dismissed.

2024-04-13 20:34 UTC, atamazov commented
@tbennun UPDATE: Currently the behavior of Find when WS is too small is unspecified. In some cases the library works, is some other it doesn't. This is not good. Your PR makes (or at least intended to make) the behavior well-specified. _It is in this sense this PR changes the API._

From the practical POV this means that we need to update the documentation in miopen.h

2024-04-15 14:24 UTC, atamazov commented
@tbennun After some internal discussion the decision is made to officially support the cases when WS is too small. I'll provide the proper fix soon. The PR will include:
- Some changes similar to this PR
- Appropriate warnings
- Changes in documentation in miopen.h.

/cc @DrizztDoUrden @JehandadKhan @junliume

2024-04-15 14:26 UTC, tbennun commented
Thank you, @atamazov!

2024-04-15 22:07 UTC, atamazov commented
@tbennun Let me open another PR first. I will ask for closing this one explicitly. Thanks.

2024-04-25 15:23 UTC, JehandadKhan commented
@atamazov  Any objections to merging this PR? Especially, are there any regression risks for existing functionality ?

2024-04-25 15:31 UTC, atamazov commented
@JehandadKhan No objections. I will reimplement it soon to make it more "right" etc

2024-04-25 15:33 UTC, atamazov commented
Risks are possible, but low.

2024-04-25 18:02 UTC, JehandadKhan approved these changes

2024-04-25 18:03 UTC, merged