Conv reference kernel alpha beta enable
ROCmSoftwarePlatform/MIOpen pull request #2912
Opened 2024-04-22 05:40 UTC by bghimireamd

This PR enables alpha and beta in naïve reference GPU kernel. 
`out = val*alpha + out*beta`

2024-04-24 14:45 UTC, amberhassaan requested changes, later dismissed
I want to get rid of passing around `alpha/beta` as `const void*` where it's not necessary. The only place where it's necessary is where we interface with public API. Our testing code can specify the types better and for internal code, we use wrapper classes.

2024-04-24 14:45 UTC, amberhassaan commented on src/include/miopen/conv/data_invoke_params.hpp
> +    ConstData_t alpha;
`Data_t` and `ConstData_t` in our codebase refer to buffer types. We shouldn't use that for scalars. I made a comment in #2817 where I want wrapper classes for `Scalar` parameters that contain data type info as well.

2024-04-24 14:45 UTC, amberhassaan commented on src/solver/conv_direct_naive_conv_bwd.cpp
> +                float alpha_val = 1.0;
We cannot assume `float` as a data type for `alpha/beta`. See: https://docs.nvidia.com/deeplearning/cudnn/latest/developer/misc.html#scaling-parameters

2024-04-24 14:45 UTC, amberhassaan commented on src/kernels/gpu_reference_kernel/naive_conv.cpp
> +                                           const float alpha,
The type of `alpha/beta` for naive kernel should be `accumulator type` as that's `double` for floating point inputs and `int32_t` for integer inputs sucha as `int8_t`.

2024-04-24 14:45 UTC, amberhassaan commented on test/gtest/nonpack_conv3d_fwd.hpp
> +                1.0, // alpha
let's not add `alpha/beta` here. There's a better way using `Combine`. See: https://github.com/ROCm/MIOpen/blob/develop/test/gtest/fused_conv_bias_res_add_activ.cpp#L229-L235

2024-05-01 14:34 UTC, amberhassaan commented on src/kernels/gpu_reference_kernel/naive_conv.cpp
> +            acc_data_t val_alpha_beta =
This is good but I don't think we are quite complying with the spec. I was wrong to suggest that we can use `acc_data_t` for `alpha/beta`. In reality, it should be `float` or `double`. I think the more correct solution would be to deduce the type of `alpha/beta` from `src_data_t`. This is where we use your type-deduction logic :).

2024-05-07 23:44 UTC, junliume commented
@bghimireamd @amberhassaan @dpsm @powderluv @rasmith 
This is a late feature, please help expedite your review, we plan to merge soon. Thanks!

2024-05-07 23:54 UTC, amberhassaan commented
> @bghimireamd @amberhassaan @dpsm @powderluv @rasmith This is a late feature, please help expedite your review, we plan to merge soon. Thanks!

@junliume : @bghimireamd will put out a combined PR soon that contains tests etc. Let's all review that one.

2024-05-08 14:48 UTC, bghimireamd commented
@amberhassaan combined PR is ready for review https://github.com/ROCm/MIOpen/pull/2863

2024-05-08 19:01 UTC, junliume commented
**Notice to the reviewers:** replaced with consolidated https://github.com/ROCm/MIOpen/pull/2863

2024-05-09 14:30 UTC, bghimireamd commented
should review https://github.com/ROCm/MIOpen/pull/2863 instead.

2024-05-09 14:30 UTC, closed without merging