Change std::string to fs::path for handling files
ROCmSoftwarePlatform/MIOpen pull request #3018
Opened 2024-06-03 20:39 UTC by apwojcik

Change handling file paths from `std::string` to `fs::path` for better cross-OS portability.

2024-06-04 18:04 UTC, DrizztDoUrden requested changes, later dismissed

2024-06-04 18:04 UTC, DrizztDoUrden commented on src/include/miopen/execution_context.hpp
> +        return udb / filename;
Prefix got lost here
Also why was ostringstream removed? It should have less allocations than concatenation chain.

2024-06-04 19:34 UTC, apwojcik commented on src/include/miopen/execution_context.hpp
> +        return udb / filename;
> Prefix got lost here

I submitted the PR too early. I am working to fix that right now (and compilation).

> Also why was ostringstream removed? It should have less allocations than concatenation chain.

It is the opposite. Please read this StackOverflow for more details: https://stackoverflow.com/questions/14741144/stdstringstream-vs-stdstring-for-concatenating-many-strings

2024-06-04 19:36 UTC, apwojcik commented on src/include/miopen/execution_context.hpp
> +        return udb / filename;
The benchmark: https://quick-bench.com/q/iR8hY3MmHXCSXe5vvY28C-6mQfY

2024-06-10 05:53 UTC, junliume commented
@DrizztDoUrden @averinevg @atamazov last call of review before merging this PR. Thanks!

2024-06-10 13:17 UTC, apwojcik commented
@junliume CI is failing because there is `No space left on device`.

2024-06-10 14:28 UTC, CAHEK7 requested changes
It looks like the first comment is important, and, if CI will be restarted in any case, the second comment can be fixed too.

2024-06-10 14:28 UTC, CAHEK7 commented on cmake/embed.cmake
> +    static const std::unordered_map<fs::path, std::string_view> result = {${INIT_KERNELS}};
Doesn't it break compatibility with old distros?
Like that one https://github.com/ROCm/MIOpen/pull/3035 ?
Also, I'd suggest to use that solution: https://github.com/ROCm/MIOpen/pull/3035#issuecomment-2156807075

2024-06-10 14:28 UTC, CAHEK7 commented on src/include/miopen/simple_hash.hpp
> +        return (std::hash<std::string>()(p.first.string()) ^ std::hash<std::string>()(p.second));
```suggestion
        return (fs::hash_value(p.first) ^ std::hash<std::string>()(p.second));
```

2024-06-10 22:27 UTC, CAHEK7 approved these changes

2024-06-11 06:01 UTC, junliume approved these changes

2024-06-11 06:02 UTC, junliume commented on cmake/embed.cmake
> -const std::unordered_map<std::string, std::pair<const char*,const char*>>& ${EMBED_NAME}();
Thanks! This will save us from some potential issues on legacy distributions :)

2024-06-11 06:03 UTC, merged

2024-06-11 21:42 UTC, atamazov commented on src/include/miopen/execution_context.hpp
> +        return udb / filename;
@apwojcik Thanks, this is interesting.

> The benchmark: https://quick-bench.com/q/iR8hY3MmHXCSXe5vvY28C-6mQfY

I've tried it in different configurations:
- c++17 or c++20
- Optimization: None or O3
- libstdc++(GNU) or libc++(LLVM)
- Modifications of the test:
  - Original code
  - 10 times longer strings
  - many writes to stream/string
  - ostringstream or stringstream

The benchmark shows that std::string is 14...220 times better than std::stringstream, depending on the configuration.

It's interesting that compiler optimizations negatively affect performance: the original `BM_StringConcat` reports ~640 "cpu_time" (whatever that means), but after change to O3 it shows ~910. For `BM_StringStream` things are even worse: "gpu_time" regresses from 16k to 177k.

@DrizztDoUrden Shall we open a ticket dedicated to replacing stringstreams with strings, what do you think?

2024-06-11 21:51 UTC, atamazov commented on src/anyramdb.cpp
> +    return *instances.emplace(path, std::make_unique<AnyRamDb>(path)).first->second;
@msaudulhassan just FYI.

2024-06-11 21:55 UTC, atamazov commented
@apwojcik Looks good.

2024-06-11 21:56 UTC, atamazov commented
@junliume @JehandadKhan Is is possible to launch a performance testing round on CI with d208a9a3351eb9048a4a2b3f9d34fefbae0f6fda (develop right after this commit)?