Changed all perf-db creations to be lazy
ROCmSoftwarePlatform/MIOpen pull request #3212
Opened 2024-08-22 14:38 UTC by DrizztDoUrden

This makes find or similar invokations to not construct any db instance when no tunable solver is applicable or in similar cases. Basically it removes redundant prefetches. After #3078 this can also delay any potential waiting for the db being prefetched, which can reduce expected delays even further.

2024-10-03 11:53 UTC, averinevg requested changes

2024-10-03 11:53 UTC, averinevg commented on src/include/miopen/mlo_internal.hpp
> +
[R] I think we shouldn't add new things into this file. This file has confusing name, also it probably has a license problem.

2024-10-03 11:53 UTC, averinevg commented on src/include/miopen/any_solver.hpp
> +    ConvSolution FindSolution(const ExecutionContext& ctx,
Let's add `#define FIN_ANY_SOLVER_FIND_SOLUTION_COMPAT 1` and wrap old `FindSolution()` with `#if/#endif`.
This code should be removed after the `Fin` is fixed.

2025-01-20 11:22 UTC, shurale-nkn approved these changes
LGTM

2025-01-20 11:58 UTC, averinevg approved these changes
LGTM

2025-01-20 13:25 UTC, merged