[testing] Speed up test_activation, convert to GTest
ROCmSoftwarePlatform/MIOpen pull request #3253
Opened 2024-09-13 19:17 UTC by averinevg

TBD

2024-09-17 18:07 UTC, CAHEK7 requested changes
That's a great improvement, but it seems logging and code quality can be improved a bit.
1) make static cast in `namespace activ_func {` more uniform and logic, Right now it feels a bit chaotic.
2) it feels like th4ere is too many wrappers over a single function, could you clarify why do we need them, or remove. (also some code generalization may reduce copypaste and number of wrappers)
3) warnings (I doubt that they are necessary at all) and debug print pollutes the logs on CI
4) there are some unnecessary synchronizations

The last concert - it seems that it removes the tests for non-packed tensors and significantly changes data ranges and generation algorithms. That may affect the test coverage.

2024-09-17 18:07 UTC, CAHEK7 commented on test/network_data.hpp
> +
We shall think about making that parameter runtime, actually switch between only small tensors for `smoke` tests and only big tensors for `full` tests.

2024-09-17 18:07 UTC, CAHEK7 commented on test/gtest/activ_common.hpp
> +        return (x > static_cast<Tparam>(0)) ? x : static_cast<T>(0);
```suggestion
        return (x > static_cast<T>(0)) ? x : static_cast<T>(0);
```
At least `x` is a `T`, not `Tparam` and casting `x` to `Tparam` does not make much sense for the comparison to 0.

2024-09-17 18:07 UTC, CAHEK7 commented on test/gtest/activ_common.hpp
> +        return (x > static_cast<Tparam>(0)) ? dy : static_cast<T>(0);
The same as for the Forward case.

2024-09-17 18:07 UTC, CAHEK7 commented on test/gtest/activ_common.hpp
> +        return dy * static_cast<Tparam>((x > static_cast<Tparam>(0)) ? 1 : -1);
The same as `ActivationRELU` case

2024-09-17 18:07 UTC, CAHEK7 commented on test/gtest/activ_common.hpp
> +        return std::min(alpha, std::max(static_cast<Tparam>(0), static_cast<Tparam>(x)));
```suggestion
        return std::clamp(static_cast<Tparam>(x), static_cast<Tparam>(0), alpha);
```

2024-09-17 18:07 UTC, CAHEK7 commented on test/gtest/activ_common.hpp
> +        return (x_native > 0 && x_native <= alpha) ? dy : static_cast<T>(0);
```suggestion
        return (x > 0 &&  static_cast<Tparam>(x) <= alpha) ? dy : static_cast<T>(0);
```

2024-09-17 18:07 UTC, CAHEK7 commented on test/gtest/activ_common.hpp
> +        return dy * ((x > static_cast<Tparam>(0)) ? 1 : alpha);
Could we be more consistent?
Either  `(x_native > static_cast<Tparam>(0))` or `x > 0`?

2024-09-17 18:07 UTC, CAHEK7 commented on test/gtest/activ_common.hpp
> +    const std::size_t num_jobs = (num_items + max_num_items_per_job - 1) / max_num_items_per_job;
https://github.com/ROCm/MIOpen/issues/2748

2024-09-17 18:07 UTC, CAHEK7 commented on test/gtest/activ_common.hpp
> +    const std::size_t max_num_jobs_per_thread  = (num_jobs + num_threads - 1) / num_threads;
https://github.com/ROCm/MIOpen/issues/2748
Can you make at least a function for this `Ceil` integer division?

2024-09-17 18:07 UTC, CAHEK7 commented on test/gtest/activ_common.hpp
> +    };
It's quite identical to `CpuActivationForwardPackedSingleThread`, I mean it can be generalized.

2024-09-17 18:07 UTC, CAHEK7 commented on test/gtest/activ_common.hpp
> +    throw std::runtime_error("CpuActivationForwardNonPacked is not implemented yet");
It doesn't seem that the initial algorithm had this limitation.
I'm not sure we can just skip non-packed tests.

Especially if we remove previous test completely.

2024-09-17 18:07 UTC, CAHEK7 commented on test/gtest/unit_ActivationDescriptor.cpp
> +                              100);
Do we really want to spam this into CI logs?
Can it be at least under `MIOPEN_LOG_LEVEL`?

2024-09-17 18:07 UTC, CAHEK7 commented on test/gtest/unit_ActivationDescriptor.cpp
> +        };
I suppose it should print formatted tensor instead of flattened.
But actually I don't think that it's necessary at all.
By the way, there is a https://github.com/ROCm/MIOpen/blob/61d9825a5eaec632a727e30d4ea881f28c38626f/test/tensor_util.hpp#L122
Can we use a single solution?

2024-09-17 18:07 UTC, CAHEK7 commented on test/gtest/unit_ActivationDescriptor.cpp
> +                                  DEBUG_PRINT_dX_TENSOR_GPU,
Do we really need that kind of flexibility? It's already bound to the algorithm, and it can be just a `bool forward` parameter.

2024-09-17 18:07 UTC, CAHEK7 commented on test/gtest/unit_ActivationDescriptor.cpp
> +    }
Either we support non-packed tensors, or we don't. What can we do with such kind of warning in CI?
Btw, it will print identical warnings for each non-packed tensors during initialization and in case of failed verification and does not print any information of which tensor is not packed.

2024-09-17 18:07 UTC, CAHEK7 commented on test/gtest/unit_ActivationDescriptor.cpp
> +    }
```suggestion
    static void RunCpu(const miopen::ActivationDescriptor& desc,
                       const tensor<T>& x,
                       tensor<T>& y,
                       tensor<T>& dx,
                       const tensor<T>& dy,
                       std::promise<void>& forward_ready)
    {
        miopen::tests::CpuActivationForward(
            desc.GetMode(), desc.GetAlpha(), desc.GetBeta(), desc.GetGamma(), x, y);
        forward_ready.set_value();
        miopen::tests::CpuActivationBackward(
            desc.GetMode(), desc.GetAlpha(), desc.GetBeta(), desc.GetGamma(), y, dy, x, dx);
    }
```
All those functions are already `Forward` and `Backward`. Why do we need extra wrappers for them?

2024-09-17 18:07 UTC, CAHEK7 commented on test/gtest/unit_ActivationDescriptor.cpp
> +        handle.Finish();
`handle.Read`/`handle.ReadTo` are synchronous. That explicit synchronization is not required, even for "just in case". Asynchronous version of this function will break whole library.

2024-09-17 18:07 UTC, CAHEK7 commented on test/gtest/unit_ActivationDescriptor.cpp
> +        handle.Finish();
`handle.Read`/`handle.ReadTo` are synchronous. That explicit synchronization is not required, even for "just in case". Asynchronous version of this function will break whole library.

2024-09-17 18:07 UTC, CAHEK7 commented on test/gtest/unit_ActivationDescriptor.cpp
> +    }
Why do we need such wrappers?

2024-09-17 18:07 UTC, CAHEK7 commented on test/gtest/unit_ActivationDescriptor.cpp
> +    }
I'm not insisting, but I'd prefer keeping the data ranges and generators the same as in the previous test.

2024-09-17 18:07 UTC, CAHEK7 commented on test/gtest/unit_ActivationDescriptor.cpp
> +    }
That function is only needed for `NonPackedTensorWarning`, but that warning appears multiple times in multiple places and there isn't much sense to have it here.

2024-09-17 18:07 UTC, CAHEK7 commented on test/gtest/unit_ActivationDescriptor.cpp
> +        verify_bwd_ready.wait();
```suggestion
```
`future.get()` waits for the result.

2024-09-17 18:07 UTC, CAHEK7 commented on test/gtest/unit_ActivationDescriptor.cpp
> +        dy_data_ready.wait();
If you pass it right into `RunCpu`/`RunGpu` you can postpone `dx`/`dy` wait till backward pass. (just an idea for already complex async code).

2024-09-20 15:17 UTC, CAHEK7 approved these changes

2024-09-23 05:17 UTC, junliume approved these changes

2024-09-23 05:17 UTC, merged