[GTests Refactoring] Removing MIOPEN_TEST_ALL and MIOPEN_TEST_FLOAT_ARG env variables. Part 1.
ROCmSoftwarePlatform/MIOpen pull request #3269
Opened 2024-09-24 12:36 UTC by Vsevolod1983

Part 1.

Base branch for this PR is GTests_Refactoring_Integration_Branch

2024-09-26 06:48 UTC, junliume commented
Is the target branch `[GTests_Refactoring_Integration_Branch](https://github.com/ROCm/MIOpen/tree/GTests_Refactoring_Integration_Branch)` ?

2024-09-26 07:11 UTC, Vsevolod1983 commented
> Is the target branch `[GTests_Refactoring_Integration_Branch](https://github.com/ROCm/MIOpen/tree/GTests_Refactoring_Integration_Branch)` ?

Yes it is. We decided to use separate branch for our GTests refactoring efforts

2024-09-26 09:48 UTC, Vsevolod1983 commented
I converted this PR into draft because this PR locks up on CI. I expect this is because of time out of any kind happens. env variables are removed in this PR and it probably overloads CI.

2024-09-26 18:07 UTC, averinevg requested changes

2024-09-26 18:07 UTC, averinevg commented on test/gtest/adam.cpp
>  #include <miopen/env.hpp>
```suggestion
```

2024-09-26 18:07 UTC, averinevg commented on test/gtest/adam.cpp
>  namespace env = miopen::env;
```suggestion
```

2024-09-26 18:07 UTC, averinevg commented on test/gtest/addlayernorm.cpp
>  #include <miopen/env.hpp>
```suggestion
```

2024-09-26 18:07 UTC, averinevg commented on test/gtest/cat.cpp
>  #include <miopen/env.hpp>
```suggestion
```

2024-09-26 18:07 UTC, averinevg commented on test/gtest/cat.cpp
>  namespace env = miopen::env;
```suggestion
```

2024-09-26 18:07 UTC, averinevg commented on test/gtest/conv_3d.cpp
>  #include <miopen/env.hpp>
```suggestion
```

2024-09-26 18:07 UTC, averinevg commented on test/gtest/conv_extra.cpp
>      const std::string default_float_arg = " --float";
```suggestion
```

2024-09-26 18:10 UTC, averinevg commented on test/gtest/conv_for_implicit_gemm.cpp
>  namespace env = miopen::env;
```suggestion
```

2024-09-26 18:10 UTC, averinevg commented on test/gtest/conv_group.cpp
>  #include <miopen/env.hpp>
```suggestion
```

2024-09-27 09:57 UTC, Vsevolod1983 commented on test/gtest/conv_extra.cpp
>      const std::string default_float_arg = " --float";
it is still used

2024-09-27 09:58 UTC, Vsevolod1983 commented on test/gtest/conv_for_implicit_gemm.cpp
>  namespace env = miopen::env;
it is still used

2024-09-27 13:59 UTC, averinevg approved these changes

2024-09-27 23:07 UTC, junliume commented
> > Is the target branch `[GTests_Refactoring_Integration_Branch](https://github.com/ROCm/MIOpen/tree/GTests_Refactoring_Integration_Branch)` ?
> 
> Yes it is. We decided to use separate branch for our GTests refactoring efforts until we collect all necessary changes. When we collect them we will merge this branch to the develop

Maybe update the target branch with merging the latest develop branch will help with the CI. Thanks!

2024-09-30 09:27 UTC, Vsevolod1983 commented
> > > Is the target branch `[GTests_Refactoring_Integration_Branch](https://github.com/ROCm/MIOpen/tree/GTests_Refactoring_Integration_Branch)` ?
> > 
> > 
> > Yes it is. We decided to use separate branch for our GTests refactoring efforts until we collect all necessary changes. When we collect them we will merge this branch to the develop
> 
> Maybe update the target branch with merging the latest develop branch will help with the CI. Thanks!

yeah, I update it periodically.

Btw, we would like to merge PRs into this temporary branch by ourselves. No objections from you ?

2024-10-01 23:50 UTC, junliume approved these changes

2024-10-02 09:58 UTC, merged