Adding base class for gtests
ROCmSoftwarePlatform/MIOpen pull request #3321
Opened 2024-10-17 20:22 UTC by reidkwja

Addressing issue #3135 with a random seed generator + environmental variables saving.

2024-10-18 02:49 UTC, bghimireamd commented on test/gtest/test_base.hpp
> +        const char* env_vars[] = {"CMAKE_CURRENT_BINARY_DIR",
could we just use `std::vector<std::string>` ?

2024-10-23 11:02 UTC, Vsevolod1983 commented
Btw, we are going to get rid of using environment variables https://github.com/ROCm/MIOpen/pull/3329

2024-11-09 16:29 UTC, CAHEK7 requested changes
Could you provide an example of how it can be used?
For example for `test/gtest/smoke_solver_ConvBinWinograd3x3U.cpp` or `test/gtest/hipblaslt_gemm.cpp`.

2024-11-13 14:50 UTC, CAHEK7 requested changes
It seems it does not build. Probably something went wrong with proper gtest base class.
Also it would be nice to have less destructive changes, ideally with minimal changes in the tests.

2024-11-13 14:50 UTC, CAHEK7 commented on test/gtest/smoke_solver_ConvBinWinograd3x3U.cpp
> +        miopen::env::setEnvironmentVariable(var, val);
I'm afraid it doesn't work for cached env variables.

2024-11-14 20:34 UTC, reidkwja commented on test/gtest/smoke_solver_ConvBinWinograd3x3U.cpp
> +        miopen::env::setEnvironmentVariable(var, val);
Yes, I have been trying different ways to integrate it without changing gtest_common.hpp - which will require changing large numbers of tests. 

I am still looking into ways to do so with seamless integration into gtests...

2024-12-04 17:56 UTC, BrianHarrisonAMD commented
There is a couple different build errors showing up in the CI that will need to be resolved.

2025-02-18 16:44 UTC, closed without merging