adding 3d bn gtest
ROCmSoftwarePlatform/MIOpen pull request #3385
Opened 2024-11-15 03:46 UTC by bghimireamd

2024-12-14 11:21 UTC, randyspauldingamd requested changes

2024-12-14 11:21 UTC, randyspauldingamd commented on test/gtest/bn.hpp
> +        std::string dimension = std::is_same<TestCase, BN2DTestCase>::value   ? "2D"
We should start enforcing invalid types with compile-time failures (not just here, but for all of our tests). You could use std::enable_if, but it's so ugly...here's a cleaner idea:
```
constexpr int dimension = std::is_same<TestCase, BN2DTestCase>::value ? 2
            : std::is_same<TestCase, BN3DTestCase>::value ? 3
            : -1;
static_assert(dimension > 0);
<snip>
std::ostringstream oss;
oss << tensor_name + "_" + api_name + dimension + "D_" + info.index;
return oss.str();
```

2024-12-14 11:21 UTC, randyspauldingamd commented on test/gtest/bn_bwd.cpp
> +// // // bfp16
extra //'s

2024-12-14 11:21 UTC, randyspauldingamd commented on test/gtest/bn_bwd.cpp
> +// // fp16
extra //'s

2024-12-14 11:21 UTC, randyspauldingamd commented on test/gtest/bn_bwd.cpp
> +// // bfp16
extra //'s

2024-12-14 11:21 UTC, randyspauldingamd commented on test/gtest/bn_bwd.cpp
> +// // fp32
extra //'s

2024-12-14 11:21 UTC, randyspauldingamd commented on test/gtest/bn_bwd.cpp
> +//
extra //'s

2024-12-14 11:21 UTC, randyspauldingamd commented on test/gtest/bn_fwd_train.cpp
> +struct GPU_BNCKFWDTrainLarge2D_FP16 : BNFwdTrainTest<half_float::half,
Just curious why some of these are multi-line and some are single-line. Have you ran clang-format?

2024-12-14 11:21 UTC, randyspauldingamd commented on test/gtest/bn_fwd_train.cpp
>  // // fp32 (float)
extra //'s

2024-12-14 11:21 UTC, randyspauldingamd commented on test/gtest/bn_fwd_train.cpp
>  // // // fp64
extra //'s

2024-12-14 11:21 UTC, randyspauldingamd commented on test/gtest/bn_fwd_train.cpp
>  // // bfp16
extra //'s

2024-12-14 11:21 UTC, randyspauldingamd commented on test/gtest/bn_fwd_train.cpp
>  // // fp32
extra //'s

2024-12-14 11:21 UTC, randyspauldingamd commented on test/gtest/bn_fwd_train.cpp
>  // // fp64
extra //'s

2024-12-14 11:21 UTC, randyspauldingamd commented on test/gtest/bn_infer.cpp
> +                         TestNameGenerator<BN2DTestCase>());
clang-format should clean these up as well

2025-01-14 19:04 UTC, bghimireamd commented on test/gtest/bn_fwd_train.cpp
> +struct GPU_BNCKFWDTrainLarge2D_FP16 : BNFwdTrainTest<half_float::half,
yes I did do calng-format. The CI also passes the clang-format stage.

2025-01-14 19:04 UTC, bghimireamd commented on test/gtest/bn_infer.cpp
> +                         TestNameGenerator<BN2DTestCase>());
yes I did do calng-format.

2025-01-14 20:11 UTC, BrianHarrisonAMD commented
Looks like a new CI error on this PR (possibly dupe name?)

GPU_BNFWDTrainLarge2D_FP64_DISABLED_BnV2LargeFWD_TrainCKfp64_Test

2025-01-23 15:26 UTC, BrianHarrisonAMD approved these changes
LGTM

2025-01-23 15:52 UTC, iq136boy approved these changes

2025-01-24 14:33 UTC, randyspauldingamd approved these changes

2025-02-04 14:42 UTC, merged