Codegen integration
ROCmSoftwarePlatform/MIOpen pull request #3415
Opened 2024-12-01 18:05 UTC by arai713

2024-12-01 21:04 UTC, CAHEK7 requested changes
It's just a quick review with some simple things and common pitfalls.
A haven't looked deep into the code yet.

2024-12-01 21:04 UTC, CAHEK7 commented on test/gtest/codegen_group_conv.hpp
> +        EXPECT_TRUE(miopen::range_distance(ref) == miopen::range_distance(computed));
```suggestion
        EXPECT_EQ(miopen::range_distance(ref), miopen::range_distance(computed));
```

2024-12-01 21:04 UTC, CAHEK7 commented on test/gtest/codegen_group_conv.hpp
> +        EXPECT_FALSE(miopen::find_idx(ref, miopen::not_finite) >= 0)
```suggestion
        EXPECT_LT(miopen::find_idx(ref, miopen::not_finite), 0)
```

2024-12-01 21:04 UTC, CAHEK7 commented on test/gtest/codegen_group_conv.hpp
> +            << "Error beyond tolerance Error:" << error << ",  Threshold: " << threshold;
```suggestion
        EXPECT_LE(error, threshold);
```
It will print something like:
```
Mismatch, error must be less than threshold :
error = 100500
threshold = 10
```

2024-12-01 21:04 UTC, CAHEK7 commented on src/solver/codegen_conv_hip_implicit_gemm_2d_grouped_fwd_xdlops.cpp
> +#if MIOPEN_BACKEND_HIP && MIOPEN_USE_COMPOSABLEKERNEL
```suggestion
#if MIOPEN_BACKEND_HIP && MIOPEN_USE_COMPOSABLEKERNEL
    auto x = CKArgs(problem);
```

2024-12-01 21:04 UTC, CAHEK7 commented on src/solver/codegen_conv_hip_implicit_gemm_2d_grouped_fwd_xdlops.cpp
> +
Usually you should add the kernels outside of this lambda and later just use added kernels.
Like here: https://github.com/ROCm/MIOpen/blob/6c4a0b3d0a462fdbdbeebb0ccadcf27f64bfa930/src/solver/softmax/softmax.cpp#L336

The list of added kernels passed through `const std::vector<Kernel>& kernels` into that lambda.

2024-12-01 21:04 UTC, CAHEK7 commented on src/solver.cpp
> +
It should be added at the end of the list, otherwise it will affect all the others solver ids.

2024-12-01 21:04 UTC, CAHEK7 commented on test/gtest/codegen_group_conv.hpp
> +        }
Basically this condition should never happen.
It's not quite good from the testing perspective - the whole test can be silently disabled and nobody knew about it.
And from the performance point of view - there is a lot of job done in SetUp, sometimes tens just to get if throw right here.

So it's better to remove `test_skipped` completely and provide only those configs which are 100% compatible with the solver.

2024-12-01 21:04 UTC, CAHEK7 commented on test/gtest/codegen_group_conv.hpp
> +    struct GPU_GroupConv##ndim##D_##dir##_##naming_type##_##cg                              \
`type` (`FP16`) must be the last in the test name. Please take a look at https://github.com/ROCm/MIOpen/wiki/GTest-development

2024-12-01 21:04 UTC, CAHEK7 commented on test/gtest/codegen_group_conv.hpp
> +    struct GPU_GroupConv##ndim##D_##dir##_##naming_type##_##cg                              \
Also you may use kind of `lightweight` version of a new type declaration:
```C++
using GPU_GroupConv##ndim##D_##dir##_##naming_type##_##cg = GroupConvTestFix<ndim, type, Direction::dir, cg>;
```
You don't need extra brackets)

2025-01-28 22:07 UTC, bghimireamd commented on src/solver/codegen_conv_hip_implicit_gemm_2d_grouped_fwd_xdlops.cpp
> +    return true;
you will need [ck_white_list ](https://github.com/ROCm/MIOpen/blob/develop/src/solver/conv_ck_igemm_fwd_bias_res_add_activ_fused.cpp#L424) since CK kernel runs only in some hardware.

2025-01-28 22:07 UTC, bghimireamd commented on test/gtest/codegen_group_conv2d_fwd.cpp
> +DEFINE_CG_GROUP_CONV2D_TEST(half, FP16, Forward);
only fp16 for now?

2025-01-28 22:09 UTC, bghimireamd commented on src/solver/codegen_conv_hip_implicit_gemm_2d_grouped_fwd_xdlops.cpp
> +    if(!(problem.IsLayoutNHWC() || problem.IsLayoutDefault()))
only nhwc is supported or both nhwc and nchw are supported? Just curious

2025-01-29 00:13 UTC, bghimireamd commented on CMakeLists.txt
> +	      find_package(ck_host)
just curious why is ck host needed?

2025-01-29 08:42 UTC, arai713 commented on CMakeLists.txt
> +	      find_package(ck_host)
ck_host is the package that has all the codegen methods in it

2025-01-29 18:42 UTC, arai713 commented on test/gtest/codegen_group_conv2d_fwd.cpp
> +DEFINE_CG_GROUP_CONV2D_TEST(half, FP16, Forward);
Yeah, we wanted to get just one example running, then extend with other data types or add new examples after everything looks okay.

2025-01-29 19:13 UTC, arai713 commented on src/solver/codegen_conv_hip_implicit_gemm_2d_grouped_fwd_xdlops.cpp
> +    if(!(problem.IsLayoutNHWC() || problem.IsLayoutDefault()))
This example only supports nhwc

2025-01-30 13:19 UTC, bghimireamd commented on src/solver/codegen_conv_hip_implicit_gemm_2d_grouped_fwd_xdlops.cpp
> +    if(!(problem.IsLayoutNHWC() || problem.IsLayoutDefault()))
so can we just do `if(!(problem.IsLayoutNHWC())`

2025-01-30 13:35 UTC, bghimireamd commented on src/solver/codegen_conv_hip_implicit_gemm_2d_grouped_fwd_xdlops.cpp
> +    return true;
Just realized your [solver currently only servers gfx908](https://github.com/ROCm/MIOpen/blob/f8e3ec06367e1da2e27953fe68bc417793a15c41/src/solver/codegen_conv_hip_implicit_gemm_2d_grouped_fwd_xdlops.cpp#L234) so I think you might need to do if(ctx.GetStream().GetDeviceName() == "gfx908") instead of is_ck_whitelist. CI will fail in other devices.

2025-01-30 21:18 UTC, arai713 commented on src/solver/codegen_conv_hip_implicit_gemm_2d_grouped_fwd_xdlops.cpp
> +    return true;
That is just the architecture selected, but this works on all the architectures listed in the whitelist, so I think ck_white_list is fine.

2025-01-31 23:10 UTC, BrianHarrisonAMD commented on requirements.txt
> +ROCm/composable_kernel@5574422afe4a357e1e5be60cc58ab42645553b93 -DCMAKE_BUILD_TYPE=Release
We will want to update this commit to match with CK next time it's promoted to staging I think.

2025-01-31 23:18 UTC, BrianHarrisonAMD commented on CMakeLists.txt
> +	      include(/usr/local/lib/cmake/composable_kernel_host/ck_host_targets.cmake)
Why is ck_host installed into a different location than the rest of the libs?

Also, do we need a separate include call here, or does find_package cover it since we have /usr/local/lib added to the prefix path?

2025-01-31 23:19 UTC, BrianHarrisonAMD commented on src/solver/codegen_conv_hip_implicit_gemm_2d_grouped_fwd_xdlops.cpp
> + * Copyright (c) 2023 Advanced Micro Devices, Inc.
Date

2025-01-31 23:19 UTC, BrianHarrisonAMD commented on src/include/miopen/conv/solvers.hpp
> +    }
What need to be done here?

2025-01-31 23:24 UTC, BrianHarrisonAMD commented on src/solver/codegen_conv_hip_implicit_gemm_2d_grouped_fwd_xdlops.cpp
> +    auto solution = x.prob.GetSolutions("gfx908", prologue, epilogue);
Won't this need to match the current device's arch?

I think right now it'll be limited to gfx908 instances.

2025-01-31 23:32 UTC, BrianHarrisonAMD commented on src/CMakeLists.txt
> +    /usr/local/lib/composable_kernel_host/include
This would need to be restricted to only when we are using CK.

Also, if ck_host was in the same location as other libs, we probably don't need this right?

2025-02-03 08:56 UTC, arai713 commented on src/include/miopen/conv/solvers.hpp
> +    }
This was an old comment, there's no need to change that function

2025-02-03 08:58 UTC, arai713 commented on src/solver/codegen_conv_hip_implicit_gemm_2d_grouped_fwd_xdlops.cpp
> +    auto solution = x.prob.GetSolutions("gfx908", prologue, epilogue);
This is supported on all devices from the ck whitelist in MIOpenThat function will check whether the given architecture is supported or not. I have been testing on gfx908 and gfx90a.

2025-02-03 17:25 UTC, arai713 commented on requirements.txt
> +ROCm/composable_kernel@5574422afe4a357e1e5be60cc58ab42645553b93 -DCMAKE_BUILD_TYPE=Release
The PR from CK has been merged into develop. Before it gets merged into staging, we'll need to make one last check to make sure that version of CK is still hipRTC compatible. Then I can change the commit hash here to match

2025-02-03 18:36 UTC, arai713 commented on CMakeLists.txt
> +	      include(/usr/local/lib/cmake/composable_kernel_host/ck_host_targets.cmake)
The ck_host lib is installed into a different location due to conflicting struct names with MIGraphX. We moved it from /opt/rocm/lib/ so they don't inadvertently access the ck_host lib if they didn't mean to.

2025-02-03 18:38 UTC, arai713 commented on src/CMakeLists.txt
> +    /usr/local/lib/composable_kernel_host/include
ck_host is in another location to prevent potential clashes due to similar structure names with MIGraphX

2025-07-14 06:21 UTC, BradPepersAMD commented
MIOpen is moving to the new monorepo setup and all older unmerged PR's are being closed.  Please re-open this as part of the new repo if these changes are still needed.

2025-07-14 06:21 UTC, closed without merging