InlineVector implementation
ROCmSoftwarePlatform/MIOpen pull request #3419
Opened 2024-12-03 08:07 UTC by novakovicdj

This is PR for initial implementation of `InlineVector` class from issue https://github.com/ROCm/MIOpen/issues/3408, also added some tests for this.

I will do additional performance testing with tensorOp solver structure to check if, and how much, host time is reduced using `InlineVector` instead of `std::vector` for lens/strides in `TensorDescriptor`

2024-12-03 11:25 UTC, CAHEK7 requested changes

2024-12-03 11:25 UTC, CAHEK7 commented on src/include/miopen/inline_vector.hpp
> +    const T* cend() const noexcept { return end(); }
MSVC is strict about iterators types, please replace `T*` with proper iterators.
You can add typedefs for pointer/reference/iterator and reuse them from `std::array`.
```c++
using storage_type = std::array<T, N>;
using iterator = storage_type::iterator;
...etc...
private:
storage_type _data;
```

2024-12-03 12:05 UTC, DrizztDoUrden requested changes

2024-12-03 12:05 UTC, DrizztDoUrden commented on src/include/miopen/inline_vector.hpp
> +    static_assert(std::is_scalar_v<T>, "Input data size is bigger than InlineVector's capacity");
[Suggestion] Strictly speaking, message does not reflect the check done.  I would suggest replacing the message with something like "Inline vector has no support for non-scalar types yet"

2024-12-03 12:05 UTC, DrizztDoUrden commented on src/include/miopen/inline_vector.hpp
> +    InlineVector(std::initializer_list<T> __data) : real_size(__data.size())
Names starting with double underscore or underscore followed by a capital letter are reserved by the implementation. E.g. 17.4.3.1.2 of 2003 standard. I think, most of our code has members with no underscore and arguments having a trailing one when needed.

2024-12-03 12:05 UTC, DrizztDoUrden commented on src/include/miopen/inline_vector.hpp
> +    const T& operator[](std::size_t n) const noexcept { return _data[n]; }
I'd add at least an assert with size validation in them
Also a suggestion: add subscripts that accept std::integral_constant<size_t, n> and something like ""_icst user-defined literal, that allows making a compile-time check and most of the code where we want to use this has constant indices anyway.

2024-12-03 12:05 UTC, DrizztDoUrden commented on src/include/miopen/inline_vector.hpp
> +    // Create element and add it to the back
`emplace_back` is not very useful if you limit data types to scalars

2024-12-03 12:05 UTC, DrizztDoUrden commented on src/include/miopen/inline_vector.hpp
> +        _data[real_size++] = e;
~~I would suggest using pre-increment in push_back/emplace_back. It wouldn't change much in terms of how it works except for data races, but the intent would be more clear.~~

2024-12-03 12:12 UTC, CAHEK7 commented on src/include/miopen/inline_vector.hpp
> +    const T& operator[](std::size_t n) const noexcept { return _data[n]; }
It mimics `std::` implementation, assert seems a good tradeoff.
As for the compile-time checks - they are possible for the capacity only.

2024-12-03 15:21 UTC, CAHEK7 commented on src/include/miopen/inline_vector.hpp
> +    template <typename _InputIterator, typename = std::_RequireInputIter<_InputIterator>>
`_RequireInputIter` is gcc/clang specific.
I guess that part can be omitted at all:
`template <typename InputIterator>`

2024-12-03 20:13 UTC, BrianHarrisonAMD commented
After develop fix, looks like there is this hip tidy error:

[2024-12-03T18:18:41.307Z] test/gtest/inline_vector_basic_ops.cpp:54:1: warning: syntax error [syntaxError]
[2024-12-03T18:18:41.307Z] TEST(CPU_InlineVectorFindIfAndDistance_NONE, Test)
[2024-12-03T18:18:41.307Z] ^

2024-12-04 11:46 UTC, DrizztDoUrden requested changes

2024-12-04 11:46 UTC, DrizztDoUrden commented on src/include/miopen/inline_vector.hpp
> +    template <typename _InputIterator>
_InputIterator is reserved by the standard (underscore + uppercase), you can just name it InputIterator or Iterator

2024-12-04 11:46 UTC, DrizztDoUrden commented on src/include/miopen/inline_vector.hpp
> +    template <typename... _Args>
_Args is a name reserved by the standard (underscore + uppercase)

2024-12-04 16:36 UTC, DrizztDoUrden requested changes

2024-12-04 16:36 UTC, DrizztDoUrden commented on src/include/miopen/inline_vector.hpp
> +        assert(n < N);
runtime assert should be with real_size

2024-12-04 16:36 UTC, DrizztDoUrden commented on src/include/miopen/inline_vector.hpp
> +        assert(n < N);
ditto

2024-12-05 07:44 UTC, novakovicdj commented on src/include/miopen/inline_vector.hpp
> +        assert(n < N);
I misunderstood you, will change that

2024-12-05 12:43 UTC, novakovicdj commented on src/include/miopen/inline_vector.hpp
> +    // Create element and add it to the back
I will remove it and leave comment for it to be implemented when adding support for other data types.

2024-12-10 19:58 UTC, CAHEK7 approved these changes

2025-01-07 18:18 UTC, CAHEK7 commented
@BrianHarrisonAMD @BradPepersAMD @junliume we need this PR for host-side performance improvements (especially around rnn/lstm networks, which is, as I remember, quite critical)
Also it may help to improve testing time a bit.

2025-01-08 23:21 UTC, DrizztDoUrden approved these changes

2025-01-14 20:20 UTC, BrianHarrisonAMD commented
Starting CI for this.

2025-01-16 15:05 UTC, merged