Produced solutions now contain original problem #3413
ROCmSoftwarePlatform/MIOpen pull request #3422
Opened 2024-12-03 15:22 UTC by BrianHarrisonAMD

2024-12-03 17:31 UTC, CAHEK7 requested changes
It breaks hiptidy on develop! See #3423

2024-12-03 17:42 UTC, BrianHarrisonAMD commented
Thanks @CAHEK7 !

2024-12-03 18:10 UTC, DrizztDoUrden approved these changes

2024-12-06 23:46 UTC, junliume approved these changes

2024-12-09 15:42 UTC, merged