[GTests] Rename non-unique test names (TEST, TEST_P, TEST_F, TYPED_TEST). Part 1.
ROCmSoftwarePlatform/MIOpen pull request #3446
Opened 2024-12-19 16:05 UTC by Vsevolod1983

When we use single test binary we should keep our test names unique (First parameter in TEST* macros).  Otherwise, we get a lot of failures, which are not related to tests themselves.  Non unique names create a conflict when get combined into one executable.

As an example of this extra failures from the ticket: SWDEV-488434
[  FAILED  ] Full/GPU_UnitTestConvSolverBwd_FP16.ConvWinoFuryRxSf2x3/0, where GetParam() = (4-byte object <FF-FF FF-FF>, 0, (x:{2,64,128,128,128} w:{32,64,3,3,3} pad:{1,1,1} stride:{1,1,1} dilation:{1,1,1} type_x:0 type_w:0 type_y:0))

We can see that "ConvWinoFuryRxSf2x3" is never used in "Full" test suites. So we have reports about the failures in tests which even don't exist!

There will be series of PRs with renaming for easier reviewing.

2024-12-23 16:10 UTC, scerzh approved these changes

2024-12-23 17:18 UTC, junliume approved these changes

2024-12-23 17:25 UTC, averinevg requested changes
Great job :smile:. Since not too many changes have been made yet, it’s worth making some adjustments to the naming. I think we should stick to the following naming scheme: **UnitTestConvSolver**+**_SolverName_**+**_Direction_**. The **UnitTestConvSolver** part is necessary so that we can use a filter to run only tests for convolution solvers. The second part is just the full name of the solver. If the solver's name contains the words 'Conv' or 'Solver', they can be excluded from the name. The third part is the direction. If the solver’s name ends with a direction, this part can be omitted. Full name for the `ConvOclDirectFwd` will end with two directions (part of the solver’s name and the actual direction) for some tests, since this solver also works with the backward direction. What is in this pull request is generally good. All of the above applies only to tests starting with `unit_conv_solver_*`.

2024-12-23 17:42 UTC, Vsevolod1983 commented
@averinevg 
Actually, I have the second branch with a lot of stuff already renamed.
Schema that I used: "UnitTestConv" + Name + "Solver" + Direction
Can we consider it for our naming ?

2024-12-23 18:11 UTC, Vsevolod1983 commented
> Great job 😄. Since not too many changes have been made yet, it’s worth making some adjustments to the naming. I think we should stick to the following naming scheme: **UnitTestConvSolver**+**_SolverName_**+**_Direction_**. The **UnitTestConvSolver** part is necessary so that we can use a filter to run only tests for convolution solvers. The second part is just the full name of the solver. If the solver's name contains the words 'Conv' or 'Solver', they can be excluded from the name. The third part is the direction. If the solver’s name ends with a direction, this part can be omitted. Full name for the `ConvOclDirectFwd` will end with two directions (part of the solver’s name and the actual direction) for some tests, since this solver also works with the backward direction. What is in this pull request is generally good. All of the above applies only to tests starting with `unit_conv_solver_*`.

Ok, I'll rename

2024-12-23 20:01 UTC, Vsevolod1983 commented
@averinevg 
Done

2024-12-24 18:31 UTC, averinevg approved these changes
LGTM

2024-12-24 19:12 UTC, BradPepersAMD approved these changes
Looks good!

2024-12-24 19:27 UTC, merged