Workaround SWDEV_247082
ROCmSoftwarePlatform/MIOpen pull request #383
Opened 2020-08-17 18:04 UTC by zjing14

- Disabled kperblock = 8

2020-08-31 16:56 UTC, daniellowell commented
@zjing14 What is going on with this PR?

2020-08-31 16:59 UTC, zjing14 commented
The PR is for temporarily workaround the failure reported in SWDEV_247082. The PR is ready.

2020-08-31 22:10 UTC, atamazov commented
It looks good to me. Needs to push it through CI.

2020-08-31 22:11 UTC, atamazov commented
Let me push it once...

2020-09-08 10:54 UTC, atamazov commented
Restarted CI job another time. /cc @zjing14

2020-09-09 20:56 UTC, asroy requested changes

2020-09-09 20:56 UTC, asroy commented on src/solver/implicitgemm_util.hpp
> +#define WORKAROUND_SWDEV_247082 1
Please add comment describing the issue a bit.

2020-09-09 21:05 UTC, asroy commented
@zjing14 Is the bug only to fp32 or fp16/bfp16 as well?

2020-09-09 21:17 UTC, asroy commented on src/solver/implicitgemm_util.hpp
> +    if(GemmKPerBlock == 8)
Does this bug happen for all data type?

2020-09-09 21:18 UTC, zjing14 commented on src/solver/implicitgemm_util.hpp
> +    if(GemmKPerBlock == 8)
At least, happened for fp32/fp16.

2020-09-10 16:44 UTC, daniellowell commented
@zjing14 Merge conflicts.

2020-09-10 17:06 UTC, zjing14 commented
@daniellowell PR https://github.com/ROCmSoftwarePlatform/MIOpen/pull/423 with the same workaround already merged. Closed this.

2020-09-10 17:06 UTC, closed without merging