disable ocl wrw2 solvers
ROCmSoftwarePlatform/MIOpen pull request #400
Opened 2020-08-24 23:31 UTC by ce1adon

2020-08-26 15:13 UTC, atamazov requested changes
The simplest way to disable some Solver is making its `IsApplicable()` return `false'.

Notice that this would allow Immediate mode (and Fast Find mode) to work properly with existing fin-db, because immediate mode checks `IsApplicable()` before running the Solution. Otherwise it would be necessary to regenerate find-db.

2020-08-26 15:13 UTC, atamazov commented on src/solver.cpp
> +#if MIOPEN_BACKEND_OPENCL
This is wrong. We shall put placeholders (`++id`) if we want remove entries from the list. See comment at the beginning of it.

2020-08-26 15:15 UTC, atamazov commented
Notice that some Ocl WrW2 solvers show very good performance untuned. These were originally non-tunable. What is the reason of disabling these?

2020-08-26 15:20 UTC, atamazov commented
IIRC right now we use the same system find-db for both HIP and OCL bakends (generated with HIP backend). After this PR, the system find-db would need to be generated separately for OCL backend, otherwise, with OCL backend, WrW convolutions run in Immediate, Fast Find, and Hybrid Find modes will suffer.

2020-08-26 15:48 UTC, JehandadKhan commented
I am not sure I follow the rationale behind disabling solvers only for HIP. Why is it ok to keep a solver for OpenCL and not for HIP ?

2020-08-26 16:43 UTC, ce1adon commented
> Notice that some Ocl WrW2 solvers show very good performance untuned. These were originally non-tunable. What is the reason of disabling these?

Three reasons:
1. wrw2<1> is leading logic error in this test https://github.com/ROCmSoftwarePlatform/MIOpen/pull/139#issuecomment-678445039

2. In fdb of all architectures wrw usages is less than 4% of all wrw related fdb records 

3. It has been compiled many times in some DL architecture but not finally get chosen, which means they contributed considerable amount of ineffectual exe time.


> The simplest way to disable some Solver is making its `IsApplicable()` return `false`.
> 
> Notice that this would allow Immediate mode (and Fast Find mode) to work properly with existing fin-db, because immediate mode checks `IsApplicable()` before running the Solution. Otherwise it would be necessary to regenerate find-db.

I was thinking about set isapplicable() to false, but worried these kernels may still contribute in the compilation time in the original building. Let's discuss this and nail a solution.

2020-08-26 16:45 UTC, ce1adon commented
> I am not sure I follow the rationale behind disabling solvers only for HIP. Why is it ok to keep a solver for OpenCL and not for HIP ?

I thought we still need these solvers on opencl backend, or we want to eliminate them on both backend?

2020-08-26 17:08 UTC, JehandadKhan commented
> > I am not sure I follow the rationale behind disabling solvers only for HIP. Why is it ok to keep a solver for OpenCL and not for HIP ?
> 
> I thought we still need these solvers on opencl backend, or we want to eliminate them on both backend?

Having them in one and not in the other creates imbalance, perhaps we should collect some data for the OpenCL backend as well and make a holistic decision.

2020-08-26 17:22 UTC, ce1adon commented
> Having them in one and not in the other creates imbalance, perhaps we should collect some data for the OpenCL backend as well and make a holistic decision.

@atamazov @JehandadKhan 
Another strategy in my mind is to have another macro or env to control the use of these kernels. Please evaluate and comment.

2020-08-26 17:26 UTC, ce1adon commented
@atamazov @JehandadKhan 
Before any changes of these solvers applied in dev, we will also need help from Peng's team in evaluating impact on performance. @sunway513

2020-08-26 17:30 UTC, sunway513 commented
Do you think there are any particular workloads that this change can affect their performance?

2020-08-26 20:16 UTC, atamazov commented
@ce1adon 
> Another strategy in my mind is to have another macro or env to control the use of these kernels. Please evaluate and comment.

We have `MIOPEN_DEBUG_CONV_DIRECT_OCL_WRW2` env var.

2020-08-31 20:07 UTC, atamazov commented
https://github.com/AMDComputeLibraries/MLOpen/issues/2534 created.

2020-09-25 18:09 UTC, atamazov commented
See https://github.com/AMDComputeLibraries/MLOpen/issues/2534#issuecomment-699075454

2020-09-25 18:09 UTC, closed without merging