DYNAMIC_HYBRID Find mode
ROCmSoftwarePlatform/MIOpen pull request #417
Opened 2020-09-04 15:23 UTC by atamazov

This implements the DYNAMIC_HYBRID Find mode, see https://github.com/ROCmSoftwarePlatform/MIOpen/issues/398#issuecomment-687210054.

- Added DYNAMIC_HYBRID mode 
- Added/initialized the `use_dynamic_solutions_only` attribute in the convolution context
- Respective Solvers marked as as Dynamic.
- In case of find-db miss, Find uses only dynamic solutions
- TODO Documentation updated

## :cyclone: Local testing

- Performance - in progress
- Correctness - in progress

## Evaluation of performance impact

Collecting data...

2020-09-04 16:08 UTC, atamazov commented
"Evaluation of performance impact" is ready.

2020-09-04 19:17 UTC, atamazov commented
GWSS should also observe `use_dynamic_only`.

2020-09-04 22:25 UTC, JehandadKhan requested changes
Please add the following solvers as well (if they are dynamic)

```c++
ConvAsmImplicitGemmV4R1DynamicBwd
ConvAsmImplicitGemmV4R1DynamicWrw
```

2020-09-04 22:52 UTC, atamazov commented
Ready for another review round.

2020-09-07 17:30 UTC, atamazov commented
"Evaluation of performance impact" updated.

2020-09-07 17:40 UTC, atamazov commented
"Local performance & correctness testing" updated.

2020-09-08 15:20 UTC, atamazov commented on src/include/miopen/find_solution.hpp
> +                    MIOPEN_LOG_I(SolverDbId(solver) << ": Skipped (non-dynamic).");
Done

2020-09-08 15:23 UTC, JehandadKhan commented
@atamazov Do you intend to open a separate PR for the heuristic code place holder ? We can add the called function now, but it would just return. Knowing where the function is would make @zjing14's job much easier.

2020-09-08 20:22 UTC, atamazov commented
@JehandadKhan Yes, there will be separate PR for WTI based heuristic (in progress, ETA this week).

Let's put the MLP classifier into separate module (.cpp with public interface in .hpp). I will integrate it on top of that PR.

2020-09-10 18:35 UTC, JehandadKhan approved these changes

2020-09-10 18:35 UTC, JehandadKhan commented
@daniellowell  Lets merge this in.

2020-09-11 19:02 UTC, merged