Dynamic convbwdbias
ROCmSoftwarePlatform/MIOpen pull request #504
Opened 2020-10-10 00:16 UTC by ce1adon

This PR intends to convert convbwdbias kernel into a dynamic format.

2020-10-12 15:20 UTC, JehandadKhan requested changes
@ce1adon  Can we quantify the change in performance ?

2020-10-19 22:25 UTC, ce1adon commented
Something is wrong with the jenkins indicator. This PR has passed all the tests. Please review it. @JehandadKhan

2020-10-23 02:58 UTC, JehandadKhan commented
@sunway513 Can you please assess the speed up offered by this PR.

2020-10-28 20:01 UTC, JehandadKhan approved these changes

2020-10-29 16:20 UTC, merged