fixed marco of v_add_co_u32
ROCmSoftwarePlatform/MIOpen pull request #515
Opened 2020-10-14 18:17 UTC by zjing14

- Fixed the macro of v_add_co_u32 that allows v_add_u32 with vcc on gfx9

2020-10-14 18:42 UTC, atamazov requested changes
Please explain the problem this PR is expected to resolve (and why this is bug).

2020-10-14 19:42 UTC, zjing14 commented
> Please explain the problem this PR is expected to resolve (and why this is bug).
- Used v_add_u32 with 4 operands on gfx9, but gfx9 should only support 3 operands (
https://llvm.org/docs/AMDGPU/AMDGPUAsmGFX9.html#id19). For some reason, the old assembler (rocm 3.7/3.8) accept it. But it failed with rocm 3.10.

2020-10-14 20:33 UTC, atamazov commented
> * Used v_add_u32 with 4 operands on gfx9, but gfx9 should only support 3 operands

This is workaround that should be active only when assembler has bug 34765 (see https://bugs.llvm.org/show_bug.cgi?id=34765). The library has some code that detects if bug 34765 exists, see 
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/9f5b58026010364c86979c4c6d4a6531858f80ea/src/ocl/gcn_asm_utils.cpp#L278 and how it is used.

I suspect there is a problem with detection of bug 34765. Could you please attach failing log.

2020-10-14 20:39 UTC, atamazov commented
> For some reason, the old assembler (rocm 3.7/3.8) accept it.

Most likely, this is incorrect statement. Macros expand to `v_add_co_u32` because bugzilla 34765 was fixed long ago.

2020-10-14 21:08 UTC, atamazov commented
Or you can send me docker and I will sort it out.

The simplest workaround for now is disabling autodetection of bug (and defining the `WORKAROUND_BUG_34765` symbol) ___in the host code___ like this:
```C++
#include <miopen/hip_build_utils.hpp>
...
#if HIP_RELEASE_VERSION_FLAT < 30300000000 // 3.10.0
    if(GcnAssemblerHasBug34765())
        GenerateClangDefsym(options, "WORKAROUND_BUG_34765", 1);
#endif
```

2020-10-14 21:09 UTC, zjing14 commented
./bin/MIOpenDriver convfp16 -n 256 -c 256 -H 14 -W 14 -k 256 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 4 -t 1
MIOpen(HIP): Info2 [FindSolutionImpl] Perf Db: record loaded: ConvAsmBwdWrW3x3
MIOpen(HIP): Info2 [PrepareInvoker] Preparing kernel: miopenGcnAsmConv3x3WrW
MIOpen(HIP): Info2 [SQLiteBase] Initializing system database file
MIOpen(HIP): Info [KernDb] database not present
MIOpen(HIP): Info2 [SQLiteBase] Initializing user database file /root//.cache/miopen/2.9.0.8230-5e1159233/gfx90878.ukdb
MIOpen(HIP): Info2 [KernDb] Database created successfully
MIOpen(HIP): Info2 [LoadBinary] Loading binary for: conv3x3wrw.s ;args:  -Wa,-defsym,elements_in_dword=2 -Wa,-defsym,batch_size=256 -Wa,-defsym,img_h=14 -Wa,-defsym,img_w=14 -Wa,-defsym,input_channels=256 -Wa,-defsym,output_channels=256 -Wa,-
defsym,wei_h=3 -Wa,-defsym,wei_w=3 -Wa,-defsym,pad_h=1 -Wa,-defsym,pad_w=1 -Wa,-defsym,stride_h=1 -Wa,-defsym,stride_w=1 -Wa,-defsym,weights_layout=0 -Wa,-defsym,reverse_weights=0 -Wa,-defsym,ROCM_METADATA_VERSION=5 -Wa,-defsym,limit_wave_cnt
=0 -Wa,-defsym,chunk_size=8 -Wa,-defsym,c_per_wave=8 -Wa,-defsym,k_per_wave=4 -Wa,-defsym,n_per_group=2 -Wa,-defsym,pipe_lines_depth=6 -Wa,-defsym,reverse_inout=0 -Wa,-defsym,enable_debug_output=0 -Wa,-defsym,group_counts=1 -Wa,-defsym,k_grou
p_size_is_power_of_two=1 -mcpu=gfx908
MIOpen(HIP): Info2 [Prepare] SELECT kernel_blob, kernel_hash, uncompressed_size FROM kern_db WHERE (kernel_name = 'conv3x3wrw.s.o') AND (kernel_args = ' -Wa,-defsym,elements_in_dword=2 -Wa,-defsym,batch_size=256 -Wa,-defsym,img_h=14 -Wa,-defs
ym,img_w=14 -Wa,-defsym,input_channels=256 -Wa,-defsym,output_channels=256 -Wa,-defsym,wei_h=3 -Wa,-defsym,wei_w=3 -Wa,-defsym,pad_h=1 -Wa,-defsym,pad_w=1 -Wa,-defsym,stride_h=1 -Wa,-defsym,stride_w=1 -Wa,-defsym,weights_layout=0 -Wa,-defsym,
reverse_weights=0 -Wa,-defsym,ROCM_METADATA_VERSION=5 -Wa,-defsym,limit_wave_cnt=0 -Wa,-defsym,chunk_size=8 -Wa,-defsym,c_per_wave=8 -Wa,-defsym,k_per_wave=4 -Wa,-defsym,n_per_group=2 -Wa,-defsym,pipe_lines_depth=6 -Wa,-defsym,reverse_inout=0
 -Wa,-defsym,enable_debug_output=0 -Wa,-defsym,group_counts=1 -Wa,-defsym,k_group_size_is_power_of_two=1 -mcpu=gfx908');
MIOpen(HIP): Info2 [Measure] Db::FindRecord time: 0.0851 ms
MIOpen(HIP): Info2 [LoadBinary] Unable to load binary for: conv3x3wrw.s ;args:  -Wa,-defsym,elements_in_dword=2 -Wa,-defsym,batch_size=256 -Wa,-defsym,img_h=14 -Wa,-defsym,img_w=14 -Wa,-defsym,input_channels=256 -Wa,-defsym,output_channels=25
6 -Wa,-defsym,wei_h=3 -Wa,-defsym,wei_w=3 -Wa,-defsym,pad_h=1 -Wa,-defsym,pad_w=1 -Wa,-defsym,stride_h=1 -Wa,-defsym,stride_w=1 -Wa,-defsym,weights_layout=0 -Wa,-defsym,reverse_weights=0 -Wa,-defsym,ROCM_METADATA_VERSION=5 -Wa,-defsym,limit_w
ave_cnt=0 -Wa,-defsym,chunk_size=8 -Wa,-defsym,c_per_wave=8 -Wa,-defsym,k_per_wave=4 -Wa,-defsym,n_per_group=2 -Wa,-defsym,pipe_lines_depth=6 -Wa,-defsym,reverse_inout=0 -Wa,-defsym,enable_debug_output=0 -Wa,-defsym,group_counts=1 -Wa,-defsym
,k_group_size_is_power_of_two=1 -mcpu=gfx908
MIOpen(HIP): Info2 [AmdgcnAssembleQuiet] /opt/rocm/llvm/bin/clang  -x assembler -target amdgcn--amdhsa  -mno-xnack-mcpu=gfx900 /tmp/2b89-f92e-69d1-272f -o /dev/null 2>&1
MIOpen(HIP): Info [GcnAssemblerHasBug34765Impl] Detected
MIOpen(HIP): Info2 [AmdgcnAssemble] ' -x assembler -target amdgcn--amdhsa -mno-xnack  -Wa,-defsym,elements_in_dword=2 -Wa,-defsym,batch_size=256 -Wa,-defsym,img_h=14 -Wa,-defsym,img_w=14 -Wa,-defsym,input_channels=256 -Wa,-defsym,output_chann
els=256 -Wa,-defsym,wei_h=3 -Wa,-defsym,wei_w=3 -Wa,-defsym,pad_h=1 -Wa,-defsym,pad_w=1 -Wa,-defsym,stride_h=1 -Wa,-defsym,stride_w=1 -Wa,-defsym,weights_layout=0 -Wa,-defsym,reverse_weights=0 -Wa,-defsym,ROCM_METADATA_VERSION=5 -Wa,-defsym,l
imit_wave_cnt=0 -Wa,-defsym,chunk_size=8 -Wa,-defsym,c_per_wave=8 -Wa,-defsym,k_per_wave=4 -Wa,-defsym,n_per_group=2 -Wa,-defsym,pipe_lines_depth=6 -Wa,-defsym,reverse_inout=0 -Wa,-defsym,enable_debug_output=0 -Wa,-defsym,group_counts=1 -Wa,-
defsym,k_group_size_is_power_of_two=1 -mcpu=gfx908 -Wa,-defsym,WORKAROUND_BUG_34765=1 - -o /tmp/miopen-tmp-52d1-d5c2-bbe2-7c36/amdgcn-asm-out-XXXXXX'
<instantiation>:2:9: error: instruction not supported on this GPU
        v_add_u32 v[voffset_in], vcc, v[voffset_in], v[vtmp]
        ^
<stdin>:1173:3: note: while in macro instantiation
  _v_add_co_u32 v[voffset_in], vcc, v[voffset_in], v[vtmp]
  ^
<instantiation>:2:9: error: instruction not supported on this GPU
        v_add_u32 v[voffset_out], vcc, v[voffset_out], v[vtmp]
        ^
<stdin>:1176:6: note: while in macro instantiation
     _v_add_co_u32 v[voffset_out], vcc, v[voffset_out], v[vtmp]

2020-10-14 21:10 UTC, zjing14 commented
docker: compute-artifactory.amd.com:5000/rocm-plus-docker/framework/compute-rocm-dkms-no-npi-hipclang:3873_ubuntu_py3_tensorflow_develop-upstream-QA-rocm39

2020-10-14 21:19 UTC, atamazov commented
In the log: `MIOpen(HIP): Info [GcnAssemblerHasBug34765Impl] Detected`. This shouldn't be so unless, to put it mildly, _quiet change of behavior_ of the assembler in the 3.10. Bug auto-detection is broken.

If you re-implement this PR as shown at https://github.com/ROCmSoftwarePlatform/MIOpen/pull/515#issuecomment-708660916, I will approve.

2020-10-14 21:22 UTC, atamazov commented
Oops I see the bug. In the log:
```
...-x assembler -target amdgcn--amdhsa  -mno-xnack-mcpu=gfx900...
                                                  ^
                                                  | missing space
```

2020-10-14 21:27 UTC, atamazov commented
Here is the bug and how to fix it: https://github.com/ROCmSoftwarePlatform/MIOpen/pull/505/files#r504981837

/cc @shurale-nkn

2020-10-15 11:33 UTC, atamazov commented
Let me do the fix myself.

2020-10-15 12:42 UTC, atamazov commented
The xnack option is not actually needed in AmdgcnAssembleQuiet() -- at least, for now. And it is _missing_ in comgr.

2020-10-15 12:50 UTC, atamazov commented
Description updated.

2020-10-15 12:52 UTC, atamazov approved these changes
LGTM but @zjing14 and @shurale-nkn -- please have a look.

2020-10-15 15:32 UTC, shurale-nkn commented
@atamazov 
<details><summary><b><i>LOG</i></b></summary><hr>
root@panzerfaust:/home/kamil/vf/MLOpen-build_2# ./bin/MIOpenDriver convfp16 -n 256 -c 256 -H 14 -W 14 -k 256 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 4 -t 1
MIOpenDriver convfp16 -n 256 -c 256 -H 14 -W 14 -k 256 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 4 -t 1
MIOpen(HIP): Info [Handle] stream: 0x217e870, device_id: 0
MIOpen(HIP): Info [BackwardWeightsGetWorkSpaceSize] 
MIOpen(HIP): Info [GetFindModeValueImpl] MIOPEN_FIND_MODE = NORMAL(1)
MIOpen(HIP): Info2 [HipCompilerVersionImpl] Read version information from HIP package...
MIOpen(HIP): Info [HipCompilerVersionImpl] 3.8.20403
MIOpen(HIP): Info [AmdRocmMetadataVersionDetect] ROCm MD version AMDHSA_COv3, MIOpen version 2.9.0.8231-7685b050d
MIOpen(HIP): Info2 [ValidateGcnAssemblerImpl] Running: '/opt/rocm/llvm/bin/clang --version'
MIOpen(HIP): Info2 [ValidateGcnAssemblerImpl] clang version 12.0.0 (/src/external/llvm-project/clang 6eff66235fa65089b4767ad0f0d39e25e292e095)
MIOpen(HIP): Info2 [ValidateGcnAssemblerImpl] Target: x86_64-unknown-linux-gnu
MIOpen(HIP): Info2 [ValidateGcnAssemblerImpl] Thread model: posix
MIOpen(HIP): Info2 [ValidateGcnAssemblerImpl] InstalledDir: /opt/rocm/llvm/bin/original
MIOpen(HIP): Info2 [ValidateGcnAssemblerImpl] 
MIOpen(HIP): Info2 [SQLiteBase] Initializing system database file /home/kamil/vf/MLOpen/src/kernels/miopen.db
MIOpen(HIP): Trace [Exec] 139865151724032:PRAGMA table_info(config);
MIOpen(HIP): Trace [Exec] 139865151724032:PRAGMA table_info(perf_db);
MIOpen(HIP): Info2 [SQLiteBase] Initializing user database file /home/kamil/vf/MLOpen/src/kernels/miopen_1.0.0.udb
MIOpen(HIP): Trace [Exec] 139865151724032:SELECT name FROM sqlite_master WHERE type = 'table' AND (name = 'config');
MIOpen(HIP): Trace [Exec] 139865151724032:SELECT name FROM sqlite_master WHERE type = 'table' AND (name = 'perf_db');
MIOpen(HIP): Trace [SQLitePerfDb] Database created successfully
MIOpen(HIP): Trace [Exec] 139865151724032:PRAGMA table_info(config);
MIOpen(HIP): Trace [Exec] 139865151724032:PRAGMA table_info(perf_db);
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvHipImplicitGemmWrwV4R4Xdlops: Not applicable
MIOpen(HIP): Info [FindSolutionImpl] ConvHipImplicitGemmV4R1WrW (db access disabled)
MIOpen(HIP): Info [EuristicInit] 16,128,8,2,4,4,4,4,4,4,8,2,16,1,2,128
MIOpen(HIP): Info [GetPerformanceConfigBase] 16,128,8,2,4,4,4,4,4,4,8,2,16,1,2,128
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvHipImplicitGemmV4R1WrW: Success.
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvBinWinogradRxS: Not applicable
MIOpen(HIP): Info [FindSolutionImpl] ConvBinWinogradRxSf2x3 (db access disabled)
MIOpen(HIP): Info [GetPerformanceConfig] 60
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvBinWinogradRxSf2x3: Success.
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvWinograd3x3MultipassWrW<3-2>: Not applicable
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvWinograd3x3MultipassWrW<3-3>: Not applicable
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvWinograd3x3MultipassWrW<3-4>: Not applicable
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvWinograd3x3MultipassWrW<3-5>: Not applicable
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvWinograd3x3MultipassWrW<3-6>: Not applicable
MIOpen(HIP): Info2 [IsApplicable] Workspace required: 1051066368, limit: 2000000000
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvWinograd3x3MultipassWrW<7-2>: Not applicable
MIOpen(HIP): Info2 [IsApplicable] Workspace required: 808845312, limit: 2000000000
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvWinograd3x3MultipassWrW<7-3>: Not applicable
MIOpen(HIP): Info2 [IsApplicable] Workspace required: 408027136, limit: 2000000000
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvWinograd3x3MultipassWrW<7-3-1-1>: Not applicable
MIOpen(HIP): Info2 [IsApplicable] Workspace required: 465960960, limit: 2000000000
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvWinograd3x3MultipassWrW<7-2-1-1>: Not applicable
MIOpen(HIP): Info2 [IsApplicable] Workspace required: 465960960, limit: 2000000000
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvWinograd3x3MultipassWrW<1-1-7-2>: Not applicable
MIOpen(HIP): Info2 [IsApplicable] Workspace required: 408027136, limit: 2000000000
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvWinograd3x3MultipassWrW<1-1-7-3>: Not applicable
MIOpen(HIP): Info2 [IsApplicable] Workspace required: 327548928, limit: 2000000000
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvWinograd3x3MultipassWrW<5-3>: Not applicable
MIOpen(HIP): Info2 [IsApplicable] Workspace required: 276824064, limit: 2000000000
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvWinograd3x3MultipassWrW<5-4>: Not applicable
MIOpen(HIP): Info2 [GetWorkspaceSize] ConvAsmBwdWrW1x1: Not applicable
MIOpen(HIP): Info2 [GetWorkspaceSize] ConvOclBwdWrW2<1>: Not applicable
MIOpen(HIP): Info2 [GetWorkspaceSize] ConvOclBwdWrW2<2>: Not applicable
MIOpen(HIP): Info2 [GetWorkspaceSize] ConvOclBwdWrW2<4>: Not applicable
MIOpen(HIP): Info2 [GetWorkspaceSize] ConvOclBwdWrW2<8>: Not applicable
MIOpen(HIP): Info2 [GetWorkspaceSize] ConvOclBwdWrW2<16>: Not applicable
MIOpen(HIP): Info2 [GetWorkspaceSize] ConvOclBwdWrW1x1: Not applicable
MIOpen(HIP): Info2 [BackwardWeightsGetWorkSpaceSizeDirect] 0 < 301989888
MIOpen(HIP): Info2 [BackwardWeightsGetWorkSpaceSize] 301989888
MIOpen(HIP): Info [FindConvBwdWeightsAlgorithm] requestAlgoCount = 2, workspace = 301989888
MIOpen(HIP): Info2 [FindRecordUnsafe] Looking for key 256-14-14-3x3-256-14-14-256-1x1-1x1-1x1-0-NCHW-FP16-W in file /home/kamil/vf/MLOpen/src/kernels/gfx906_60.HIP.2_9_0.ufdb.txt
MIOpen(HIP): Info2 [Measure] Db::FindRecord time: 0.114088 ms
MIOpen(HIP): Info [TryLoad] Find-db regenerating.
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvAsmBwdWrW1x1: Not applicable
MIOpen(HIP): Info [FindSolutionImpl] ConvAsmBwdWrW3x3
MIOpen(HIP): Info2 [Prepare] SELECT solver, params FROM perf_db INNER JOIN config ON perf_db.config = config.id WHERE ( (layout = ? ) AND (data_type = ? ) AND (direction = ? ) AND (spatial_dim = ? ) AND (in_channels = ? ) AND (in_h = ? ) AND (in_w = ? ) AND (in_d = ? ) AND (fil_h = ? ) AND (fil_w = ? ) AND (fil_d = ? ) AND (out_channels = ? ) AND (batchsize = ? ) AND (pad_h = ? ) AND (pad_w = ? ) AND (pad_d = ? ) AND (conv_stride_h = ? ) AND (conv_stride_w = ? ) AND (conv_stride_d = ? ) AND (dilation_h = ? ) AND (dilation_w = ? ) AND (dilation_d = ? ) AND (bias = ? ) AND (group_count = ? ) )AND (arch = 'gfx906' ) AND (num_cu = '60');
MIOpen(HIP): Info2 [impl] [NCHW,FP16,W,2,256,14,14,1,3,3,1,256,256,1,1,0,1,1,0,1,1,0,0,1]
MIOpen(HIP): Info2 [Prepare] SELECT solver, params FROM perf_db INNER JOIN config ON perf_db.config = config.id WHERE ( (layout = ? ) AND (data_type = ? ) AND (direction = ? ) AND (spatial_dim = ? ) AND (in_channels = ? ) AND (in_h = ? ) AND (in_w = ? ) AND (in_d = ? ) AND (fil_h = ? ) AND (fil_w = ? ) AND (fil_d = ? ) AND (out_channels = ? ) AND (batchsize = ? ) AND (pad_h = ? ) AND (pad_w = ? ) AND (pad_d = ? ) AND (conv_stride_h = ? ) AND (conv_stride_w = ? ) AND (conv_stride_d = ? ) AND (dilation_h = ? ) AND (dilation_w = ? ) AND (dilation_d = ? ) AND (bias = ? ) AND (group_count = ? ) )AND (arch = 'gfx906' ) AND (num_cu = '60');
MIOpen(HIP): Info2 [impl] [NCHW,FP16,W,2,256,14,14,1,3,3,1,256,256,1,1,0,1,1,0,1,1,0,0,1]
MIOpen(HIP): Info [SetValues] , content inserted: ConvAsmBwdWrW3x3:0,0,8,4,4,1
MIOpen(HIP): Info [SetValues] , content inserted: ConvBinWinogradRxSf2x3:60
MIOpen(HIP): Info [SetValues] , content inserted: ConvHipImplicitGemmV4R1WrW:16,64,16,2,2,2,4,4,4,4,16,1,16,1,4,64
MIOpen(HIP): Info [GetValues] =ConvAsmBwdWrW3x3:0,0,8,4,4,1
MIOpen(HIP): Info2 [Measure] Db::Load time: 160.079 ms
MIOpen(HIP): Info2 [FindSolutionImpl] Perf Db: record loaded: ConvAsmBwdWrW3x3
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvAsmBwdWrW3x3: Success.
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvOclBwdWrW2<1>: Not applicable
MIOpen(HIP): Info2 [SearchForAllSolutions] ConvOclBwdWrW2<2>: Not applicable
MIOpen(HIP): Info2 [Sea [...]

2020-10-15 15:36 UTC, zjing14 commented
@shurale-nkn Which GPU are you using? gfx906?

2020-10-15 15:41 UTC, atamazov commented
@shurale-nkn This is different problem. Use `export MIOPEN_DEBUG_IMPLICIT_GEMM_NON_XDLOPS_INLINE_ASM=0` to disable inline asm in HIP kernels as a temporary workaround.

2020-10-15 15:42 UTC, atamazov commented
The issue described at https://github.com/ROCmSoftwarePlatform/MIOpen/pull/515/#issuecomment-709406639 should be resolved in separate PR.

2020-10-15 15:56 UTC, daniellowell commented
v_dot is affected as well it looks like.

2020-10-15 16:02 UTC, zjing14 commented
Tested with gfx908, no issue. Let me try it on gfx906.

2020-10-15 19:04 UTC, zjing14 commented
@shurale-nkn Which docker image you are using? According to your logs, the compiler version is 3.8. Are you using rocm 3.8?

2020-10-15 20:12 UTC, daniellowell commented
@atamazov @zjing14 @shurale-nkn Despite the issues seen in v_dot is this PR good to go?

2020-10-15 20:45 UTC, shurale-nkn commented
> @shurale-nkn Which docker image you are using? According to your logs, the compiler version is 3.8. Are you using rocm 3.8?

image: compute-rocm-dkms-amd-feature-targetid-78

\$ dpkg -l| grep rocm-dev
ii  rocm-dev                               3.9.0.30900-crdaft.78                                  amd64        Radeon Open Compute (ROCm) Runtime software stack

2020-10-15 20:51 UTC, shurale-nkn commented
> @atamazov @zjing14 @shurale-nkn Despite the issues seen in v_dot is this PR good to go?

@daniellowell 
I still want to have a function to switch between enabled and disabled xnack arguments, not just turn it off. But for now this PR is good.

2020-10-16 13:54 UTC, atamazov commented
@zjing14 
>  Which docker image you are using?

This is target-id feature preview targeted to ROCm 4.0

@daniellowell 
> Despite the issues seen in v_dot is this PR good to go?

Yes.

2020-10-16 20:21 UTC, merged