Fixed offload_arch cflags with targetID HIP
ROCmSoftwarePlatform/MIOpen pull request #585
Opened 2020-11-11 18:15 UTC by zjing14

- Remove all offload_arch flags in HIP_COMPILER_FLAGS, and then add offload_arch flag back with the target device.

2020-11-11 19:57 UTC, atamazov requested changes

2020-11-11 19:57 UTC, atamazov commented on src/hip/hip_build_utils.cpp
> +    params += " --" + std::string(MIOPEN_ARCH_FLAG) + "=" + dev_name;
Move it to line 115 (i.e. replace line 115 with it). And what about line 116 ("--cuda-device-only")?

2020-11-11 19:58 UTC, atamazov commented
@t-tye Please let me know if COMgr path also needs to be fixed.

2020-11-11 21:24 UTC, t-tye commented
> 
> 
> @t-tye Please let me know if COMgr path also needs to be fixed. I guess not -- right now we are not passing anything like "---cuda..." to COMgr.

COMgr takes the name of the target as a target ID now. So you can askp for a "gfx908:sramecc+:xnack-". If you ask simply for "gfx908" you will get a code object that will work with any setting of sramecc or xnack. So does the code currently specify the xnack/sramecc settings? If so the old method still works (using -mxnack/-msramecc) but the new method can be used instead.

2020-11-16 06:29 UTC, zjing14 commented
CI passed.

2020-11-17 02:39 UTC, pfultz2 approved these changes

2020-11-23 21:32 UTC, daniellowell commented
@zjing14 @atamazov is this needed still?

2020-11-23 22:03 UTC, atamazov commented
@daniellowell I guess so.

2021-01-26 16:38 UTC, daniellowell commented
@zjing14 is this still required?

2021-03-07 20:06 UTC, atamazov commented
Oops, SWDEV-259381 is closed. I think I or someone else has already fixed this.

2021-03-07 20:06 UTC, closed without merging