Winograd RxSf2x3 solver V21_1_2 update
ROCmSoftwarePlatform/MIOpen pull request #626
Opened 2020-11-25 21:18 UTC by Slimakanzer

Winograd V21_1_2 changes compared to #175 :
* Fixed bugs
* Tensor offset support (64 bit byte offsets)

2020-11-26 06:59 UTC, Kirpich30000 requested changes

2020-11-26 06:59 UTC, Kirpich30000 commented on src/kernels/Conv_Winograd_v21_1_2_metadata.inc
> +    - { .size: 8, .offset: 112, .value_kind: by_value, .value_type: i64, .name: f_offset }
Please explicitly add reserved2 field. See latest updates of the winograd shader.

2020-11-26 06:59 UTC, Kirpich30000 commented on src/solver/conv_winoRxS_f2x3.cpp
> +        long int reserved_offset = 0;
better to use uint64_t

2020-11-26 06:59 UTC, Kirpich30000 commented on src/solver/conv_winoRxS_f2x3.cpp
> +            MIOPEN_LOG_WE(SolverDbId(*this)
Why was it reformatted?

2020-11-26 06:59 UTC, Kirpich30000 commented on src/solver/conv_winoRxS_f2x3.cpp
> +    const PerformanceConfigConvBinWinogradRxSf2x3& other) const
Why was it reformatted?

2020-11-26 07:06 UTC, Kirpich30000 commented
Few more features should be added in following PRs. Please create sepparate issues to support:
- gfx10
- filter traverse modes
- extended applicability with multiple dispatches

2020-12-09 16:27 UTC, atamazov commented
@Slimakanzer Please use drafts instead of `work_in_progress` label. 
![image](https://user-images.githubusercontent.com/12697412/101657097-89e3be80-3a54-11eb-9c2d-d117b01bddc4.png)

2020-12-10 12:07 UTC, Kirpich30000 commented on src/kernels/Conv_Winograd_v21_1_2_metadata.inc
>      - { .size: 8, .offset:  88, .value_kind: global_buffer, .value_type: f32, .name: bias_addr,    .address_space: global, .is_const: true }
BTW, why only `bias_addr` is marked as `.is_const: true`
Let's make `in` and `weights` const also

2020-12-11 11:37 UTC, Kirpich30000 approved these changes
LGTM

2020-12-16 16:10 UTC, merged