[iGemmFix] Disabled the igemm_bwd v4r1_xdlops solver due to accuracy loss
ROCmSoftwarePlatform/MIOpen pull request #645
Opened 2020-12-07 16:06 UTC by zjing14

- Disabled the igemm_bwd v4r1_xdlops solver for fp32 and fp16 due to a convergence issue with ResNet50v1.5

2020-12-07 16:10 UTC, asroy approved these changes

2020-12-07 16:13 UTC, daniellowell approved these changes

2020-12-07 18:31 UTC, atamazov commented
@zjing14 Could you please elaborate a bit why convergence issues in ResNet50v1.5 mean that igemm_bwd_v4r1_xdlops has problems. Link to the existing issue would be enough.

2020-12-07 20:48 UTC, zjing14 commented
@atamazov We did not have a ticket or issue related to it. We performed bisect on all xdlops igemm, and isolated the problem solver is igemm_bwd_v4r1_xdlops.

2020-12-07 22:35 UTC, atamazov requested changes

2020-12-07 22:35 UTC, atamazov commented on src/solver/conv_hip_implicit_gemm_bwd_v4r1_xdlops.cpp
> +    if(!miopen::IsEnabled(MIOPEN_DEBUG_CONV_IMPLICIT_GEMM_HIP_BWD_V4R1_XDLOPS{}))
As we do not know exact reason of the issue, let's make it a workaround, see #561.

2020-12-15 19:57 UTC, daniellowell commented
#644 fixes this issue, so this PR is not needed.

2020-12-15 19:58 UTC, closed without merging