remove test_conv_igemm_dynamic_small from unapplicable test
ROCmSoftwarePlatform/MIOpen pull request #649
Opened 2020-12-08 06:34 UTC by carlushuang

this fixes https://github.com/ROCmSoftwarePlatform/MIOpen/issues/648 by removing test_conv_igemm_dynamic_small from onot applicable test case

2020-12-08 16:44 UTC, atamazov reviewed
I am unable to review this as I do not understand the original issue #648. Someone please elaborate it.

2020-12-10 07:45 UTC, asleepzzz commented
I updated log  in https://github.com/ROCmSoftwarePlatform/MIOpen/issues/648,
this unit test is only for gfx908, we should disable this test if platform is not 908

2020-12-10 17:14 UTC, asroy commented
> I am unable to review this as I do not understand the original issue #648. Someone please elaborate it.

Yea, this PR and original issue need more clarification
@carlushuang

2021-01-15 19:38 UTC, atamazov requested changes
Perhaps I do not understand something?

2021-01-16 03:42 UTC, carlushuang commented on test/CMakeLists.txt
> +add_custom_test(test_conv_igemm_dynamic SKIP_UNLESS_ALL
Hi @atamazov I think you are right. Let me just move `test_conv_igemm_dynamic` to `SKIP_TEST` when under gfx908 test.(`MIOPEN_TEST_GFX908`)

2021-01-16 03:43 UTC, carlushuang commented on test/CMakeLists.txt
> +add_custom_test(test_conv_igemm_dynamic SKIP_UNLESS_ALL
Yes, this is small test. Let me move to `SKIP_TEST` when under gfx908

2021-02-22 18:06 UTC, atamazov requested changes
~One mandatory comment.~ Review is irrelevant.

2021-02-22 18:06 UTC, atamazov commented on test/CMakeLists.txt
> +       set(SKIP_TESTS test_immed_conv3d test_conv3d test_fusion_aux test_activation test_lrn_test test_ctc test_conv2d_bias test_conv3d_bias test_cba_inference test_cbna_inference test_pooling2d test
[Recommendation] Add `${SKIP_TESTS}` at the end to keep values added to `SKIP_TESTS` when backend is OpenCL.

2021-02-22 18:08 UTC, atamazov commented on test/CMakeLists.txt
> +        set(SKIP_TESTS test_gru test_rnn_vanilla test_lstm test_conv_igemm_dynamic test_conv_igemm_dynamic_small)
[Note] Yes, I know that we do not test OCL backend with gfx908 yet.

2021-02-22 18:12 UTC, atamazov commented on test/CMakeLists.txt
> +        set(SKIP_TESTS test_gru test_rnn_vanilla test_lstm test_conv_igemm_dynamic test_conv_igemm_dynamic_small)
Oops, the comment is wrong.

2021-02-22 18:13 UTC, atamazov commented on test/CMakeLists.txt
> +        set(SKIP_TESTS test_gru test_rnn_vanilla test_lstm test_conv_igemm_dynamic test_conv_igemm_dynamic_small)
`test_conv_igemm_dynamic` and `test_conv_igemm_dynamic_small` tests only FP32.

2021-02-22 18:22 UTC, atamazov requested changes
`test_conv_igemm_dynamic` and `test_conv_igemm_dynamic_small` should be only used with Vega targets and only with FP32 datatypes. This doesn't happen due to a bug in `add_custom_test`. Fix is #750 

Please confirm and close this PR.

2021-02-24 02:23 UTC, carlushuang commented
> `test_conv_igemm_dynamic` and `test_conv_igemm_dynamic_small` should be only used with Vega targets and only with FP32 datatypes. This doesn't happen due to a bug in `add_custom_test`. Fix is #750
> 
> Please confirm and close this PR.

As per https://github.com/ROCmSoftwarePlatform/MIOpen/pull/750#discussion_r581140999, this PR should closed, but in order to remove `test_conv_igemm_dynamic` / `test_conv_igemm_dynamic_small` from gfx908 target, better refactor these custom test inside `if(NOT MIOPEN_TEST_GFX908)`
```
if(NOT MIOPEN_TEST_GFX908)
    add_custom_test(test_conv_igemm_dynamic_small
    ...
    )
endif()
```

2021-02-24 02:23 UTC, closed without merging

2021-02-24 16:58 UTC, atamazov commented
Yes, this file needs redesign.