Report correct CU count for gfx10
ROCmSoftwarePlatform/MIOpen pull request #655
Opened 2020-12-16 13:19 UTC by Slimakanzer

resolves #654 

Continuation of #653.
This PR provides a function in the Handle to get actual number of _CUs_. This is important for gfx10 GPUs since this generation introduced the concept of _WGP_ (wrokgroup processor), which contain 2 _CUs_. In this case, the OCL and HIP backends report the **number of WGPs instead of CUs**.  Using the number of _WPGs_ instead of _CUs_ in winogradRxSf2x3 gfx10 may have performance regression as mentioned in #654.

## Summary of code changes
* Added `GetMaxHardwareComputeUnits()` to get actual number of CUs instead of WGPs
* Replaced `GetMaxComputeUnits()` with `GetMaxHardwareComputeUnits()` in the winoRxS_f2x3 solver

## Local performance testing
Convolution time improvements compared with #653.
* gfx1030, ROCm 3.9
* OCL + HIP backend
* fp16 + fp32

W | H | c | n | k | x | y | p | q | u | v | g | dir | | perf
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
14 | 14 | 1024 | 64 | 1024 | 3 | 3 | 1 | 1 | 1 | 1 | 1 | fwd | | -8%
14 | 14 | 1024 | 64 | 1024 | 3 | 3 | 1 | 1 | 2 | 2 | 1 | fwd | | -8%
14 | 14 | 1024 | 64 | 1024 | 3 | 3 | 1 | 1 | 1 | 1 | 1 | wrw | | 0%
14 | 14 | 1024 | 64 | 1024 | 3 | 3 | 1 | 1 | 1 | 1 | 1 | bwd | | 0%
14 | 14 | 1024 | 64 | 1024 | 3 | 3 | 1 | 1 | 2 | 2 | 1 | bwd | | -8%
56 | 56 | 2048 | 128 | 2048 | 3 | 3 | 1 | 1 | 1 | 1 | 1 | fwd | | 49%
56 | 56 | 2048 | 128 | 2048 | 3 | 3 | 1 | 1 | 2 | 2 | 1 | fwd | | 61%
56 | 56 | 2048 | 128 | 2048 | 3 | 3 | 1 | 1 | 1 | 1 | 1 | bwd | | 49%
56 | 56 | 2048 | 128 | 2048 | 3 | 3 | 1 | 1 | 2 | 2 | 1 | bwd | | 50%
56 | 56 | 2048 | 128 | 2048 | 3 | 3 | 1 | 1 | 1 | 1 | 1 | wrw | | 0%
224 | 224 | 512 | 64 | 512 | 3 | 3 | 1 | 1 | 1 | 1 | 1 | fwd | | 47%
224 | 224 | 512 | 64 | 512 | 3 | 3 | 1 | 1 | 2 | 2 | 1 | fwd | | 47%
224 | 224 | 512 | 64 | 512 | 3 | 3 | 1 | 1 | 1 | 1 | 1 | bwd | | 47%
224 | 224 | 512 | 64 | 512 | 3 | 3 | 1 | 1 | 2 | 2 | 1 | bwd | | 47%
224 | 224 | 512 | 64 | 512 | 3 | 3 | 1 | 1 | 1 | 1 | 1 | wrw | | 32%

2020-12-16 20:31 UTC, atamazov requested changes
This PR needs to be redone on top of `develop` branch.

2020-12-21 15:33 UTC, atamazov commented
Still too many commits in this PR. Please try to merge the tip of develop onto this branch; this may help.

2020-12-28 20:55 UTC, atamazov commented
@Slimakanzer 
```bash
git checkout develop
git pull origin develop
git checkout gfx10-hardware-cu-count
git merge develop
git push origin gfx10-hardware-cu-count
```

2020-12-29 04:46 UTC, Slimakanzer commented
@atamazov 
The problem was that the current branch is inherited from [winograd_v21_1_2](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/626) that was *squash merged* into the `develop` branch. The only way to remove unnecessary commits from the [winograd_v21_1_2](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/626) (because of *squash merge*) branch and redo this PR on top of `develop` is to use `git rebase`.

If I did a *merge* instead of a *rebase*, there would be a lot of unnecessary commits from the [winograd_v21_1_2](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/626) branch, making this PR difficult to understand.

2020-12-29 23:59 UTC, atamazov commented
I already see 10 commits in this PR instead of 2. At last, you can export diff, apply it to a new branch and create some new PR.

2021-01-11 18:25 UTC, daniellowell commented
@Slimakanzer Status?

2021-01-13 17:51 UTC, Slimakanzer commented
Superseded by #677

2021-01-13 19:08 UTC, closed without merging