adopt public resource
ROCmSoftwarePlatform/MIOpen pull request #868
Opened 2021-04-19 17:13 UTC by ce1adon

Update repo address

2021-04-19 17:25 UTC, pfultz2 approved these changes

2021-04-19 17:31 UTC, atamazov requested changes

2021-04-19 17:31 UTC, atamazov commented on Jenkinsfile
> +            defaultValue: true,
Please revert this

2021-04-19 17:31 UTC, atamazov commented on Jenkinsfile
> +            defaultValue: true,
And this.

2021-04-19 17:43 UTC, ce1adon commented on Jenkinsfile
> +            defaultValue: true,
Will do when CI passes.

2021-04-19 17:43 UTC, atamazov commented
There is no need to change Jenkinsfile to just to toggle some stage ON or OFF.

BTW I just re-run the CI job with "MIOPENTENSILE" and "SMOKE_MIOPENTENSILE_LATEST" manually set. This should be enough to test this PR.

2021-04-19 17:45 UTC, shurale-nkn submitted a review, later dismissed
But in future, please use Jenkins GUI for parameters changing and start testing job manually.
<img src="https://user-images.githubusercontent.com/37591772/115279981-0ea3bf00-a150-11eb-9d27-ee68ae3eb5f0.png" width=50%>

2021-04-19 17:49 UTC, ce1adon commented
> But in future, please use Jenkins GUI for parameters changing and start testing job manually.
> <img src"https://user-images.githubusercontent.com/37591772/115279981-0ea3bf00-a150-11eb-9d27-ee68ae3eb5f0.png" width=50%>

Isn't this going to make the tracking of the test results more complex? How do you distinguish the parameter you toggled for each test for the same PR?

2021-04-19 17:51 UTC, ce1adon commented
> There is no need to change Jenkinsfile just to toggle some stage ON or OFF.
> 
> BTW I just re-run the CI job with "MIOPENTENSILE" and "SMOKE_MIOPENTENSILE_LATEST" manually set (the rest is cleared). This should be enough to test this PR.

Please also check with Paul.

2021-04-19 17:57 UTC, shurale-nkn commented
> 
> Isn't this going to make the tracking of the test results more complex? How do you distinguish the parameter you toggled for each test for the same PR?

The time required to start testing is incomparably less than the duration of testing. It also saves a lot more time than you spent. We hope that all participants are able to visually compare the list of running stages and determine whether they are enough or not. 
Jenkins keeps all job logs for analysis.

2021-04-19 22:36 UTC, ce1adon commented
@shurale-nkn Looks like jenkins is still down.

2021-04-19 22:39 UTC, atamazov commented
> @shurale-nkn Looks like jenkins is still down.

There were transient problems. It works somehow; I just restarted the job.

2021-04-19 23:30 UTC, junliume commented
> > @shurale-nkn Looks like jenkins is still down.
> 
> There were transient problems. It works somehow; I just restarted the job.

Is the Jenkins issue still persistent? I think devops upgraded and downgraded it today due to plugin compatibility issue

2021-04-19 23:34 UTC, ce1adon commented
> > > @shurale-nkn Looks like jenkins is still down.
> > 
> > 
> > There were transient problems. It works somehow; I just restarted the job.
> 
> Is the Jenkins issue still persistent? I think devops upgraded and downgraded it today due to plugin compatibility issue

In this PR ,the Jenkins skips a lot of test stages. Not sure if this is related to the early jenkins issue.

2021-04-20 00:03 UTC, atamazov commented
> In this PR ,the Jenkins skips a lot of test stages. Not sure if this is related to the early jenkins issue.

That was done intentionally. I unchecked the most of build parameters (manually, in the Jenkins Web UI).

2021-04-20 15:29 UTC, atamazov commented
@ce1adon Please resolve https://github.com/ROCmSoftwarePlatform/MIOpen/pull/868#pullrequestreview-639129688 and I will merge it.

2021-04-20 17:43 UTC, ce1adon commented
> @ce1adon Please resolve [#868 (review)](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/868#pullrequestreview-639129688) and I will merge it.

I don't see param control lists on jenkins. Are all test stages disabled in default?

2021-04-20 19:06 UTC, atamazov commented
> 
> 
> > @ce1adon Please resolve [#868 (review)](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/868#pullrequestreview-639129688) and I will merge it.
> 
> I don't see param control lists on jenkins. Are all test stages disabled in default?

## At http://micimaster.amd.com/job/MLLibs/job/MIOpen, find your branch and click it.

![image](https://user-images.githubusercontent.com/12697412/115449239-3fa0f400-a223-11eb-971a-b11b0d594098.png)

## Click on "Build with parameters"

![image](https://user-images.githubusercontent.com/12697412/115449366-6828ee00-a223-11eb-9ab9-cd642efbef3e.png)

## Set build parameters as you wish and click [Build]
![image](https://user-images.githubusercontent.com/12697412/115450272-5d228d80-a224-11eb-9fe9-8a135ba3c26d.png)

2021-04-20 20:08 UTC, atamazov commented
@ce1adon When you update and push the branch, you may find that "**_Build with parameters_**" is not available, only "**_Build now_**".

In this case you need to give some time for Jenkins to detect and launch CI job (or better click "**_Scan repository now_**" and it will scan immediately). Then check that the job is actually launched and refresh the web page. You'll see that "**_Build now_**" is changed to "**_Build with parameters_**". Then terminate the just launched job and follow the instructions shown [above](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/868#issuecomment-823529901).

2021-04-20 23:41 UTC, ce1adon commented
@atamazov 
Is the [skip CI] commit key word still valid?

2021-04-21 00:45 UTC, atamazov commented
It should, but please use lowercase.

2021-04-23 16:49 UTC, ce1adon commented
This PR passed all the tests. Let me know if you request any change. I will revert the build param after addressing all comments.

2021-04-23 17:21 UTC, atamazov commented
@ce1adon The only leftover is https://github.com/ROCmSoftwarePlatform/MIOpen/pull/868#pullrequestreview-639129688.

2021-04-23 23:50 UTC, ce1adon commented
> @ce1adon The only leftover is [#868 (review)](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/868#pullrequestreview-639129688).

Please find latest commit for it.

2021-04-24 16:46 UTC, atamazov approved these changes

2021-04-24 16:50 UTC, merged