fix undefined behavior
ROCmSoftwarePlatform/MIOpen pull request #886
Opened 2021-04-23 01:24 UTC by ce1adon

2021-04-23 15:45 UTC, atamazov approved these changes
LGTM

2021-04-23 15:47 UTC, atamazov requested changes

2021-04-23 15:47 UTC, atamazov commented on test/ctc.cpp
> +            assert(aidx_t1s >= 2);
assertion failed at Fp32 Hip Debug CI stage.

2021-04-26 14:43 UTC, atamazov commented
@ce1adon Please have a look at CI, thanks.

2021-04-27 00:15 UTC, ce1adon commented on test/ctc.cpp
> +            assert(aidx_t1s >= 2);
Thanks! Fixed.

2021-04-27 16:18 UTC, shurale-nkn approved these changes
LGTM

2021-04-27 16:30 UTC, atamazov approved these changes

2021-04-27 16:30 UTC, merged