Fix for PR #775. Disable xdlops for non gfx908
ROCmSoftwarePlatform/MIOpen pull request #950
Opened 2021-05-23 22:02 UTC by shurale-nkn

Fixes bug in tests (partially unblocks #944)

Stage: FP32 OpenCL install all vega 20
and other non gfx908
Failed tests:
test_conv_igemm_dynamic_xdlops_fwd
test_conv_igemm_dynamic_xdlops_bwd
test_conv_igemm_dynamic_xdlops_wrw
Convolution cannot be executed due to incorrect params

2021-05-24 00:44 UTC, atamazov requested changes

2021-05-24 00:44 UTC, atamazov commented on test/CMakeLists.txt
> +    set(is_miotensile_chech)
```suggestion
    set(is_miotensile_check)
```

2021-05-24 00:45 UTC, atamazov commented
Merge conflicts

2021-05-24 00:45 UTC, atamazov commented
@shurale-nkn Basically, this looks good. Let's have a quick call tomorrow.

2021-05-24 08:07 UTC, shurale-nkn commented
First run passed CI

2021-05-26 22:36 UTC, atamazov requested changes

2021-05-26 22:36 UTC, atamazov commented on test/CMakeLists.txt
> +    set(MIOPEN_TEST_GFX906 FALSE)
Many tests can run on gfx900. Please rename GFX906 to VEGA everywhere.

2021-05-26 22:36 UTC, atamazov commented on test/CMakeLists.txt
> +        if(PARSE_PERF_TEST)
Please replace PERF_TEST with TEST_PERF_DB_RECORD_NOT_FOUND (yes, this looks terrible, so please feel free to invent something better, if you can)))

2021-05-26 22:38 UTC, atamazov commented
@shurale-nkn We'll need to explain the new features introduced in this PR -- the values of new attributes and their meanings, for example. Can you please prepare some internal documentation? Let's have a quick call tomorrow and discuss. Thanks.

2021-05-30 13:08 UTC, atamazov commented on test/CMakeLists.txt
> +option( MIOPEN_TEST_VEGA "Test arch VEGA mode" ON )
[Recommendation] 
```suggestion
option( MIOPEN_TEST_VEGA "Test arch VEGA (gfx900, gfx906)" ON )
```

2021-05-30 13:08 UTC, atamazov commented on test/CMakeLists.txt
> +#       Default: (gfx900&gfx906)=VEGA=enabled, GFX908=disabled.
```suggestion
#       Default: VEGA=enabled, GFX908=disabled.
```

2021-05-30 13:08 UTC, atamazov commented on test/CMakeLists.txt
> +#   (e.g. "HALF_ENABLE HALF DISABLE" is illegal)
```suggestion
#   (e.g. "HALF_ENABLE HALF_DISABLE" is illegal)
```

2021-06-03 18:01 UTC, atamazov approved these changes
LGTM!

2021-06-03 18:02 UTC, merged