fix issue #946
ROCmSoftwarePlatform/MIOpen pull request #951
Opened 2021-05-24 01:55 UTC by shaojiewang

kernel selection error for c or k padding cases

2021-05-24 02:30 UTC, carlushuang commented
This fix issue https://github.com/ROCmSoftwarePlatform/MIOpen/issues/946

2021-05-24 02:43 UTC, carlushuang approved these changes
LGTM

2021-05-24 04:10 UTC, junliume approved these changes

2021-05-24 07:47 UTC, shurale-nkn approved these changes

2021-05-24 19:40 UTC, atamazov requested changes
Please add regression tests (or explain why these are not required).

2021-05-25 02:33 UTC, shaojiewang commented
Performance will not regress. Because only c or k padding case with single batch conv is influenced. For these convolutions, right kernel is faster. Further more, we rarely use single batch to do backward propagation.

2021-05-25 04:02 UTC, junliume approved these changes

2021-05-26 22:40 UTC, atamazov approved these changes
LGTM!

2021-05-26 22:43 UTC, merged