fix NCHW bwd asm igemm solver with proper applicability
ROCmSoftwarePlatform/MIOpen pull request #952
Opened 2021-05-24 08:56 UTC by carlushuang

this fix issue https://github.com/ROCmSoftwarePlatform/MIOpen/issues/948, not WA.

test passed:
```
# MIOPEN_DEBUG_FIND_ONLY_SOLVER=ConvAsmImplicitGemmGTCDynamicBwdXdlops  LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt//conda/lib/ MIOPEN_LOG_LEVEL=5 MIOPEN_FIND_MODE=1 ./bin/MIOpenDriver convfp16 -n 8 -c 16 -H 5 -W 5 -k 8 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 2 -t 1 -V 1 2>&1
MIOPEN_DEBUG_FIND_ONLY_SOLVER=ConvAsmImplicitGemmGTCDynamicBwdXdlops  LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt//conda/lib/ MIOPEN_LOG_LEVEL=5 MIOPEN_FIND_MODE=1 ./bin/MIOpenDriver convfp16 -n 8 -c 16 -H 5 -W 5 -k 8 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 2 -t 1 -V 1 2>&1 | tee log.txt
MIOpenDriver convfp16 -n 8 -c 16 -H 5 -W 5 -k 8 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 2 -t 1 -V 1
MIOpen(HIP): Info [get_device_name] Raw device name: gfx908:sramecc+:xnack-
MIOpen(HIP): Info [Handle] stream: 0x1ae3c30, device_id: 0
MIOpen(HIP): Info [GetFindModeValueImpl] MIOPEN_FIND_MODE = NORMAL(1)
MIOpen(HIP): Info [BackwardDataGetWorkSpaceSize]
MIOpen(HIP): Info [HipCompilerVersionImpl] 4.2.21185
MIOpen(HIP): Info [AmdRocmMetadataVersionDetect] ROCm MD version AMDHSA_COv3, MIOpen version 2.12.0.0b58280-dirty
MIOpen(HIP): Info [GetEnvFindOnlySolverImpl] 82
MIOpen(HIP): Info [FindConvBwdDataAlgorithm] requestAlgoCount = 2, workspace = 0
MIOpen(HIP): Info [TryLoad] Find-db regenerating.
MIOpen(HIP): Info [FindSolutionImpl] ConvAsmImplicitGemmGTCDynamicBwdXdlops (not searchable)
MIOpen(HIP): Info [EvaluateInvokers] ConvAsmImplicitGemmGTCDynamicBwdXdlops: igemm_bwd_gtcx_nchw_fp16_bx4_ex1_bt16x32x8_wt8x32x4_ws1x1_wr1x1_ta1x1x1x1_1x8x1x16_tb1x1x2x1_1x8x1x16: 0.01232 < 3.40282e+38
MIOpen(HIP): Info [EvaluateInvokers] Selected: ConvAsmImplicitGemmGTCDynamicBwdXdlops: igemm_bwd_gtcx_nchw_fp16_bx4_ex1_bt16x32x8_wt8x32x4_ws1x1_wr1x1_ta1x1x1x1_1x8x1x16_tb1x1x2x1_1x8x1x16: 0.01232, workspce_sz = 0
MIOpen(HIP): Info [FindConvBwdDataAlgorithm] miopenConvolutionBwdDataAlgoImplicitGEMM   0.01232 0
MIOpen(HIP): Info [FindConvBwdDataAlgorithm] BWD Chosen Algorithm: ConvAsmImplicitGemmGTCDynamicBwdXdlops , 0, 0.01232
MIOpen(HIP): Info [ConvolutionBackwardData] algo = 5, workspace = 0
MIOpen(HIP): Info [ConvolutionBackwardData] algo = 5, workspace = 0
MIOpen(HIP): Info [ConvolutionBackwardData] algo = 5, workspace = 0
MIOpen(HIP): Info [ConvolutionBackwardData] algo = 5, workspace = 0
MIOpen(HIP): Info [ConvolutionBackwardData] algo = 5, workspace = 0
MIOpen(HIP): Info [ConvolutionBackwardData] algo = 5, workspace = 0
MIOpen(HIP): Info [ConvolutionBackwardData] algo = 5, workspace = 0
MIOpen(HIP): Info [ConvolutionBackwardData] algo = 5, workspace = 0
MIOpen(HIP): Info [ConvolutionBackwardData] algo = 5, workspace = 0
MIOpen(HIP): Info [ConvolutionBackwardData] algo = 5, workspace = 0
MIOpen Backward Data Conv. Algorithm: 5, Solution: 82/ConvAsmImplicitGemmGTCDynamicBwdXdlops
GPU Kernel Time Backward Data Conv. Elapsed: 0.011769 ms (average)
stats: name, n, c, ho, wo, x, y, k, flopCnt, bytesRead, bytesWritten, GFLOPs, GB/s, timeMs
stats: bwdd-conv2x2u1, 8, 16, 2, 2, 8, 4, 4,  131072, 3072, 2048, 11, 0, 0.011769
Backward Convolution Data Verifies OK on CPU reference (6.74569e-05)
```

2021-05-24 09:48 UTC, shaojiewang reviewed
Should ALLOW_HALF be reopened in ctest for this solver?

2021-05-24 10:44 UTC, shaojiewang submitted a review, later dismissed
LGTM

2021-05-24 19:43 UTC, atamazov commented
#948 asks for:
> Let's ... verify that https://ontrack-internal.amd.com/browse/SWDEV-286774 remains fixed, and remove W/A introduced in #945 and updated in #949.

Have you tested https://ontrack-internal.amd.com/browse/SWDEV-286774?

2021-05-24 19:44 UTC, atamazov requested changes
Can you please add regression test?

2021-05-24 19:46 UTC, atamazov commented
> this fix issue #948, not WA.

@carlushuang #948 is about possible performance regression (due to W/A in #945, #949). I am not sure if it is even possible to W/A a performance regression ;)

2021-05-25 07:53 UTC, carlushuang commented
> Have you tested https://ontrack-internal.amd.com/browse/SWDEV-286774?

Yes, I prepared the environment and following the steps in that issue, and apply this branch, that issue is also fixed. Here is the log with this PR, and run this command:
```
MIOPEN_FIND_MODE=1 MIOPEN_DEBUG_AMD_WINOGRAD_RXS_F2X3_G1=0     MIOPEN_DEBUG_CONV_IMPLICIT_GEMM_HIP_BWD_V4R1_XDLOPS=0 MIOPEN_ENABLE_LOGGING_CMD=1 MIOPEN_LOG_LEVEL=7 PYTORCH_TEST_WITH_ROCM=1 /opt/conda/bin/python3.6 distributed/test_data_parallel.py TestDataParallel.test_strided_grad_layout -v
```
[log_asm_igemm_bwd.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/6537463/log_asm_igemm_bwd.txt)

I used this command only to make sure there are multiple `ConvAsmImplicitGemmGTCDynamicBwdXdlops` can be selected. And of course if not apply that much environment variable, the test also passed

2021-05-27 06:39 UTC, carlushuang commented
Hi @atamazov please help review again this PR. I changed all the code you mentioned before

2021-05-27 12:17 UTC, atamazov approved these changes
LGTM!

2021-05-27 12:23 UTC, merged